### ISSUE TITLE
Transparency change w/ scroll unsets with Opacity when moving.

### ISSUE THREAD

**Issue by shelbyKiraM** [RamonUnch/AltSnap#100]
I have Opacity when moving set to 200, when I change opacity with Alt+scroll wheel, it changes but when I let go of Alt it resets to opaque (non-transparent).

**Comment by RamonUnch** [comment]
I cannot reproduce the bug.
Which windows version are you using? give me your .ini file (you can zip it and attach it in a post).

When a window has a specific transparency and you move it with AltSnap, then the opacity is set to 200, then it is restored to the old opacity at the end of the movement.

Maybe you would like an option to avoid changing transparency of windows that are already transparent.

**Comment by RamonUnch** [comment]
Actually if you are using the Action without Click, then indeed it makes some problems.
Use this build, it should fix it:
[AltSnap1.47test17bin.zip](https://github.com/RamonUnch/AltSnap/files/7203002/AltSnap1.47test17bin.zip)
[AltSnap1.47test17bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/7203003/AltSnap1.47test17bin_x64.zip)

**Comment by shelbyKiraM** [comment]
Nice! That does exactly what I intended, thanks! 👏🏼
