### ISSUE TITLE
Task Scheduler

### ISSUE THREAD

**Issue by xzayn** [RamonUnch/AltSnap#101]
![image](https://user-images.githubusercontent.com/74079803/134694772-9d6184cc-8f0e-46dc-b00a-dc8d5c9ab9b2.png)
Can you add this: Current I manually have to create a task in Task Scheduler that looks like this (a .xml file I cant attach here) with the help of Winaero Tweaker (Shortcut Elevate) and changing the trigger to "Every Logon". And it works, now if its possible can you integrate it within AS...

**Comment by RamonUnch** [comment]
What is the advantage over the `AltSnap.xml`already available in AltSnap directory?
You do not need *Winaero Tweaker* to add a task, just follow the instructions on the [wiki](https://github.com/RamonUnch/AltSnap/wiki#setup-auto-start)

1. In the Task Scheduler, select Action->Import Task... and select the AltDrag.xml file
2. Go into the Actions tab, double click on the path to AltDrag.exe and Update it.

**Comment by xzayn** [comment]
Overlooked that, thankyou!

**Comment by RamonUnch** [comment]
Ok, perfect, maybe i will rename the file to make it clearer, also i should include some beter help at some point
