### ISSUE TITLE
Not super important but can it show Volume flyout when I'm changing volume?

### ISSUE THREAD

**Issue by xzayn** [RamonUnch/AltSnap#103]

**Comment by RamonUnch** [comment]
Unfortunately, I think it is not possible.
I am using the mmdeviceapi, with the ole interface and I do not see such a way.

**Comment by xzayn** [comment]
That's okay. There's this app called ModernFlyouts which does related stuff ...

**Comment by RamonUnch** [comment]
@xzayn 
You may be interested in the test builds tht include this feature:
https://github.com/RamonUnch/AltSnap/issues/155
