### ISSUE TITLE
AltSnap is randomly closing itself after some time

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#107]
Ok, so I wasn't as sure of this bug but AltSnap is randomly closing itself after some time

_Originally posted by @xzayn in https://github.com/RamonUnch/AltSnap/issues/104#issuecomment-927104428_

**Comment by RamonUnch** [comment]
You can hide the tray using the tray menu,
You could maybe run for a while with the debug version:
[AltSnap1.47test22x64debug.zip](https://github.com/RamonUnch/AltSnap/files/7231605/AltSnap1.47test22x64debug.zip)

You have to open a command prompt in the folder, and type:
`gdb.exe AltSnap.exe`
Then gdb (the debugger) will start and you have to type the `r` command to run the program
at this moment altdrag will start and you can use your computer normally, a lot os messages will be displayed in the console that you must not close but you can ignore them until the point AltSnap crashes, at this moment i will be interested by the latest lines of the debug log. 
Note that usually the debugger will lock AltSnap state and thus lock the mouse, so once the mouse freeze, you have to alt+tab to the command prompt ant hit the `c` (for continue) command in the debug console until altdrag compleatly terminate. then send me the last lines of the debug log.

**Comment by RamonUnch** [comment]
@xzayn
Tell me if you still got some crashes with new 1.47 release

**Comment by xzayn** [comment]
I was still facing crashes so I decided to reinstall it//deleted it completed and did a fresh install... but it still crashes//without any logs...Happens when system left idle for a long time

**Comment by RamonUnch** [comment]
Note that I am curretly far from anything, with only an extreamly old XP computer and a very bad internet connection.

**Comment by RamonUnch** [comment]
@xzayn I made so more minor adjustments that might fix this crash...
[AltSnap1.48test1x64debug.zip](https://github.com/RamonUnch/AltSnap/files/7312799/AltSnap1.48test1x64debug.zip)

**Comment by RamonUnch** [comment]
Installer:
[AltSnap1.48test5-x64-inst.exe.zip](https://github.com/RamonUnch/AltSnap/files/7349134/AltSnap1.48test5-x64-inst.exe.zip)

**Comment by xzayn** [comment]
Thanks...altho I made the last one work after restarting... Ill let you know if the issue is fixed..

**Comment by xzayn** [comment]
No it still closes randomly...

**Comment by RamonUnch** [comment]
@xzayn 
Do you still have the crash under Windows 11 with the 1.48test13 build?

**Comment by szkrd** [comment]
I remember having this (or a very similar) bug with AltDrag on my previous work laptop - most of the time it happened after waking up from sleep or returning from the lock screen (in the end I created an autohotkey script to kill the frozen instance and just load a new one), but it never happened on my new machine, neither with AltDrag, nor with AltSnap. I know this is not much of a help, but heck, it did happen and I couldn't find the cause back then.

**Comment by RamonUnch** [comment]
Duplicate of #125
