### ISSUE TITLE
Found this on reddit...

### ISSUE THREAD

**Issue by xzayn** [RamonUnch/AltSnap#119]
https://www.reddit.com/r/AutoHotkey/comments/q8fu5h/using_winclick_on_mixmaxclose_buttons_to_set/

**Comment by RamonUnch** [comment]
Not a bad idea, even though I do not like much small targets such as those buttons, I will see what I can do about that.
What do you think on Ctrl+Alt+Middle click on the titlebar => toggles always on top? when the LowerWithMMB is on.

**Comment by RamonUnch** [comment]
>Shift+MMB on title bars when _Lower windows by middle-clicking on title bars is active or as an additional setting would be more consistent with AltSnap's typical input scheme.

True but Shift+MMB is already used for the minimize action.

**Comment by RamonUnch** [comment]
in 1.48 release
