### ISSUE TITLE
Win+Home as Mouse Action

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#122]
AltSnap's dragging doesn't have the aero shake mechanic, but fortunately windows provides the same functionality with the win+home (on qwerty) shortcut.
Would be nice to have this as a mouse action as a substitute for aero shake.

**Comment by RamonUnch** [comment]
This would be a "Minimize all other windows" action, quite straightforward to implement.
Does Aero-Shake minimize windows on all monitors or on the current monitor only?

**Comment by RamonUnch** [comment]
in 1.48 release
