### ISSUE TITLE
Alternative Snapping

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#123]
Similar to Windows, while holding Ctrl other snapped windows get ignored in the snapping and resizing process.

My suggestion:
Alternative Mouse action, respectively the modifier key reverts snapping behaviour to non-adaptive aero snapping.
Or maybe vice versa, meaning the modifier key activates the behaviour which isn't currently activated.

I would have suggested shift as it is the key for resizing other windows, but it's already reserved for zones.

**Comment by RamonUnch** [comment]
I am not sure I understand, it seems quite advanced considerations, could you give more details?

**Comment by Ichisich** [comment]
Simply put, a dragging mode which ignores other windows.
ALT+Leftclick -> smart aero snap dimensions
ALT+Leftclick+Modifierkey -> non-smart snapping

As I said, native windows does this already with Ctrl if you want to have an example.

**Comment by RamonUnch** [comment]
Ok, I get it now, maybe Ctrl could do the trick, but probably, I should do so that when pressing using space, that disable border-border snapping it should also disable smart aero snapping.

**Comment by Ichisich** [comment]
Space sounds good as an all around dumb mode

The problem with Ctrl would be, that if someone already mapped it as meta key instead of ALT and Shift is already in use for zones.

**Comment by RamonUnch** [comment]
Use this version of hooks.dll (for 64bit version of AltSnap).
[hooks1.48test15_x64.zip](https://github.com/RamonUnch/AltSnap/files/7492173/hooks1.48test15_x64.zip)
If you hit space, in addition to enabling/disabling border-border window snapping, it also disables/enables smart window snappig. You just should hit space, do not keep it down or it will toggle super fast...

**Comment by Ichisich** [comment]
I see, it's a switch.

Works, you can even toggle the behaviour after snapping/tiling.

**Comment by RamonUnch** [comment]
in 1.48 release
