### ISSUE TITLE
Portable?

### ISSUE THREAD

**Issue by FlarosOverfield** [RamonUnch/AltSnap#132]
AltDrag was portable but this still isn't five years later, any chance of this being portable?

**Comment by RamonUnch** [comment]
What are you taking about? Initially I only made the portable version, just look at the bin.zip files and extracts them somewhere, then doubleclick AltSnap.exe.
Files are:
AltSnap1.48bin.zip for i386
AltSnap1.48bin_x64.zip for AMD64 builds.

**Comment by FlarosOverfield** [comment]
oh i am pepega

**Comment by RamonUnch** [comment]
It is perfectly fine, I am the first to do this kind of overlook. Maybe I should change the name and add portable suffix, but I do not want to change the naming convention.
