### ISSUE TITLE
Sroll lock stat to pause/resume script Code please.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [RamonUnch/AltSnap#152]
Can i have the code you used in this where if i have scroll lock on - script paused.. and scoll lock off- script resumed..

i want to add it to one of my personal scripts.

**Comment by RamonUnch** [comment]
I use : `GetKeyState(VK_SCROLL)&1` to know if Scroll lock state is on or off. It is a Win32 C function exported by user32.dll

**Comment by PhoenixCODE2322** [comment]
thank you
