### ISSUE TITLE
Left-Click While Resizing

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#154]
Similar to this setting: `Toggle maximize state with right-click while moving`

Left-click while the right mouse button is pressed mimics the behaviour of double right-click into window fractions.

**Comment by RamonUnch** [comment]
Try with this copy of hooks.dll, it should handle side/corner snapping and maxV with the same setting:
i386 build: [hooks_1.50test4_i386.zip](https://github.com/RamonUnch/AltSnap/files/7985822/hooks_1.50test4_i386.zip)
x64 build: [hooks_1.50test4_x64.zip](https://github.com/RamonUnch/AltSnap/files/7985831/hooks_1.50test4_x64.zip)

**Comment by Ichisich** [comment]
Windows perform without objection (normal/inverted).

The only detriment is the poping up of the context menu in case the left mouse button gets unhanded first.

**Comment by RamonUnch** [comment]
I think i fixed it:
[hooks-1.50test5_x64.zip](https://github.com/RamonUnch/AltSnap/files/7986592/hooks-1.50test5_x64.zip)
[hooks-1.50test5_i386.zip](https://github.com/RamonUnch/AltSnap/files/7986595/hooks-1.50test5_i386.zip)

**Comment by Ichisich** [comment]
Perfect.
