### ISSUE TITLE
Visual indicator of volume change

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#155]
As suggested by @cojoMan [here](https://github.com/stefansundin/altdrag/issues/148), I modified the **Volume** wheel action to simply send the volume up/down keys, so it should show the volume indicator like whn using the multimedia keys.
Here are some test builds of AltSnap.

[AltSnap1.50test1bin.zip](https://github.com/RamonUnch/AltSnap/files/7964121/AltSnap1.50test1bin.zip)
[AltSnap1.50test1bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/7964122/AltSnap1.50test1bin_x64.zip)
[AltSnap1.50test1-installers.zip](https://github.com/RamonUnch/AltSnap/files/7964123/AltSnap1.50test1-installers.zip)

**Comment by cojoMan** [comment]
Oh wooow, I didn't know about this fork, so many new options. Checking it out !

**Comment by cojoMan** [comment]
works wonder, thank you, already switched, and checking out the other options !

**Comment by RamonUnch** [comment]
You might be interested in looking at the wiki for more details: https://github.com/RamonUnch/AltSnap/wiki

**Comment by Ichisich** [comment]
@RamonUnch 
Great addition. 
But wheel input still doesn't get recognized on the desktop as long as the mouse cursor isn't in a window or the taskbar.
This is not a regression, and was, to my knowledge, always the case with altdrag/snap.

I guess you're using the [SystemMediaTransportControls](https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-22000) API to show the overlay?
If so, you could also add the instructions:
`Volume_Mute`
`Media_Play_Pause`
`Media_Prev`
`Media_Next`

**Comment by RamonUnch** [comment]
> But wheel input still doesn't get recognized on the desktop as long as the mouse cursor isn't in a window or the taskbar.
This is not a regression, and was, to my knowledge, always the case with altdrag/snap.

The desktop is in the scroll blacklist. Just clear this blacklist if it if you want to be able to adjust volume everywhere.
I do not want to have a separated blacklist for every action...

I actually just send the multimedia vkeys to the system and Windows shows himself the appropriate volume control. Multimedia keys are:
vKey|HEX|Description
-- | -- | --
VK_VOLUME_MUTE | 0xAD | Volume Mute key
VK_VOLUME_DOWN | 0xAE | Volume Down key
VK_VOLUME_UP | 0xAF | Volume Up key
VK_MEDIA_NEXT_TRACK | 0xB0 | Next Track key
VK_MEDIA_PREV_TRACK | 0xB1 | Previous Track key
VK_MEDIA_STOP | 0xB2 | Stop Media key
VK_MEDIA_PLAY_PAUSE | 0xB3 | Play/Pause Media key

How do you think the other keys could be used?
New actions for each key?

**Comment by Ichisich** [comment]
> The desktop is in the scroll blacklist.

Sorry, I just looked at the process blacklist.

> I actually just send the multimedia vkeys to the system and Windows shows himself the appropriate volume control.

Neat, so it works with Windows prior to 8/10 as well.
 
> How do you think the other keys could be used? New actions for each key?

For `Mute` and `Pause/Play`, yes.
`Next/Prev` could be mapped to the wheel, same as `Volume`, and `Stop` is somewhat superfluous with `Pause/Play` existing.

**Comment by RamonUnch** [comment]
> For `Mute` and `Pause/Play`, yes.
> `Next/Prev` could be mapped to the wheel, same as `Volume`, and `Stop` is somewhat superfluous with `Pause/Play` existing.

After some testing, it seems that those keys have to be sent to the playing application. So to use them you would need to focus the media player, this would make those Play/Pause/Stop and Next/Prev actions a bit "useless" to me. When thinking about it it is obvious, for a program to handle those key without focus, they would need a low level keyboard hook.

`Mute` is handled by the system (like the volume) so it works as intended. I will add this one for sure.

**Comment by cojoMan** [comment]
> The desktop is in the scroll blacklist. Just clear this blacklist if it if you want to be able to adjust volume everywhere. I do not 


For the uninitiated, what is the process I have to remove from the blacklist to have the volume act on desktop hovering as well ?
Currently the windows blacklist looks like this :

Program Manager|Progman,*|MultitaskingViewFrame,Volume Control|Tray Volume,Volume Control|Windows.UI.Core.CoreWindow,*|TaskSwitcherWnd,*|TaskSwitcherOverlayWnd,|WorkerW,|Shell_TrayWnd,|BaseBar,|#32768,*|XamlExplorerHostIslandWindow,*|TSSHELLWND

**Comment by Ichisich** [comment]
https://github.com/RamonUnch/AltSnap/wiki#blacklists

![Unbenannt](https://user-images.githubusercontent.com/31080003/152036398-87fa1f0e-03d5-4812-b089-c9f34d462722.png)

You can either delete the marked entry or just comment it out.
