### ISSUE TITLE
Generalization of title bar actions (w/o hotkey)

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#158]
I would either go full hardcoded or general.
Whatever is mapped to the LMB contrasted to MMB specifically lowers and Shift+MMB specifically minimizes isn't really consistent.
I would either hardcode movement in the title bar to left-click, or just let all buttons be active in the title bar without hotkey, including non-drag-actions using the primary actions.

I'd advocate for general. 
Shift+MMB is already redundant, when you have to press a key plus mouse, you can just minimize with a standard hotkey-action.

With non-drag-actions included, you could use 7 actions without any hotkey.
e.g. my setup:
LMB=moves -> NDA=maximizesHV -> CK=maximizes
MMB=closes
RMB=resizes -> NDA=minimizes
MouseWheel=Volume

Admittedly, resizing isn't really thrilling and always better done by a hotkey-action, grid or zones.

_Originally posted by @Ichisich in https://github.com/RamonUnch/AltSnap/issues/110#issuecomment-1029257269_

**Comment by RamonUnch** [comment]
So my plan is:
Remove Lower with MMB and replace "normal" movement options to have:
```
LMBT=Nothing
MMBT=Lower
RMBT=Nothing
MB4T=Nothing
MB5T=Nothing
+ the B sufixed varients
```
So that you can setup any action to be performed when clicking on the title bar without needing to press the hotkey.
This also will have to be added to the GUI, It should not be hard to add it without messing up too much.

Then the same will have to be done for wheel actions (that are a bit separated) probably not for the next release though.
To simulate Use AltSnap for normal movement you will need to use `LMBT=Move`, to simulate Lower with MMB tou will have to set `MMBT=Lower`, but you will have a lot more options.

**Comment by RamonUnch** [comment]
Well the wheel action will also be implemented, so the RollWithTBScroll will be disabled as redundent...

**Comment by RamonUnch** [comment]
@Ichisich here is a beta builds of the generalized title bar actions:
Keep a backup of your previous install because there will probably be problems.
[AltSnap1.50test10bin.zip](https://github.com/RamonUnch/AltSnap/files/8007966/AltSnap1.50test10bin.zip)
[AltSnap1.50test10bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/8007967/AltSnap1.50test10bin_x64.zip)

Do not bother yet with the translation, it may change more in the future

**Comment by Ichisich** [comment]
That's more sophisticated than I anticipated.
To be honest, I would streamline it.

Suggestion:
Normal(not intuitive in itself)->Primary/Alternate and Titlebar->Primary/Alternate in a flat rectangular array is too overwhelming for the uninitiated.
I would stick to just three entries, Primary/Alternate/Titlebar and keep TitlebarB in the .ini for power users.

**Comment by Ichisich** [comment]
Or, in case you want to keep TitlebarB in the GUI, I would arrange it like this:
![array](https://user-images.githubusercontent.com/31080003/152643351-579f9bf0-c45e-424e-994f-f752a28d4e0c.png)

**Comment by RamonUnch** [comment]
That is indeed much better...

**Comment by RamonUnch** [comment]
Actually I think I will opt for the even simpler Primary/Alternate/Titlebar because the main point of Titlebar action is to avoid keyboard.

**Comment by RamonUnch** [comment]
Also an important info: when you use a click combo, the titlebar action is never used for the second click because AltSnap the cursor hides what is below. It would be possible to change this but I think it is ok like this and the implementation is simpler.:
Example (ignoring 'B' actions):
You map like default: LMB=Move, RMB=Resize
then LMBT=Move, and set RMBT=Minimize, then if you start moving the window (via the titlebar or with Alt+LMB) the maximize combo will happen on RMB, because the action of RMB corresponds to 'Resize', not Minimize.

**Comment by RamonUnch** [comment]
Well here is a more cleandup version, where the wheel+button code is better unified and there is less duplicate code.
I fixed some regressions, concerning inactive scroll (not applying to Win10/11), I may have added more though, but refactoring has to happen at some point.
GUI has been improved with your suggestions.
[AltSnap1.50bintest12_x64.zip](https://github.com/RamonUnch/AltSnap/files/8014381/AltSnap1.50bintest12_x64.zip)
[AltSnap1.50bintest12.zip](https://github.com/RamonUnch/AltSnap/files/8014384/AltSnap1.50bintest12.zip)

Options that have changed:
NEW:
```
GeneralPiercingClick=Avoi&d blocking Alt+Click

InputActionMute=Mute &sounds

InputMouseINTTB=In &Titlebar
InputMouseTTBActionBox=Use specific actions when clicking the Title bar
InputMouseTTBActionNA=Without hot&key
InputMouseTTBActionWA=&With hotkey
```

Removed:
```
InputMouseLowerWithMMB=&Lower windows by middle clicking on title bars
InputMouseRollWithTBScroll=Ro&ll/Unroll windows with Alt+Scroll on title bar
AdvancedNormRestore=Restore AltDrag snapped windows with &normal move
AdvancedTitlebarMove=&Use AltSnap for normal titlebar movement
```
Of course, tell me if you got problems, this is still beta area.

**Comment by Ichisich** [comment]
Test10 already ran pretty flawlessly, so does Test12 as far as I can tell.

Suggestions:
I noticed that the `Title bar` option gets greyed out in case no title bar action is selected.
I would replicate this with `Alternate` as well, in case no modifier key is mapped.

Furthermore, I would add, that `Avoid blocking ALT+Click` disables AltSnap-Doubleclicks.

**Comment by RamonUnch** [comment]
> I noticed that the Title bar option gets greyed out in case no title bar action is selected.
I would replicate this with Alternate as well, in case no modifier key is mapped.

It should already be the case. are you sure you have no alternate, hotkey mapped?
Also you need to press Apply for it to gray/ungray. maybe check the .ini for `ModKey`.

You are right, the text should be changed as you say:
`GeneralPiercingClick=Avoi&d blocking Alt+Click (also disables AltSnap double-clicks)`

**Comment by Ichisich** [comment]
> It should already be the case.
Yes it is, I switched tabs without applying.
