### ISSUE TITLE
[Help] Kodi window not affected

### ISSUE THREAD

**Issue by cojoMan** [RamonUnch/AltSnap#161]
Running Kodi on Windows 10, and it seems to be the only window that does not drag/resize. All others present at the same time seem to. Not sure how to debug this. Haven't added a specific rule for the app to be excluded or anything.

Current Blacklist tab looks like this :

Process Blacklist : Virtual PC.exe,StartMenuExperienceHost.exe,SearchApp.exe
Windows Blacklist : Program Manager|Progman,*|MultitaskingViewFrame,Volume Control|Tray Volume,Volume Control|Windows.UI.Core.CoreWindow,*|TaskSwitcherWnd,*|TaskSwitcherOverlayWnd,|WorkerW,|Shell_TrayWnd,|BaseBar,|#32768,*|XamlExplorerHostIslandWindow,*|TSSHELLWND
Windows that should ignore scroll action : 
MDIs not to be treated as such : *|PPTFrameClass,*|MMCMainFrame,*|classFoxitReader

**Comment by cojoMan** [comment]
not sure how to atach a picture, but it says :
**Kodi|Kodi**

**Comment by Ichisich** [comment]
@cojoMan 
Kodi only responses to elevated AltSnap.

**Comment by cojoMan** [comment]
thank you

**Comment by RamonUnch** [comment]
Funny I would not have expected this from a non-elevated program.
I will mention it in the wiki.
