### ISSUE TITLE
Handling Borderless Windows

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#164]
It seems there is a conflict with the setting `Resize all windows`.

In case this setting is unchecked, resizing borderless windows becomes also impossible.
Snapping, maximizing and Zones, anything that contains some form of resizing in its process becomes inaccessible, too.

**Comment by RamonUnch** [comment]
Maybe I should add a flag to all windows that have been borderdisabled by altsnap so that they are still considered resizable.

**Comment by Ichisich** [comment]
Considering that there are only a few native borderless applications, and those can be included into `AResize`, it would almost fix all perceived inconsistencies.

**Comment by RamonUnch** [comment]
This one should do it:
[AltSnap1.50test23.zip](https://github.com/RamonUnch/AltSnap/files/8091346/AltSnap1.50test23.zip)

**Comment by RamonUnch** [comment]
I guess some people liked to be able to add borders, I should adjust the function to make it still possible probably, I will see.
