### ISSUE TITLE
MB4B/MB5B Regression

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#167]
Mapping MB5B in the GUI does map MB4B instead.
Mapping MB4B in the GUI will be discarded.

Both 32bit and 64bit versions are affected.
I also tested back to 1.50test12/test16/test24, and they all show the same bug.

AltSnap1.49 isn't affected.

**Comment by RamonUnch** [comment]
Indeed there is a bug in the GUI (bad copy/paste when I made the title bar actions).
[AltSnap1.50fix_x64.zip](https://github.com/RamonUnch/AltSnap/files/8102475/AltSnap1.50fix_x64.zip)
This exe should fix it.
This is enough for a new release (quite big bug) but I might wait a little as well in case more problems occur.

**Comment by Ichisich** [comment]
A shame I didn't find it sooner in the test build prior to release.
The .ini wasn't/isn't affected, so all my settings were always transferred properly.

**Comment by RamonUnch** [comment]
It is alright, I was expecting regressions, not so many people I think are using 5 button mouses (I just got one recently), plus not everyone uses the secondary action. 1.50 makes big changes so I do not think people will be mad or anything.
Thanks a lot for reporting so quickly, this is not your fault at all, I am responsible for this kind of mistakes.

**Comment by RamonUnch** [comment]
[1.51](https://github.com/RamonUnch/AltSnap/releases)
