### ISSUE TITLE
Horizontal Aero Snap

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#179]
Horizontal borders won't get recognized after resizing:
https://user-images.githubusercontent.com/31080003/156890458-de015c07-a82b-47ad-992b-872e7cfab5ad.mp4

Dragging leads to the desired behaviour:
https://user-images.githubusercontent.com/31080003/156890475-125adab0-d4f5-41e4-998b-18f8988a8c6a.mp4

**Comment by RamonUnch** [comment]
Yes indeed, the reason is that the right window was snapped to the LEFT, then resized, it still has the LEFTONLY snapping flag and not the BOTTOM_LEFT flag, I should fix it by ensuring that the *smarter* aero snapping algoritm is used in priority. to the smart mode instead of afterward.

**Comment by RamonUnch** [comment]
this one should fix it when using Smarter aero snapping
[hooks1.53test11_x64.zip](https://github.com/RamonUnch/AltSnap/files/8192203/hooks1.53test11_x64.zip)

**Comment by Ichisich** [comment]
It does.
