### ISSUE TITLE
Feature Request: Alt+Shift resizing from center of window to expand only left/right or up/down (`ResizeCenter=1`)

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltSnap#18]
It would be cool if Alt+Shift when right-click dragging from the center of the window (ResizeCenter=1), only expanded left/right, or up/down, instead always in all directions. Ideally, you would be able to grab anywhere inside this center box, and if you click-and-drag for over maybe 10px(?) left/right, then resize both +x/-x until releasing the mouse button. If up/down is the first to be clicked-and-dragged over 10px(?), then do the same but for +y/-y. Maybe there is a way to change your mind after starting left/right, or it could just be locked until your next click.

From https://github.com/RamonUnch/AltDrag/issues/7#issuecomment-768541942.

**Comment by RamonUnch** [comment]
@redactedscribe and @vipersniper0501
I am not sure I 100% understand this feature request but I think you might be happy to have Shift to lock the resize vertically or Ctrl to lock it horizontally when you are in the center resize mode.
Have a try with this one (beta build).
[AltSnap1.47test18.zip](https://github.com/RamonUnch/AltSnap/files/7205911/AltSnap1.47test18.zip)

**Comment by RamonUnch** [comment]
Use 1.47 release
