### ISSUE TITLE
Add a mark to the top windows,

### ISSUE THREAD

**Issue by irrealizable** [RamonUnch/AltSnap#184]
Add a mark to the top windows, similar to deskpins. Add a pushpin to the top windows, so that you can intuitively know which windows are topped

**Comment by RamonUnch** [comment]
related to #90
I understand your concern but actually I am not really willing to do this because it would require AltSnap to be much more intrusive as it would have to inject drawing code inside other programs which is unsafe unless I was 100% sure there are no bugs in my code.

**Comment by RamonUnch** [comment]
> The context menu item(Action menu) should also have a checkmark when the option is activated.

I agree, This is an easy one.

> Maybe have a border around the window like how powertoys alwaysontop utility does it.

I will investigate How PowerToys makes this

**Comment by xan2622** [comment]
Hi @RamonUnch. 👋
Thank you for developing AltSnap!

> Add a mark to the top windows, similar to deskpins. Add a pushpin to the top windows, so that you can intuitively know which windows are topped

You might want to take a look at [pinwin](https://github.com/VictorZakharov/pinwin) 's source code. This is exactly what it does.

**Comment by RamonUnch** [comment]
>Is the window border still a won't fix?

For now it is still a won't fix, or at least not soon.
Implementing a keyboard only shortcut is another story as it would not require to inject code into other processes.

**Comment by meihus** [comment]
Similar to deskpins, there is a prompt in the title bar, I am looking forward to this function, otherwise I don't know if this window is on top。

**Comment by RamonUnch** [comment]
This would not be hard to implement indeed quite an ugly mess however.

I will eventually add the option to make a custom action that just sends a key sequence so it will become a thing automatically.

What is the problem with PowerToys' AlwaysOnTop activation method? does it only support a keyboard shortcut?
How are PinWin or PowerToys' AlwaysOnTop unable to fulfill your requirements on the *only feature* they are supposed to implement?

**Comment by RamonUnch** [comment]
I think this could be submitted as a feature request to both of them.

Also you may be interested in the eXtra Buttons, that also has a topmost option
http://www.xtrabuttons.com/

The good thing about this topmosty option is also that it properly toggled when when you topmost/lower the window, with AltSnap.

**Comment by xan2622** [comment]
> I would like to suggest a solution which is a compromise.
> It involves using AltSnap along with the Powertoys AlwaysOnTop.
> There could be an advanced option in the .ini which allows you to send a hotkey instead when you select the always on top action from the action menu.
> That hotkey will be the hotkey to activate the Powertoys Alwaysontop.
> That way AltSnap users can use it in combination with Powertoys Alwaysontop and get their always on top windows marked.
> Would that be possible?

Your solution relies on using another third party utility : PowerToys. 🤨  But not everyone uses it.

> I quite like the PoweToys' AlwaysOnTop and the way it marks on top windows

I did understand that you suggested to use PowerToys AlwaysOnTop alongside AltSnap because of the way PowerToys AlwaysOnTop makes "windows on top" visible with the colored borders (which is a nice way to show it, I don't deny it). 
Another nice way to show it, IMO, [as I suggested earlier](https://github.com/RamonUnch/AltSnap/issues/184#issuecomment-1183958085), is to add a "pin icon" 📍 on the titlebar when AltSnap makes the window always on top. 

AltSnap can already make windows always on top thanks to a hotkey (ALT + a mouse button). Altsnap just needs to visually show that a window is always on top, that being with a colored border or thanks to a pin icon. I would be happy with either each solution.

> The pinwin method of selecting a window from a menu isn't really the most user friendly
That's not how pinwin works. To make a window always on top with it, you just have to click on the pinwin icon in the taskbar then click on the targeted window. That's all.
Btw, if I suggested RamonUnch to take a look at pinwin's source code, it's just in case he wanted to reuse the code that adds a pin icon onto the titlebar, not the way pinwin manages to make windows always on top.

**Comment by xan2622** [comment]
What about this suggestion: 
- RamonUnch finds a way to implement colored borders for windows that are _always on top_.
- And he adds the possibility, in the `AltSnap.ini` file, to type an extra keyboard hotkey (for example, Win+Ctrl+T) to toggle the _always on top_ . This way, there would be two hotkeys to toggle it, a mouse shortcut and a keyboard shortcut.

**Comment by xan2622** [comment]
I am not a developer so excuse my ignorance:
Adding a colored border to a window or adding a pin to the titlebar necessarily requires to "inject code" ?
If it does, does that mean that both PowerToys and PinWin "inject code" ?

**Comment by RamonUnch** [comment]
In all cases they use or code injection or dirty hacks.

I realize that this feature actually has quite some importance, and alternative software are not good enough.
I am working on an implementation, it is not perfect but at least it will get the job done. and it will just be a few tens extra lines of code and not a a huge megabyte project.

**Comment by RamonUnch** [comment]
here we go:
set `TopmostIndicator=1` in the `[Advanced]` section of the .ini file
You can also set the `PinRate` value in milliseconds between two position refresh. Default is 32.
larger values will give better performances, but less reactive pin position.
The pin is not a pin but just a simple square.

It will not work perfectly with monitors that have different DPI settings, but I am working on it.I will need feedback because I have no more Win10 machines and I have no powerful enough PC to run it in a VM of any kind.

```
in the [Advanced] section
TopmostIndicator=1
PinRate=32

in the [Input] section
PinColor=FF FF 00
; FF FF 00 = Yellow
; FF 00 00 = Red
; 00 FF 00 = Green
; etc.
```

[AltSnap1.55test26_x64.zip](https://github.com/RamonUnch/AltSnap/files/9316483/AltSnap1.55test26_x64.zip)
[AltSnap1.55test26_i386.zip](https://github.com/RamonUnch/AltSnap/files/9316484/AltSnap1.55test26_i386.zip)

I am actually not sure it will work at all on Win10 for now...

**Comment by Ichisich** [comment]
Works, even with borderless windows and elevated ones.
![alwaysOntop](https://user-images.githubusercontent.com/31080003/184373342-91f3aed1-d0b7-43f0-899b-4e127ae3ee5e.png)

The only exception I found this early is the `ApplicationFrameWindow` class.

**Comment by xan2622** [comment]
Here on Windows 11 it works too: 
![ShareX_bzhX1HD6Jm](https://user-images.githubusercontent.com/1732773/184376127-52ae7502-5306-4c2a-8bb0-23deb6c756e3.gif)

**Comment by RamonUnch** [comment]
Well I am glad to see that!

I will make some more efforts for per-monitor DPI setup, it should not be hard.

**Comment by RamonUnch** [comment]
Also if you left-click the indicator, it will disappear and remove topmost attribute.
If you disable AltSnap it will also remove all indicators and the associated topmost attributes. This might ba an annoyance if you often enable/disable AltSnap via the tray icon. However I prefer to keep it this way (would be annoying to change). 
You can use the ScrollLock key to suspend/resume AltSnap and not have this problem.

**Comment by RamonUnch** [comment]
Well this version also adds a context menu of all topmost windows when you right click the indicator.
I thought thiw would make sense, it just takes 5 extra lines of code.
![Image2](https://user-images.githubusercontent.com/74856804/184407455-6329ed64-d590-47e3-91b7-a7962a73882d.png)


[AltSnap1.55test27_i386.zip](https://github.com/RamonUnch/AltSnap/files/9328609/AltSnap1.55test27_i386.zip)
[AltSnap1.55test27_x64.zip](https://github.com/RamonUnch/AltSnap/files/9328617/AltSnap1.55test27_x64.zip)

**Comment by RamonUnch** [comment]
@irrealizable does it work for you?

Again small improvements, it now displays a T in the indicator (I think it looks beter like this).
Also the option is available via the GUI.

[AltSnap1.55test28_x64.zip](https://github.com/RamonUnch/AltSnap/files/9331615/AltSnap1.55test28_x64.zip)
[AltSnap1.55test28_i386.zip](https://github.com/RamonUnch/AltSnap/files/9331616/AltSnap1.55test28_i386.zip)

@xzayn,
You asked for this AltSnap feature some time ago in Issue #90, I guess you would be interested in this build.

**Comment by xan2622** [comment]
Thank you RamonUnch for all that you've done regarding this feature request. It works very well. 👍
I kind of prefered the colored rectangle without the " T ", but I guess it's just a matter of UI design preference. 🙂

**Comment by RamonUnch** [comment]
I think I will make the letter configurable, should be *trivial*, there are no reasons to force it anyway, as you say.

**Comment by xan2622** [comment]
I have just tested AltSnap 1.55 and if I am glad there's an option to display the colored rectangle (the indicator) on the titlebar, I think that this checkbox should be ticked ✅ (enabled) by default. 

![hjkghk](https://user-images.githubusercontent.com/1732773/185746883-1ee4aad2-3dbb-48ad-b246-4529a5b858c5.jpg)

On a side note, notice how the line "Show an indicator on always on top windows" (at the bottom) is a bit truncated.
My resolution is 3840x2160 with 125% DPI scale.

**Comment by Ichisich** [comment]
@xan2622 
FYI, In case you still use your old altsnap.ini `Pinrate` is now supposed to be in the performance section,

**Comment by RamonUnch** [comment]
Yes I see i was not very carefull about that.
Indeed the PinRate was moved to the performance section because it belongs there.

**Comment by RamonUnch** [comment]
I did not enable it by default because it is a bit hacky and the default ini files tries to be as baseline as possible.

**Comment by RamonUnch** [comment]
Yes it is but it will take time as for now actions have no parameters, so it would require re-writing quite some code.

**Comment by emvaized** [comment]
Could it be possible to add different options for the indicator? For example, bold window outline (the way PowerToys implemented it), or some customization options for the existing indicator (width, height, color, border radius, text, etc)? 
Thanks
