### ISSUE TITLE
Borderless Window Interaction

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#185]
Would it be possible to let windows interact with borderless windows as if they had borders?

**Comment by RamonUnch** [comment]
You mean for snapping I guess?
You already have the `Snaplist` in the `[Blacklists]` you an add any window inside it.
If you want all borderless windows to be snapped to then you can set:
`Snaplist=*|*` then if you want to exclude a specific borderless window you can still add it after the `*|*`

Default snaplist:
```
Snaplist=*|BaseWindow_RootWnd,*|SkinWnd,*|ChatSkinWnd,*|SpotifyMainWindow,*|USurface_*,*|Winamp*,*|M4W_MainWindow,*|SunAwtDialog
; List of windows that should be snapped to, even though they have no caption.
; Use Snaplist=*|* if you want to enable snapping to all border-less windows.
```

Also all windows that were made borderless by AltSnap should be snapped to.

**Comment by Ichisich** [comment]
Ok, `Snaplist `it is.

> Also all windows that were made borderless by AltSnap should be snapped to.
Not with my hooks.dll it seems.

**Comment by Ichisich** [comment]
I made a strange discovery.
When all borderless applications are recognized via `Snaplist=*|*` some invisible borders are present on the desktop.

They're random and can be vertical and horizontal.
Some examples:
https://user-images.githubusercontent.com/31080003/166662320-5c361b2c-be31-4c35-b12c-acc111dc31dd.mp4

I just whitelisted the applications I usually use borderless, either native or with AltSnap and the borders aren't present any more.
Unfortunately, I couldn't pin down which application is responsible, but it seems *|* can have some caveats to consider.

**Comment by RamonUnch** [comment]
Yes there are some invisible windows on the desktop, this is one of the reason of the snaplist.
Maybe you can Identify some of those window and add them after the `*|*` so they that they are excluded from the snaplist. I am not sure it would work.

**Comment by RamonUnch** [comment]
In version 1.53 all windows that were made borderless by AltSnap will be snapped to.
