### ISSUE TITLE
Balance Preserving Audio Control

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#186]
Windows has the quirk to reset the balance settings when lowering the volume to 0.

To illustrate, lowering the volume to 2 keeps the balance:
https://user-images.githubusercontent.com/31080003/165258195-50adf903-9af6-4e36-9294-75e547ade386.mp4

Lowering to 0 resets the balance:
https://user-images.githubusercontent.com/31080003/165258250-3eef6be6-815c-426b-bdde-ffda2343e1bd.mp4

Muting also keeps the balance:
https://user-images.githubusercontent.com/31080003/165258320-7443a589-4aa0-4ed2-85b7-e8bef34e9a2e.mp4

To counter this quirk, I adapted my autohotkey-script to mute instead of lowering the volume from 2 to 0.

AppsKey & PgDn::
SoundGet, Volume
if (Volume >= 4) 
{
Send {Volume_Down}
return
} else {
Send {Volume_Mute}
return
}

Would be nice if Altsnap could handle volume control similar.

**Comment by RamonUnch** [comment]
Interesting, I never realized this bug was here. It seems it was already there even on Windows XP/7 and I guess Microsoft is not going to fix it, so better avoid it as you suggest.
I guess Microsoft considers this like a feature.

**Comment by RamonUnch** [comment]
[AltSnap1.62test20_x64.zip](https://github.com/RamonUnch/AltSnap/files/13418874/AltSnap1.62test20_x64.zip)

Should fix it.
When you decrease volume it will mute instead of setting to Zero.
