### ISSUE TITLE
Lowering Window also start displaying rainmeter skins .

### ISSUE THREAD

**Issue by PhoenixCODE2322** [RamonUnch/AltSnap#189]
Altsnap 1.52

I have set title bar middle click to lower the window waitout hotkey. when i lower a window my rainmeter skin shows up - "Unfold" with setting -
![image](https://user-images.githubusercontent.com/75798544/166127252-d6045029-3872-401c-9852-59ec378d6d5c.png)

do i have to raise this issue in rainmeter forum ?

**Comment by RamonUnch** [comment]
I need to investigate this, I never used Rainmaker...

**Comment by RamonUnch** [comment]
Is this new to 1.52 or was it the same with older AltSnap versions?

**Comment by Ichisich** [comment]
I wasn't able to replicate the described behaviour with the default illustro skin and setting.
Could you share your usual Skins (Transparent?) and Rainmeter.ini?

**Comment by RamonUnch** [comment]
I am also unable to reproduce the bug. When I lower a window the Rainmaker settings window does not popup.
Maybe you have extra auto-hotkeys scripts that are making funny interactions. Try to disable all your desktop enhancements tools and re-enable them one by one to see if you can spot the interacting programs.

**Comment by PhoenixCODE2322** [comment]
> Is this new to 1.52 or was it the same with older AltSnap versions?

i tried the old version 1.51x64.zip , same thing happened. is portable version the casue ?

**Comment by PhoenixCODE2322** [comment]
> I am also unable to reproduce the bug. When I lower a window the Rainmaker settings window does not popup. Maybe you have extra auto-hotkeys scripts that are making funny interactions. Try to disable all your desktop enhancements tools and re-enable them one by one to see if you can spot the interacting programs.

Sorry, i didn't mean the setting windows.. the skins are the one that starts displaying.. i will attach some screenshot here.. 

note- below are the things that i did and found this out.. lets say 3 windows are opened on top of each other. after lowering all the windows one by one , then at the end or after lowering that last 3 application, the rainmeter skins pop up. 

![image](https://user-images.githubusercontent.com/75798544/166404200-837e7f99-92a2-4285-b023-1250e6691f16.png)


And now open bunch of windows and try to lower one by middle clicking on the title bar.

![image](https://user-images.githubusercontent.com/75798544/166404453-95c9a390-ec58-4730-88e0-da711397b907.png)

**Comment by RamonUnch** [comment]
OK, I get it, you are 100% correct indeed, all the small rainmaker skin windows are actually *normal* windows and they can be moved around above/below the other windows.
The only way to fix this would be to add a new blacklist of windows that are supposed to be bottom-most below which other windows should not lower. This would require re-writing the lower action to lower to the highest non-blacklisted window.

Maybe there would be a way for rainmaker to have windows that are really integrated in the desktop like widgets did in Windows Vista/7 but I am not sure it would work.

It should be possible for AltSnap to avoid this bug anyway, I will investigate...

**Comment by RamonUnch** [comment]
I am not sure btw that this would be considered a bug by everyone because the current behavior can be seen as an advantage as you can now interact with the skin windows.

**Comment by RamonUnch** [comment]
Here is a fixed version:
First replace AltSnap.exe and hooks.dll with the appropriate versions below (32bit or 64bit builds)
[AltSnap1.53_test19_i386.zip](https://github.com/RamonUnch/AltSnap/files/8609467/AltSnap1.53_test19_i386.zip)
[AltSnap1.53_test19_x64.zip](https://github.com/RamonUnch/AltSnap/files/8609468/AltSnap1.53_test19_x64.zip)

Then add the Bottommost list in the in the `[Blacklist]` section:
```
Bottommost=*|RainmeterMeterWindow
; List of windows that should be kept below other Windows that are lowered
; by AltSnap. Default is *|RainmeterMeterWindow for Rainmaker skin windows.
```
It does not work at 100%, sometime some windows will no longer want to lower, but it mostly work for now.
You can of course add more windows if you want them to stay bottommost.
Of course if you take a rainmaker skin windows and move it above other windows then you will have trouble lowering windows that are above.

**Comment by PhoenixCODE2322** [comment]
> I am not sure btw that this would be considered a bug by everyone because the current behavior can be seen as an advantage as you can now interact with the skin windows.

yes i thought the same .. lol

**Comment by PhoenixCODE2322** [comment]
> Here is a fixed version: First replace AltSnap.exe and hooks.dll with the appropriate versions below (32bit or 64bit builds) [AltSnap1.53_test19_i386.zip](https://github.com/RamonUnch/AltSnap/files/8609467/AltSnap1.53_test19_i386.zip) [AltSnap1.53_test19_x64.zip](https://github.com/RamonUnch/AltSnap/files/8609468/AltSnap1.53_test19_x64.zip)
> 
> Then add the Bottommost list in the in the `[Blacklist]` section:
> 
> ```
> Bottommost=*|RainmeterMeterWindow
> ; List of windows that should be kept below other Windows that are lowered
> ; by AltSnap. Default is *|RainmeterMeterWindow for Rainmaker skin windows.
> ```
> 
> It does not work at 100%, sometime some windows will no longer want to lower, but it mostly work for now. You can of course add more windows if you want them to stay bottommost. Of course if you take a rainmaker skin windows and move it above other windows then you will have trouble lowering windows that are above.

it works . thank you
