### ISSUE TITLE
draw window content while moving/resizing

### ISSUE THREAD

**Issue by marcosdon** [RamonUnch/AltSnap#192]
I wonder if it's possible to add a feature to draw the window content while moving/resizing, in addition to the rectangular preview of the new position/size.

**Comment by RamonUnch** [comment]
By default AltSnap follows the system setting, that was active when it was launched.
You can Force the windows content shown while dragging in AltSnap using the `FullWin` option in the .ini file:

Edit the .ini file by middle-clicking on the Tray Icon.
```
In the [Performance] section

FullWin=2
; Set to 1 to force the Drag Full Windows option (old default)
; Set to 0 to force off
; Default is 2: autodetect based on Windows setting
```
So you want To set `FullWin=1` in your case

After modifying the .ini file, you need to disable then enable AltSnap.

**Comment by RamonUnch** [comment]
Wait sorry I now think you mean Both at the same time...
It seems a good Idea, I will see on how to implement it nicely.
