### ISSUE TITLE
Feature: Center resize mode: Up, Down, Left, and Right extended

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltSnap#193]
I'd like to see an additional option for the center resize mode, something like this:

![Untitled](https://user-images.githubusercontent.com/25013746/171622835-4a92769a-9ac3-4f7b-b57d-fef99b653777.jpg)

This would be for those users that aren't interested in the options to resize in all directions, or resize the corners from anywhere but the corners. The main advantage is that to resize up, down, left, or right doesn't require you to be _outside_ of the center resize area which can result in relatively large distances to cover just to adjust the axes independently. This way the mouse can adjust each direction independently and with less mouse movement as well as with less errors of activating some different behavior via the center resize area because there effectively isn't one.

Thanks.

**Comment by RamonUnch** [comment]
Looks like a good idea to me, I will see on how to implement this nicely.

**Comment by RamonUnch** [comment]
It was quite straightforward, here it is.

[AltSnap1.53_test21-installers.zip](https://github.com/RamonUnch/AltSnap/files/8826496/AltSnap1.53_test21-installers.zip)
[AltSnap1.53bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/8826497/AltSnap1.53bin_x64.zip)
[AltSnap1.53bin.zip](https://github.com/RamonUnch/AltSnap/files/8826498/AltSnap1.53bin.zip)

tell me if you got problems, also the test window was updated.

**Comment by RamonUnch** [comment]
PS it is the closest side mode, or `ResizeCenter=3` in the .ini file

**Comment by redactedscribe** [comment]
I like it, works great.

The only thing I'd suggest is making the test window graphic clearer to communicate what's going on. Or perhaps just rely on documentation? However, if you wanted to do this, I'd propose:

- Make the square center resize area have a dashed line instead of solid one.
- Make the graphic dynamic based on chosen mode:
  - All directions: Show an 8-pointed star with arrow heads on each line within in the center square (i.e. a + combined with an x).
  - Bottom right: An arrow pointing to the bottom right within the center square.
  - Closest side: The same as is now, but with the square being a dashed line.

Maybe it's a problem if the user changes the mode via the parent AltSnap popup window and the test window is still open. Will the graphic redraw? Maybe just make the graphic static and combine the suggestions above into a single graphic?

**Comment by RamonUnch** [comment]
I agree, more will go in improving the test window. I will keep your suggestions in my TODO list.
Nothing is difficult it is just takes time to make it nice and perfect.
It is also perfectly possible to refresh the windows when settings changes, no black magic involved just some time to refine.
For now the test window is still a bit of an advanced user setting and not a high priority on my list.

**Comment by RamonUnch** [comment]
Feature is present in the latest 1.53 release.
