### ISSUE TITLE
Bug: Minimum window alpha transparency ignored

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltSnap#194]
These are my settings:

```ini
[Input]
Scroll=Transparency

[Advanced]
MinAlpha=32
AlphaDelta=64
AlphaDeltaShift=1
```

This used to work in v1.47 (just upgraded to the latest v1.52). Now when reducing the transparency, the window reaches 100% transparency, i.e. it cannot be seen any longer despite having a minimum of `32` set.

Thanks.

**Comment by RamonUnch** [comment]
Just replace AltSnap.exe+hooks.dll or use the installer to update.

**Comment by redactedscribe** [comment]
Tested as working, thanks.

**Comment by RamonUnch** [comment]
Use This one instead, Also the AeroSpeedTau was buggy in 1.52 for the same reason.
[AltSnap1.53bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/8824858/AltSnap1.53bin_x64.zip)
[AltSnap1.53bin.zip](https://github.com/RamonUnch/AltSnap/files/8824860/AltSnap1.53bin.zip)
[AltSnap1.53-test20-installers.zip](https://github.com/RamonUnch/AltSnap/files/8824861/AltSnap1.53-test20-installers.zip)

**Comment by redactedscribe** [comment]
> Use This one instead, Also the AeroSpeedTau was buggy in 1.52 for the same reason.

Seems fine.

As a suggestion, I'd say to increase the default value for the minimum transparency, for example to at least `24` (preferably `32`) which from my experience still produces useable results to be able to inspect behind both a light or dark colored window with it still being obvious enough that there is a transparent window in front. `8` is too transparent as the default as transparency could be activated unintentionally and then prove difficult to notice the foreground window on anything but a blank desktop. If a user wants more transparency, they can edit the INI.

**Comment by RamonUnch** [comment]
Indeed the default can be set to 32 it will be better for most users.
