### ISSUE TITLE
Add the SnapGap option to the GUI

### ISSUE THREAD

**Issue by apotenza92** [RamonUnch/AltSnap#200]
Add option to specify a pixel gap between windows or screen border so when windows are snapped there can be a gap between them or the screen edge.

**Comment by Ichisich** [comment]
`SnapGap` in the AltSnap.ini does exactly that.

**Comment by apotenza92** [comment]
You're right, that's great. I didn't know that existed. In that case, my request is simply for the snap gap to be added to the GUI configuration.

**Comment by RamonUnch** [comment]
> You're right, that's great. I didn't know that existed. In that case, my request is simply for the snap gap to be added to the GUI configuration.

This setting Is I guess intuitive enough to be displayed in the GUI without annoying anyone. So I will add it at some point.

**Comment by elnoelsi** [comment]
i made the opened the same issue some time ago, although there is not necessarily a need for it to be in GUI, could avoid things like this...

**Comment by RamonUnch** [comment]
This AltSnap build adds the SnapGap option to the GUI in the Metric section of the Advanced tab.
You can put a positive or negative value in pixels.

[AltSnap1.55test16_i386.zip](https://github.com/RamonUnch/AltSnap/files/9277456/AltSnap1.55test16_i386.zip)
[AltSnap1.55test16_x64.zip](https://github.com/RamonUnch/AltSnap/files/9277457/AltSnap1.55test16_x64.zip)
