### ISSUE TITLE
Mention installing via scoop in documentation/wiki

### ISSUE THREAD

**Issue by paulharris** [RamonUnch/AltSnap#203]
https://scoop.sh/#/apps?q=altsnap&s=0&d=1&o=true

scoop bucket add extras
scoop install extras/altsnap

AND a massive thanks to you and Stefan for building and maintaining this wonderful piece of software!

**Comment by RamonUnch** [comment]
Very nice, thanks a lot.
Wiki was updated.
Are you the maintainer of the package?
Should I mention you in the wiki page?

**Comment by paulharris** [comment]
No I'm not the maintainer, I'm just a humble user that also discovered scoop today (smoother than choco),
and was a bit sad that it was only on choco (according to your docs).
I searched on scoop just to see if it was there, and it was :)  So I thought updating the docs here would also be good.

There is a contributor mentioned here:
https://github.com/ScoopInstaller/Extras/blob/master/bucket/altsnap.json

But it might be like conan, where there is no dedicated maintainers, just a lot of people pushing PRs to update their packages to the latest versions.
