### ISSUE TITLE
Suggestion: Next and Previous track on Mouse thumb buttons

### ISSUE THREAD

**Issue by hammarhaus** [RamonUnch/AltSnap#205]
Thank you for all you do.

Best regards,
Kenneth

**Comment by Ichisich** [comment]
I would just implement:
`VK_MEDIA_NEXT_TRACK` `B0`
`VK_MEDIA_NEXT_TRACK` `B1`

So the media keys could also be bound to the mouse wheel or other buttons.

And perhaps additionally:
`VK_MEDIA_STOP` `B2`
`VK_MEDIA_PLAY_PAUSE` `B3`

**Comment by RamonUnch** [comment]
You can look at #492 to make an action that sends arbitrary key sequence.
