### ISSUE TITLE
Firefox Picture in Picture

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#206]
Firefox's picture in picture (pip) can generate an external window for videos on almost every website.
The generated window is categorized completely as title bar (WM_NCHITTEST=2)

Since title bar actions are implemented and can create such mismatches, an additional black list would be advisable.

**Comment by Ichisich** [comment]
I tested `MMBLower=Bild-im-Bild|MozillaDialogClass` and it worked.

The `MMBLower` Blacklist is already what I asked for. 
I would perhaps add Firefox's pip as a default entry in the next release.

**Comment by RamonUnch** [comment]
So now titlebar the blacklist will be:
``` 
MMBLower=*|CASCADIA_HOSTING_WINDOW_CLASS,*|SDL_app,*|MozillaDialogClass
```

**Comment by Ichisich** [comment]
Unfortunate, that there is no language agnostic solution.
I will use `*|MozillaDialogClass` for some days and report if something becomes iffy.

**Comment by RamonUnch** [comment]
From my experience it seems good.

**Comment by Ichisich** [comment]
Can confirm, the only other collateral damage besides Firefox's about box is Thunderbird's about box.
Both are obscure and not really essential in daily use.
