### ISSUE TITLE
Multiple Modifier Keys

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#207]
Currently, only left Ctrl disables AltSnap while pressed.

In case this isn't a deliberate design choice, having this function on right Ctrl as well would be really appreciated.

**Comment by RamonUnch** [comment]
I am not sure I understand.
You can Disable Hotkey+Click by hitting Ctrl while keeping the Hotkey down before the click.
In this case both Left and right ctrl should do the trick (it does when I test it).
Maybe you are taking about another fature.

**Comment by Ichisich** [comment]
It seems it's a bug caused by the modifier key and not, as I thought, a feature inert to left ctrl.
I changed the modifier key and now said key can disable AltSnap temporary as long as it is pressed.

So the solution to my plea would be the ability to set multiple modifier keys.

**Comment by Ichisich** [comment]
OK, I renamed the issue more appropriately.
So the win keys are the outliers, with only separate `5B` and `5C` available.

By the way, what I mean with disabled AltSnap:
https://user-images.githubusercontent.com/31080003/176104177-bf627611-efad-4723-9a33-6ce55d3366fa.mp4

I figure it is more an override of action `without hotkey` into the title bar `alternate actions`, which are normally set to `nothing`. This would explain why any given modifier key would work. 
Taking the video as an example, setting `LMBTB=Move` results in no different behaviour while left Ctrl is pressed.

On a different note, the shift key does something similar to `Smart Aero Snapping`.
While Shift is pressed, only geometrically snapping occurs (exact half or quarter tiling).
Is this by accident or design? Regardless, it often comes in handy.

**Comment by Ichisich** [comment]
I was aware of the space-toggle, but the shift-hold came by accident through zone usage. Have to say, it is quite the elegant approach of doing tiling.
You can on the fly tile in three different ways (smart, zone, geometrical).

Even specialized Linux tiling desktop environments don't come close, at least regarding mouse tiling.

**Comment by Tabiskabis** [comment]
So currently only one key can be the trigger for AltSnap, and another key can override it?  
I would prefer to have a two key combo as the trigger instead (ctrl-alt-click). That would correspond to Mac (hidden feature).

**Comment by Ichisich** [comment]
Not sure that I get you correctly, but your preference sound like this already implemented option:

![two](https://user-images.githubusercontent.com/31080003/177883922-f37d3735-41e0-4b4b-8995-0ccdf64ff279.png)

**Comment by RamonUnch** [comment]
Indeed I have implemented key combo with MAC users in mid.

**Comment by RamonUnch** [comment]
This AltSnap version supports a key list for the `ModKey`.
By default a small list of options is available but If you want to make a custom key-list, it is possible via the .ini file.
The `ModKey=11 ` trick will still work like before, but if you use an *action without click** you will need to use `ModKey=A2 A3`, because the `11` code only works in the `GetAsyncKeyState()` function.

[AltSnap_x64.zip](https://github.com/RamonUnch/AltSnap/files/9103513/AltSnap_x64.zip)
[AltSnap_i386.zip](https://github.com/RamonUnch/AltSnap/files/9103515/AltSnap_i386.zip)
