### ISSUE TITLE
Wiki entry for autostart links to wrong image

### ISSUE THREAD

**Issue by Earlopain** [RamonUnch/AltSnap#212]
https://github.com/RamonUnch/AltSnap/wiki

The last image in the autostart instructions is a repeat of the one before. The link is https://github.com/RamonUnch/AltSnap/raw/main/HelpImages/taskmgr3.png, but it should be https://github.com/RamonUnch/AltSnap/raw/main/HelpImages/taskmgr4.png. I tried to somehow edit this myself with a pr or something, but I don't think Github supports that.

**Comment by RamonUnch** [comment]
Indeed, thanks for your report!
Fixed.
