### ISSUE TITLE
bug: "mimic aero snap" is necessary for "Snap to Layout with Shift" to work correctly. 

### ISSUE THREAD

**Issue by onguarde** [RamonUnch/AltSnap#220]
When "mimic aero snap" is disabled, "Snap to Layout with Shift", will not snap to the layout set properly. It will snap to position, but the window will not be resized properly to match the exact shape of the layout.

https://user-images.githubusercontent.com/681355/180171416-c9b36095-482b-4602-b89c-bc581974e3e6.mp4

https://user-images.githubusercontent.com/681355/180171424-e299f28d-d84a-47aa-8d06-385d075787a3.mp4

I wish to disable "mimic aero snap" without breaking "Snap to Layout with Shift".

> mimic aero snap docs,
> If you do not want windows to automatically snap to fill a fraction of the monitor when you drag it towards the edges, then disable the Mimic Aero Snap option. The threshold from the monitor edge at which snapping occurs can be changed in the Advanced tab.

**Comment by RamonUnch** [comment]
Indeed this is a huge bug, I will investigate.

**Comment by RamonUnch** [comment]
This build should fix it.
[AltSnap1.54test8_i386.zip](https://github.com/RamonUnch/AltSnap/files/9158459/AltSnap1.54test8_i386.zip)
[AltSnap1.54test8_x64.zip](https://github.com/RamonUnch/AltSnap/files/9158464/AltSnap1.54test8_x64.zip)

**Comment by onguarde** [comment]
great, thanks so much for the fix.
