### ISSUE TITLE
when FullWin=0, difficult to see pink border in greyscale mode 

### ISSUE THREAD

**Issue by onguarde** [RamonUnch/AltSnap#223]
It's difficult to see the pink border. In the video below, I enabled greyscale mode for windows, and it's very very difficult to see the border. 

https://user-images.githubusercontent.com/681355/180358047-e8948e05-568a-4e7c-a205-55c964ddd573.mp4

It'll be nice to have a blue highlight, similar to the Microsoft's implementation.

**Comment by Ichisich** [comment]
You can change the colour with `FrameColor` in the AltSnapt.ini input section.
`FrameColor=00 66 CC` would be your typical windows navy blue.

**Comment by RamonUnch** [comment]
Indeed the FrameColor let you set the color in RR GG BB format.
FF 00 00 => Bright red
00 FF 00 => Bright green
00 00 FF => Bright Blue

The default purple/pink color is quite visible when Windows si setup in bright mode.
Tell me also if you think borders should be thicker. I could add an option for this.

**Comment by onguarde** [comment]
Yes pink is very visible. But when greyscale mode is enabled, everything is black and white. I'm on greyscale mode most of the time, helps me to focus better.

> Tell me also if you think borders should be thicker. I could add an option for this.

This would be great. But if you colour the whole rectangle with a light blue box, 50% opacity, like the fancyzone implementation, that would be perfect.

**Comment by RamonUnch** [comment]
>This would be great. But if you colour the whole rectangle with a light blue box, 50% opacity, like the fancyzone implementation, that would be perfect.

Makes sense indeed.

**Comment by onguarde** [comment]
I've tested 1.54, this works perfectly. Really like the visual experience, exactly similar to Microsoft's Powertoys implementation.



Following are my settings for future reference,

> ;FullWin=2; orig
> FullWin=0
> ; Set to 1 to force the Drag Full Windows option (old default)
> ; Set to 0 to force off
> ; Default is 2: autodetect based on Windows setting
> 
> TransWinOpacity=128
> ; New in 1.54
> ; Set opacity from 1-255 of the transparent window used when FullWin=0
> ; default is 0 which mean no transparency is used (best performances).
> ; also 255 has good performances but there is zero opacity.
> ; If you are using desktop composition or Windows 8+ then there will be
> ; no significant performance impact to any value.
> 
> RezTimer=1
> ;RezTimer=0 ; orig
> ; Set to 1 to move the window only when the timestamp of
> ; a mouse event is different from the previous one, every 16ms
> ; more or less. MoveRate and ResizeRate and RefreshRate
> ; will have no effect if the option is enabled.
> ; This is overall the option that gives the best performances.
> ; It can be combined with FullWin=0 mode for ~0% CPU usage.
>

**Comment by onguarde** [comment]
I noticed that this feature is also affected by the new AeroMaxSpeed settings. AeroMaxSpeed is meant to delay the snapping of windows. However, the blue rectangles should be drawn immediately as a real-time feedback. So, typically we wouldn't want any delay when FullWin=0. 

Just putting a note here, so remember to disable this when using FullWin=0. I don't think this has to be enforced in code, because some may actually prefer to configure this.

> ;AeroMaxSpeed=16
> ;AeroSpeedTau=32
> ; New option AeroMaxSpeed and AeroSpeedTau in AltSnap1.54test12_x64.zip version
> ;Window will be not moved if the cursor speed is higher than the Max snapping (see Advanced tab).
> ;I suggest you start with a Max Snapping Speed of 64pixels/64ms, then try increasing or decreasing depending on your taste.
> ;If the cursor goes faster than the max snapping speed, then the windows will not be moved until the cursor slows down. like this you can move quickly your cursor over a zone without having the window snap to it.
> ; Note: make sure this is disabled when you FullWin=0

**Comment by RamonUnch** [comment]
>     ;AeroMaxSpeed=16
>    ;AeroSpeedTau=32
 >   ; New option AeroMaxSpeed and AeroSpeedTau in AltSnap1.54test12_x64.zip version
 >   ;Window will be not moved if the cursor speed is higher than the Max snapping (see Advanced tab).
 >   ;I suggest you start with a Max Snapping Speed of 64pixels/64ms, then try increasing or decreasing depending on your taste.
    ;If the cursor goes faster than the max snapping speed, then the windows will not be moved until the cursor slows down. like this you can move quickly your cursor over a zone without having the window snap to it.
    ; Note: make sure this is disabled when you FullWin=0

AeroMaxSpeed ans AeroSpeedTau are not new to 1.54 but it just did not apply to Zones snapping before, it was a bug.
The Tau corresponds to the delay in miliseconds used for speed calculation, so you need at least 32 to 100 ms to have an accurate calculation.
The AeroSpeedTau cannot be modified by the GUI because the default should be good for everyone.
The old default was 32ms but I found that 64ms is a bit better (not by much)
