### ISSUE TITLE
[Snap to layout] enhancement: Show list of all windows in a snapped layout position

### ISSUE THREAD

**Issue by onguarde** [RamonUnch/AltSnap#231]
While using "Snap to Layout / Fancyzones", I find myself repeatedly asking, "What are all the windows within that snap position?"

Say we have 5 windows in a snap position, it becomes difficult to switch between them. Currently I use the "lower" function, to cycle between them, which works well enough. (Note: this skips minimised windows)

![image](https://user-images.githubusercontent.com/681355/180643524-01feb54e-8fa4-4c45-9b5e-213f6a30892f.png)

However, it'll be awesome if we can have a list of all the windows within that snap position,

![image](https://user-images.githubusercontent.com/681355/180643529-630b4382-6cc7-470a-ab6f-3ca50a7dcb5c.png)

This will scale much better, even with 10 windows, we don't have to hunt and peck in the windows taskbar. 

It's quite natural to use a visual layout to group windows, we are visually spatially oriented after all. That way, It's easier to remember where things are. We just need a way to scale this with many windows. 

Looking at the big picture...

We will still need another complementary function to list all "minimised windows". We can't get this list from the taskbar as it shows all the windows. It's annoying to have to hunt and peck in the taskbar.

I'm super excited because with these 2 functions, we can easily manage 20+ windows easily by splitting them into snap positions. While hiding the ones we don't need temporarily in the "minimised windows" list. 

Instead of having one giant list of all windows in the taskbar, we now have lists of windows in each snap position, and a minimised windows list. That is definitely easier to manage. 

Classic "divide and conquer", combined with spatial layout visualisation, which is easier to remember. 

Appreciate your thoughts.

**Comment by RamonUnch** [comment]
Interesting,

I would suggest however that you try a program named Tidy Tabs:
https://www.nurgo-software.com/products/tidytabs

It is not exactly the same thing but it might help you in the meantime.

**Comment by onguarde** [comment]
Interesting, 

![image](https://user-images.githubusercontent.com/681355/180675592-3d93363f-2c42-4043-b8d0-8f5c0ec6aef4.png)

I tried it. It doesn't scale very well with many windows. Especially when the monitor is divided into smaller zones, and the width of a window is small.

![image](https://user-images.githubusercontent.com/681355/180675659-f784242a-214c-4c7e-b500-261543fdd26b.png)

It'll be great if there's a way to support vertical tabs, expandable via a hotkey or mouse hover. 


Other Cons,

- minimise window now minimises the whole grouped window. But we lose the ability to hide certain windows from the list. 

- harder to drag the current tab into the existing group. Relative to Altsnap style drag it into position. 

- bug: when window is maximised, need to restore it first, before adding to a group. 


But looks promising, I may continue to play with it.

**Comment by onguarde** [comment]
i've tried [Groupy ](https://www.stardock.com/products/groupy/) and i believe it works better than Tidytabs. It's perfect but unfortunately, it doesn't work at all with virtuawin/dexpot or any virtual desktop software. The grouped tabs will be undone on desktop switch. 

![image](https://user-images.githubusercontent.com/681355/180725315-76eb0451-cc59-478d-b507-7794214ae1a1.png)


it does play well together with built-in windows 10 virtual desktop though. That is usable but missing features like shortcuts and a quick way to visualise and move windows between desktops. My favourite way to do this is using "iconised" plugin of virtualwin,

![image](https://user-images.githubusercontent.com/681355/180725589-b56d62c9-1548-4f7c-bb3e-c7a6e849c665.png)

I thought we may be able to use autohotkey to,
1) Show a pop up list of windows under the mouse cursor.
2) Show a pop up list all minimised windows.

But a quick search, does not give anything readily available. (2) might be trivial. But (1) may not even be possible.

**Comment by RamonUnch** [comment]
[AltSnap1.55test22_i386.zip](https://github.com/RamonUnch/AltSnap/files/9292917/AltSnap1.55test22_i386.zip)
[AltSnap1.55test22_x64.zip](https://github.com/RamonUnch/AltSnap/files/9292919/AltSnap1.55test22_x64.zip)

Here is a test build with the new **Stacked windows list** action that can be selected for any mouse buttons.
It pops up a menu with the list of windows that are stacked at the current location.as you asked.

For now there is no icon added to the menu, but I plan doing it at some point.

**Comment by onguarde** [comment]
This is awesome it works perfectly. I set it ALT + mouse's Back button, to open the window list. And ALT + scrolling to switch to next/prev window in the zone. 

![image](https://user-images.githubusercontent.com/681355/184844044-8f7f64ff-1648-42c8-a39d-17f8f92f514b.png)


Some enhancements to consider, 

1) Good to have icons, aids easier identification. Failing which, a process name. Else, I find it's really hard to pick windows.

2) 123, is better than ABC. We can easily reach 123 using just the left hand positioned at the keyboard, while the right hand is on mouse.

![image](https://user-images.githubusercontent.com/681355/184833335-1453e192-6795-49d7-835e-411b98bc7fc4.png)

![image](https://user-images.githubusercontent.com/681355/184833406-65521691-c816-4c90-bbf3-ad1687804275.png)

3) Quickly close windows by middle clicking. 

4) This is a bonus, and might not be technically feasible,

On mouse hover, switch to the window temporarily. Similar to hovering on thumbnails in Windows taskbar, the window will be raised and background blurred to give a "sneak preview" of the window. A subsequent left click will raise the window, otherwise if the cursor is no longer hovering on the window list, the "sneak preview" is disabled. 

This will complete this function as a taskbar replacement.

**Comment by RamonUnch** [comment]
> 123 shortcut, is better than ABC. We can easily reach 123 using just the left hand positioned at the keyboard, while the right hand is on mouse.

I do not agree using many non-US you have a hard time pressing 1-9. A-Z is always feasible without pressing Shift. However I will make this optional, and this will apply to all menu.

I am using a native Windows menu so unless I re-invent the wheel I cannot implement those visual enhancements.
I plan doing this in the long run but it will take a while and a bunch of coding.

**Comment by RamonUnch** [comment]
I have never seen right aligned text in menu (for right-to left scripts of course).
This looks very strange, could you give a sole example of menu like this in English language?

**Comment by RamonUnch** [comment]
I am working on an owner-drawn menu, it is already starting to look half decent.

**Comment by RamonUnch** [comment]
[AltSnap1.55test32_i386.zip](https://github.com/RamonUnch/AltSnap/files/9365796/AltSnap1.55test32_i386.zip)
[AltSnap1.55test32_ix64.zip](https://github.com/RamonUnch/AltSnap/files/9365797/AltSnap1.55test32_ix64.zip)

Here you go @onguarde 

![StackedWindowList](https://user-images.githubusercontent.com/74856804/185234744-5ad3b4be-e0c8-4955-8356-eb4110e4d522.png)

If you want numbers in items, use 
```
In the [Advanced] section
NumberMenuItems=1
; Use numbers instead of a-z for shortcuts in windows list menu.
```

**Comment by onguarde** [comment]
![image](https://user-images.githubusercontent.com/681355/185288503-fc27d284-55fd-448e-9218-6957fb868bca.png)

This looks perfect with the icons. I figured the number should start from 1 instead of 0, but actually 0 makes more sense because you won't want to switch to the current window (0).

I'm not longer seeing the right align text issue, it is all left aligned now in this version.

**Comment by RamonUnch** [comment]
If anyone has a screen reader I would love to know if it can actually read the menu.
Drawing myself the menu makes it more complicated for accessibility tools.

**Comment by Ichisich** [comment]
[Microsft Narrator ](https://en.wikipedia.org/wiki/Narrator_(Windows)) does recognize it:
![sprachausgabe](https://user-images.githubusercontent.com/31080003/185353420-c7c22219-dac2-42ed-93ec-b3111137cafe.png)

**Comment by onguarde** [comment]
I've been using this on a daily basis, awesome. Couple of enhancements, 

### Show Stacked Window List 2 (Laser focus mode)

![image](https://user-images.githubusercontent.com/681355/186304501-e6182fd1-af9f-4c8d-9436-935905f29628.png)

There should be a "Stacked Window List 2" above, which will list windows using the "laser pointer" method. Currently, it only shows stacked windows snapped to the zone. 

This is to be consistent with, 

![image](https://user-images.githubusercontent.com/681355/186304666-e50eb8d5-e4e7-44ea-9cb2-9774832839af.png)

In keyboard, we have a way to select between laser cursor or zone mode. 


### Configurable font size 
Another small issue is with the font size, which is a really small. Making it bigger or configurable would be great for high DPI monitors.

![image](https://user-images.githubusercontent.com/681355/186305507-e5dd11fe-e423-4372-98f7-e0f4d655df33.png)
