### ISSUE TITLE
(fancyzones) Shortcut to Go to Next/Previous Window

### ISSUE THREAD

**Issue by onguarde** [RamonUnch/AltSnap#234]
![image](https://user-images.githubusercontent.com/681355/180982586-f7576dbc-7624-4a5b-b2ee-edafb5c81264.png)

When the window is snapped using fancyzones, those keyboard shortcuts work. 
When the window is snapped using altSnap, those keyboard shortcuts don't work. 

Is there a way to make it work for interoperability? If not, is there a way to define similar shortcuts that work with both AltSnap and FancyZones.

This is what I came up with autohotkey, it pushes the current window under the mouse cursor all the way to the back of all windows. So we can see the next window. 

> 
> ; Lower window
> ;	replaces fancyzones (shortcuts) - not working if altSnap is used to snap windows
> ;	replaces altSnap - Lower window function - doesn't work well
> +RButton::
> 	; get mouse position relative to the active window and get the 
> 	; window ID under the cursor (not necessarily active!) 
> 	MouseGetPos, TB_X, TB_Y, TB_ID
> 	
> 	WinSet, Bottom,, ahk_id %TB_ID%
> return
> 

Works pretty well. But I can't find a way to get back that last window that was pushed back. That should act as reverse shortcut.

**Comment by RamonUnch** [comment]
I Guess it would not be too difficult to implement.
I can detect based on the dimensions that a stack of windows are on a specific zone, then I can Alt+Tab only through them.

Should the current zone be determined on using the currently focused window or the pointed zone?
This should also be available through a wheel action and in this later case the pointed zone should be considered.

So in the end If I add those shortcuts, you will have to disable them on FancyZones to avoid interaction and it will have to handle both FancyZones and AltSnapped windows.
There will also be a wheel action to do the same task.
And finally ideally there should be an optional visual indicator of the window list that pops up when switching between stacked windows. And one should also be able to click an item of the list to select the desired window, like asked in #231. Finally an additional action should be also added just to popup this stacked windows list.

This is a lot to do, I will see when I get more time.

**Comment by onguarde** [comment]
Wow that sounds like a good plan.

> Should the current zone be determined on using the currently focused window or the pointed zone?
I prefer the pointed zone, as you won't have to activate the window first. One less step. 
I have other shortcuts that work on the window under the cursor eg. minimise(alt+Rbutton), close(alt+Mbutton). Works really well to quickly close windows, almost like a FPS game. In the spirit of AltSnap, I strongly prefer pointing based shortcuts, instead of having to actively focus a window, before any manipulation.

Should it work based on "pointed zone" or "any window under the cursor"? I was originally thinking of the latter, like a laser shooting through all the windows beneath. This would allow it to work on normal windows outside of zones, even without zone snapping. Say on a large monitor, where windows are not snapped but overlapping. But this may complicate implementation, prolly need to think through deeper. 

Edge case: What should happen when window is stretched across 2 zones? The window should appear on BOTH zones' window list. And the alt+tab on the zone should still work.

**Comment by RamonUnch** [comment]
For now only windows that are stacked with the same size are considered with the action.

[AltSnap1.55test19_x64.zip](https://github.com/RamonUnch/AltSnap/files/9282718/AltSnap1.55test19_x64.zip)
[AltSnap1.55test19_i386.zip](https://github.com/RamonUnch/AltSnap/files/9282719/AltSnap1.55test19_i386.zip)

You have two new actions (next and previous stacked window) plus a wheel action (next/prev stacked window).
And you also have a checkbox in the Keyboard tab to enable Alt+PageUp/PageDown to go to next/previous stacked window.

It is still WIP and there is not yet any drop menu with a window list.

**Comment by RamonUnch** [comment]
> I was originally thinking of the latter, like a laser shooting through all the windows beneath. This would allow it to work on normal windows outside of zones, even without zone snapping. Say on a large monitor, where windows are not snapped but overlapping. But this may complicate implementation, prolly need to think through deeper.

Actually it is a very good idea. I think it would fill all requirements If using some kind of zones then it would only cycle through zones and in free mode it would still be useful.
It would be the simplest option too, as the inclusion list is trivial.

**Comment by RamonUnch** [comment]
This hooks.dll improves the behavior again.
Now by default when Doing Alt+PageUp/Down it will include all stacked in a more generous way (one is inside the other) and only switch if the cursor points to the window. If you press Shift (Alt+Shift+PageUp/Down) then the pure laser pointer technique you were taking about will be used.

This hooks.dll is to be used alongsie altsnap.exe test19 above
[hooks1.55test20_i386.zip](https://github.com/RamonUnch/AltSnap/files/9283601/hooks1.55test20_i386.zip)
[hooks1.55test20_x64.zip](https://github.com/RamonUnch/AltSnap/files/9283609/hooks1.55test20_x64.zip)

**Comment by Ichisich** [comment]
Are you planning to hardcode Alt+PgUp/PgDw, because currently it's Hotkey+PgUp/Dw?

hook20 doesn't work with full-screen applications any more.
Besides that, it works intuitively, both on the wheel and a button.

**Comment by RamonUnch** [comment]
> Are you planning to hardcode Alt+PgUp/PgDw, because currently it's Hotkey+PgUp/Dw?

For now it is hardcoded to this indeed, like the other shortcuts.
It is in my todo list to have the option to customize all those keyboard shortcuts. Not sure if it will be for the next release, probably not. 
When I say Alt in this case it just means the hotkey actually, it is the same mistake with the others shortcuts.

I do not know if there are important defaults shortcuts for Alt or Win + PageUp/Dw on Windows, but not that I am used to at least.

**Comment by RamonUnch** [comment]
> hook20 doesn't work with full-screen applications any more.

In which way? I can still move full-screen windows when the advanced option is checked.

**Comment by Ichisich** [comment]
> I do not know if there are important defaults shortcuts for Alt or Win + PageUp/Dw on Windows, but not that I am used to at least.

Not that I'm aware of, at least on Windows it seems only Ctrl/Shift+PgUp/Dw are in common use.

> In which way? I can still move full-screen windows when the advanced option is checked.

Only concerning the new stacking feature.

**Comment by RamonUnch** [comment]
Ok, this is normal then and it should be improvable.

I want to Alt+Tab between windows for which it makes sense and I have to exclude windows that have no captions. In the first version where only windows that had exactly the same size were considered stacked it did not induce problems to do otherwise. But otherwise the desktop window would be selected.

I should probably check for the full screen window option here too.

Could you send the detail of the said fullscreen window?

**Comment by Ichisich** [comment]
> Could you send the detail of the said fullscreen window?

I tested it with Firefox(F11), Explorer(F11) and vkquake2 (exclusive Fullscreen through the vulkan api).
hook19 works with all of them, even with vkquake2 which normally crashes when minimized or is kept present when alt+tabbed.
hook20 works with none of them.

**Comment by RamonUnch** [comment]
Actually I just had to check the absence of the `WS_EX_TOOLWINDOW` to know if the window has can be alttabbed.

[hooks1.55test21_x64.zip](https://github.com/RamonUnch/AltSnap/files/9289009/hooks1.55test21_x64.zip)
[hooks1.55test21_i386.zip](https://github.com/RamonUnch/AltSnap/files/9289010/hooks1.55test21_i386.zip)

**Comment by Ichisich** [comment]
Yep, now it acts more like alt+tab and ignores the desktop.
I kind of preferred the hook19 approach, but I might be in the minority.

**Comment by RamonUnch** [comment]
This might be an advanced option that would also affect the Alt+Tab wheel action as they are both almost the same.

**Comment by onguarde** [comment]
This is awesome. Works perfectly. I've tested the switching using the keyboard works fine too.

**Comment by onguarde** [comment]
In the latest version you shared from from another #231, the keyboard settings looks different. Cool that we can setup our own keyboard shortcuts for "Next/Previous Stacked Window" function.

![image](https://user-images.githubusercontent.com/681355/185289197-861226a4-50e1-4e83-9740-5ea57bc1a604.png)

FYI, this is my mapping. Hope it's useful for anyone else configuring the same setting.

Alt+scroll => "Next/Previous Stacked Window" 
Alt+backButton => "Stacked window list"
![image](https://user-images.githubusercontent.com/681355/185355778-e286ca97-6e94-4c8b-b5bb-dee7f3d4e938.png)

Win+Scroll => Next/Previous tabs in Browsers/Vscode/etc.
```
; in Autohotkey script,
; Next/Prev tab - For Chrome/Firefox & others
#WheelDown::send {Ctrl Down}{PgDn}{Ctrl Up}
#WheelUp::send {Ctrl Down}{PgUp}{Ctrl Up}
```

**Comment by onguarde** [comment]
1) "laser shooting through all the windows beneath"
2) only windows docked in zones will be shown

This window selection mode setting affects "Show stacked window list" and "Next/prev stacked window". 

In the interest of simplification, I was thinking if we should only have one method to detect windows. Currently we have 2 methods, and it adds to the complexity, which I would love to simplify. Even as a user, having to think that holding "shift" changes the behaviour of "show stacked window list", is rather disconcerting. 

It works perfectly fine everywhere, so perhaps this is a nitpick. But as more and more features get added, it's good to stop and try to simplify wherever possible. 

![image](https://user-images.githubusercontent.com/681355/185356254-d8741cdf-2722-4c6d-8341-72b407c9f608.png)

Pros/cons
1) "laser shooting through all the windows beneath"
+more generic and works when the another window is covering the zone, you don't have to click at position 2. 
![image](https://user-images.githubusercontent.com/681355/185358013-5ed0daff-90fe-4850-a5f1-718a848655dd.png)
+don't have to keep worrying that other windows that are not yet snapped to any zones, is hiding beneath all the other snapped windows in a zone. 

2) only windows docked in zones will be shown
+fancyzones only has (2), easier to understand.



In any case, one way to reduce the complexity is to **make this an advanced setting**. We get to choose (1) or (2) window selection mode, since the ability to choose between the 2 is not worth the extra mental load. One would usually prefer one or the other.

**Comment by RamonUnch** [comment]
I am generalizing the way the keyboard works by using the native windows function for mapping a keyboard shortcut.

I think that when there will be too many settings in the drop-list, I will start classifying them in separated drop-lists.
Also the Next/previous stacked window 2 could be better named, but it means the laser mode.

When you setup a keyboard shortcut without and then press shift then the shortcut is considered different . For this reason I need to duplicate the laser mode and the stacked mode.

I guess most people will choose their preferred way and not mix them.

The non laser mode does not actually looks for snapped state, it works for any windows that are stacked, when one is inside the other or has the same size.
