### ISSUE TITLE
Inconsistent focusing of windows on Windows 11

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#235]
> > Also, windows don't get focused by single left clicking when the left mouse button is set to move in the titlebar actions.
> 
> Can't replicate. Is this checked: ![Unbenannt](https://user-images.githubusercontent.com/31080003/181005365-8c95775f-165d-4fde-9325-7e4c7d3ed9b1.png)

I'm referring to a single click action on the titlebar rather than a drag action.
Like you would do to focus a window if altsnap is not active.

I just tried the setting you mentioned, but it doesn't seem to work very well for me.
It's not at all consistent in windows 11.

Also enabling this setting causes a certain window to go into a disco mode(for lack of a better word):

https://user-images.githubusercontent.com/47380919/181014126-3825b87d-4ed8-4c36-88ba-86b13228b7e0.mp4

_Originally posted by @rp1231 in https://github.com/RamonUnch/AltSnap/issues/229#issuecomment-1195466110_

**Comment by Ichisich** [comment]
Does only AnLink hit the dance floor?

**Comment by RamonUnch** [comment]
Windows does not let very easily programs to focus other windows outside of the real input.
AltSnap Uses the SetForegroundWindow() function and it is not guaranteed to work.

For the disco effect, I should just check that the window is not already focused.

**Comment by RamonUnch** [comment]
Well, the only reliable solution seems to be sending a key input.
Here is a build of AltSnap that uses a more solid focusing algorithm.

[AltSnap1.54test15_x64.zip](https://github.com/RamonUnch/AltSnap/files/9217627/AltSnap1.54test15_x64.zip)
[AltSnap1.54test15_i386.zip](https://github.com/RamonUnch/AltSnap/files/9217628/AltSnap1.54test15_i386.zip)

**Comment by RamonUnch** [comment]
Yes it should include previous fixes.

**Comment by RamonUnch** [comment]
It is not possible for the moment but you can set `UseCursor=2` in the `[Advanced]` section of the .ini file so that the cursor does not change to the hand for a move action.
