### ISSUE TITLE
Generalize handling  of caption buttons

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#236]
@Ichisich
Here is a way to incluse or excluse caption buttons in the titlebar action for each button.
```
In the [Advanced] section of the .ini file
BLCapButtons=3
; Bitmask of the buttons for which the caption buttons will not be
; considered like the titlebar. Default is 3 (LMB and RMB) you can
; specify any value in decimal converted from a it mask in the order
; of mouse buttons ie: LMB RMB MMB MB4 MB5.
; use BLCapButtons=0 if you always want titlebar actions to be applied
; when clicking caption buttons and use 31 if you never want this (11111 binary).
```
[hooks1.54test13_i386.zip](https://github.com/RamonUnch/AltSnap/files/9190114/hooks1.54test13_i386.zip)
[hooks1.54test13_x64.zip](https://github.com/RamonUnch/AltSnap/files/9190118/hooks1.54test13_x64.zip)

**Comment by Ichisich** [comment]
The text is a bit cryptic.
But `BLCapButtons=0` seems to do what I want.

**Comment by Ichisich** [comment]
Oh, now I get it, it is just simple binary or how to count to 31 with just one hand.
I wasn't familiar with the term bit mask.

One inconsistency I noticed is that buttons which are enabled to perform title bar actions in the button-box also ignore the upper window edge `WM_NCHTTEST=12`

This can lead to undesirable outcomes as closing the browser instead of creating a new tab etc.

**Comment by RamonUnch** [comment]
You mean that when `BLCapButtons=0` you would still prefer the top resizing borer to be excluded from the titlebar?
Actually the normal caption is *strictly* the caption and the extended caption adds the sysmenu, caption buttons and the top resizing border, like with the original AltDrag (which only had Lower with middle click action).

Maybe I should still exclude for the two primary buttons the ability to perform an action in this area (`WM_NCHTTEST=12`).

**Comment by Ichisich** [comment]
It has its advantages and disadvantages.
I just thought it was an oversight because prior to test14 the behaviour was different.
Personally, I think including `WM_NCHTTEST=12` in the title bar is more useful than harmful, but could have negative consequences for user that are unaware.

Considering that default `BLCapButtons=3` already excludes the left mouse button, which is the only one with a native function on `WM_NCHTTEST=12`, I wouldn't change the current approach.

My attempt to make the .ini text less confusing for non programmers:

```
BLCapButtons=00011
; bitmask of the buttons for which the caption buttons and upper window edge will not considered as title bar 
; default is 00011 (LMB and RMB)
; specify any value in decimal converted from a bitmask in the order of mouse buttons: 
; LMB=xxxx1 
; RMB=xxx1x 
; MMB=xx1xx 
; MB4=x1xxx 
; MB5=1xxxx
; use BLCapButtons=00000 if you always want titlebar actions to be applied when clicking caption buttons
; use BLCapButtons=11111 if you never want titlebar actions to be applied when clicking caption buttons
```

**Comment by RamonUnch** [comment]
Well I am not really willing to make an ASCII bit mask reading code just for simpler .ini edition. I guess people can convert mentally or using calc.exe if they are unsure. Plus outside of 0, 1, 3 and 31 there are not really  any values that makes much sense for most users. I already use the convention to Add a power of two for some settings that are closely related, like the `SmartAero` settings, so using a specific convention for this one would be strange as  settings that are single numbers are read in the same loop.

I think we could include your comment telling people to convert the value to decimal and start with the list of the most useful values (0: All buttons, 1 exclude LMB, 3 exclude LMB+RMB and 31 excludes all buttons, then for a custom value start from zero and add add 1, 2, 4, 8, 16 to exclude respectively LMB, RMB MMB, MB4 and MB5.

**Comment by Ichisich** [comment]
My approach is that you neither have to convert nor understand binary.
Just make a 1 where you want and that's it.

For example:
I only want MMB to respect the upper window edge as is:
so I use `BLCapButtons=00100`, no need to convert to `BLCapButtons=4`

**Comment by Ichisich** [comment]
Somewhat related:
Could you also add the scroll wheel to `BLCapButtons`?

**Comment by RamonUnch** [comment]
Indeed there are no reasons to limit it to the five first mouse buttons.

In test 15 you can go from button 1 to 22  (buttons 1 to 20 + the two latest values are the vertical and the horizontal wheel, so if you want to exclude one of them, just add 1048576 for the vertical Wheel or 2097152 for the Horizontal Wheel: 

Use 0 or -1 to enable or disable all mouse buttons+wheel in the extended caption area.

[AltSnap1.54test15_x64.zip](https://github.com/RamonUnch/AltSnap/files/9217627/AltSnap1.54test15_x64.zip)
[AltSnap1.54test15_i386.zip](https://github.com/RamonUnch/AltSnap/files/9217628/AltSnap1.54test15_i386.zip)

**Comment by Ichisich** [comment]
Doesn't work.

`BLCapButtons=-1` disables all but the scroll wheel.
`BLCapButtons=1048576` and `BLCapButtons=100000000000000000000` don't disable the wheel either.

**Comment by RamonUnch** [comment]
I put the wrong version, sorry, this one should do it.
[AltSnap154test16_x64.zip](https://github.com/RamonUnch/AltSnap/files/9226641/AltSnap154test16_x64.zip)

**Comment by Ichisich** [comment]
Perfect, thanks.
