### ISSUE TITLE
[Feature request] Add resize option to scroll wheel and title bar scroll action

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltSnap#239]
This was one of the first things that I  tried to add it wasn't in the options.
Seems like a very intuitive feature.

**Comment by xan2622** [comment]
If you meant : 
- scrolling up to resize the window vertically (increasing its height)
- scrolling down to resize the window horizontally (increasing its width)
... then I like this idea. 👍

There might also be an option to set how many pixels (or % of the size) each _mouse wheel notch_ should increase.

**Comment by RamonUnch** [comment]
Here is a quick test version.
The idea is that the zooming mode depends on which of the 9 quadrant you are in.
The corresponding quadrant does not move when you zoom in/out, the center mode zooms in all directions and by default the windows increase/decrease 5% in width and 1% with shift.

It is still work in progress.

[AltSnap1.55test5_x64.zip](https://github.com/RamonUnch/AltSnap/files/9261156/AltSnap1.55test5_x64.zip)
[AltSnap1.55test5_i386.zip](https://github.com/RamonUnch/AltSnap/files/9261157/AltSnap1.55test5_i386.zip)

**Comment by xan2622** [comment]
I have just tried this "AltSnap1.55test5_x64.zip" version and wow.. this is impressive!
I haven't noticed any bug.

**Comment by Ichisich** [comment]
One suggestion.

Let the window border recognize the screen edge, or, preferably, behave accordingly to the `Snap window edges to:` setting.

**Comment by RamonUnch** [comment]
> Let the window border recognize the screen edge, or, preferably, behave accordingly to the Snap window edges to: setting.

For sure it is coming...
However it will be like with resizing, the "center" mode does not snap.

**Comment by RamonUnch** [comment]
> Would it be possible to add both horizontal and vertical resizing for the center titlebar fraction?

How would that be done?

> Ok I just noticed that the titlebar zoom window action also uses the window fractions.

Usually the Titlebar action is exactly the same than the normal one.

**Comment by RamonUnch** [comment]
Here is an improved version.
* Snapping is supported.
* more stable when windows gets out of bound (except in center mode)
* also you can use Ctrl+Wheel in the top-center quadrant for a horizontal (bilateral resize).

[hooks1.55test6_i386.zip](https://github.com/RamonUnch/AltSnap/files/9262762/hooks1.55test6_i386.zip)
[hooks1.55test6_x64.zip](https://github.com/RamonUnch/AltSnap/files/9262778/hooks1.55test6_x64.zip)

**Comment by RamonUnch** [comment]
>> > Would it be possible to add both horizontal and vertical resizing for the center titlebar fraction?
>> 
>> How would that be done?
>
>I'm not a programmer and not sure of the technicalities which is why I am asking if it would be possible.....

Actually I was just wondering which key could have been used to invert between horizontal and vertical, but Ctrl is the obvious choice as it can already be used to idicate a vertical only center resize (using the resize action).

**Comment by RamonUnch** [comment]
>  What I meant was that in the titlebar scroll action the window should resize in both directions(horizontal and vertical) by default.

You mean only in the case of titlebar?
I think a separate action could be made that would expend more like that so that people have more choice.

**Comment by RamonUnch** [comment]
This one have two zoom option, the second one corresponds to what you want.
[AltSnap1.55test7_x64.zip](https://github.com/RamonUnch/AltSnap/files/9266215/AltSnap1.55test7_x64.zip)
[AltSnap1.55test7_i386.zip](https://github.com/RamonUnch/AltSnap/files/9266216/AltSnap1.55test7_i386.zip)

**Comment by RamonUnch** [comment]
[hooks1.55test8_i386.zip](https://github.com/RamonUnch/AltSnap/files/9267686/hooks1.55test8_i386.zip)
[hooks1.55test8_x64.zip](https://github.com/RamonUnch/AltSnap/files/9267687/hooks1.55test8_x64.zip)

Aspect ratio cannot be perfect because there is a minimum step in each direction for snapping, plus there is rounding error at every step.

You can prevent AltSnap from resizing windows that are not resizable by disabling the **Resize all windows** option.

This version also fixes the window running out of the screen when zooming too much problem.

**Comment by RamonUnch** [comment]
> Would there be any way to send the normal mouse resizing command instead of the altsnap resizing command?

Unfortunately there is only few documented function to move a window and they are all based on SetWindowPos(). I suspect Microsoft added a new way of resizing/moving windows via the DWM but it is not available for programs.

**Comment by RamonUnch** [comment]
I already use the WM_ENTERSIZEMOVE and WM_EXITSIZEMOVE messages in the Move and Resize actions, My observation is that it was mostly a placebo but I forgot to add it to the Zoom action. it will be done for sure.
