### ISSUE TITLE
The titlebar on the  window created by scrcpy isn't detected by altdrag.

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#241]
Also wanted to add that the titlebar on the  window created by scrcpy isn't detected by altdrag.
https://github.com/Genymobile/scrcpy

_Originally posted by @rp1231 in https://github.com/RamonUnch/AltSnap/issues/235#issuecomment-1200120257_

**Comment by RamonUnch** [comment]
@rp1231
Maybe first have a look at the WM_NCHITTEST value when pointing at the titlebar, using the Identify Window option in the Blacklist tab.
Probably the program does not respond properly as it seems it is redrawing itself everything.

**Comment by RamonUnch** [comment]
It is a SDL based program so it is blacklisted by default.
You can still try to modify the `MMBLower` blacklist and remove the `*|SDL_app,` entry but I am not sure that it will behave correctly:
```
In the [Blacklist] section

MMBLower=*|CASCADIA_HOSTING_WINDOW_CLASS,*|SDL_app,*|MozillaDialogClass
; List of windows for which the Titlebar action should not be performed.
; default is MS-WindowTerminal and all SDL programs.
```

**Comment by RamonUnch** [comment]
I will link this thread to the wiki

**Comment by Ichisich** [comment]
> The reason that SDL apps are blacklisted in this way is that I was unable to make DOSBox windows behave correctly with AltSnap.

Does this still persist?
I only tested DOSBox 0.74 and couldn't notice anything unusal.
SDL apps are very common, I at least use almost a dozen, and not one behaves irregularly (I deleted the blacklist entry long ago).

**Comment by RamonUnch** [comment]
I do not which version I was using but it seems you are right. Also maybe AltSnap changed too. I guess I will remove it from the default list.
