### ISSUE TITLE
Selecting text in address bar initiates bar drag and drop

### ISSUE THREAD

**Issue by ibestvina** [RamonUnch/AltSnap#243]
Very often, but I haven't been able to find any pattern to it, when I start selecting text in the address bar by pressing and dragging the cursor over it, instead of selecting text, the whole address bar starts moving, and most often (when mouse is released) it switches place with the back/forward/refresh buttons.

System: MacOS Monterey 12.4
Vivaldi: 5.3.2679.70

**Comment by RamonUnch** [comment]
I am not sure what to understand,
It seems you are using MacOS but AltSnap is a Windows only program.

From the description of your bug, I suggest you try to blacklist the Vivaldi program.

**Comment by ibestvina** [comment]
Sorry for this, I have no idea how it ended up on your GH - I wanted to post this on the Vivaldi browser page.
