### ISSUE TITLE
Menu remapped to Win (with AutoHotKey) doesn't focus windows

### ISSUE THREAD

**Issue by AstrayCG** [RamonUnch/AltSnap#249]
I'm used to remapping Menu to Left Win key because I use mouse in my left hand and some hotkeys actually don't work with Right Win, not to mention that there are less and less keyboards to choose from that still have the Right Win key.
The problem is, when "Focus windows when dragging" is enabled, it doesn't work with this setup.

Steps to replicate:
1. Install AutoHotKey
2. Make a text file with .ahk extension, type this there: AppsKey::LWin (If you don't have the Menu key, try Left Ctrl instead, for example: LCtrl::LWin)
3. Double click the .ahk file
4. Enable "Focus windows when dragging" option in AltSnap
5. Try dragging windows with the Menu key

**Comment by RamonUnch** [comment]
Well, I guess this one *should* fix it.

[hooks1.55test2_x64.zip](https://github.com/RamonUnch/AltSnap/files/9254441/hooks1.55test2_x64.zip)
[hooks1.55test2_i386.zip](https://github.com/RamonUnch/AltSnap/files/9254445/hooks1.55test2_i386.zip)

Replace the hooks.dll file.

**Comment by AstrayCG** [comment]
RamonUnch. Yep, it does! Thank you very much!
