### ISSUE TITLE
Altsnap is blocking Alt/Ctrl with some combination but work for others.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [RamonUnch/AltSnap#254]
My AltSnap [Config](https://pastebin.com/tutFVrM5)

i have another .ahk running which performs these action and many more.
```
These don't work

>^Space::Send       			        {Media_Play_Pause}
>!Left::Send        				{Media_Prev}
>!Right::Send       				{Media_Next}

```

```
These works
>!Up::Send   					 {Volume_Up}
>!Down::Send   				 {Volume_Down}
```
These are the list of action which won't perform but when i disable Altsnap it works. i closed every program powertoys, radialmenu, capslock++, mousegestureL that can effect but it still does not work.
But when i disable Altsnap these hotkeys starts working.

Can you cross check then in yours.
Also i don't have physical keyboard , using laptop keyboard . could this be the issue ?

**Comment by RamonUnch** [comment]
make sure that the XXButtons list is empty in the [Input] section of the .ini file.

**Comment by RamonUnch** [comment]
>  Also i don't have physical keyboard , using laptop keyboard . could this be the issue ?

Laptop keyboard should behave the same than other keyboards except that some keys may be missing and you got some extra keys, but this is true as well for outside of laptops.

**Comment by PhoenixCODE2322** [comment]
> make sure that the XXButtons list is empty in the [Input] section of the .ini file.

ok its working now ..

**Comment by RamonUnch** [comment]
It is my mistake, the default .ini file that came With AltSnap corresponds to a test config. It should not have been this way by default.
