### ISSUE TITLE
Titlebar move action does not pop down context menu

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#255]
I was having a look at the SmartSystemMenu you recommended and came across another bug.
When the "right click action menu" title bar action is disabled, the native menu doesn't disappear on left click.

https://user-images.githubusercontent.com/47380919/183086840-4b6f0f09-3d99-4c77-ae1e-cfa7a82443ab.mp4

This is before I installed the SmartSystemMenu.
So maybe solving this would solve the Action menu not disappearing sometimes.
idk just taking a guess.

_Originally posted by @rp1231 in https://github.com/RamonUnch/AltSnap/issues/233#issuecomment-1206457742_

**Comment by RamonUnch** [comment]
[hooks1.55test9_i386.zip](https://github.com/RamonUnch/AltSnap/files/9274554/hooks1.55test9_i386.zip)
[hooks1.55test9_x64.zip](https://github.com/RamonUnch/AltSnap/files/9274555/hooks1.55test9_x64.zip)

```
TTBMoveClick=0
; If set to 1, then a click will be sent to the titlebar when
; moving with AltSnap from the titlebar. This can help to pop down
; context menu when the drag starts. AutoFocus needs to be enabled
; for this option to have effect.
```

**Comment by Ichisich** [comment]
Does close the menus and panels reliably, but produces a clearly noticeable delay.

**Comment by RamonUnch** [comment]
> Does close the menus and panels reliably, but produces a clearly noticeable delay and prevents MoveUp.

Strange, for me MoveUp works. and I do not see much of a delay.
Give me your .ini file again, maybe I can figure it out.

**Comment by Ichisich** [comment]
`MoveUp` works when I hold move down as long as the additional delay introduced with `TTBMoveClick`.
[AltSnap.zip](https://github.com/RamonUnch/AltSnap/files/9274645/AltSnap.zip)

**Comment by RamonUnch** [comment]
Well obviously I will need to test with Win10 as I still cannot reproduce.
My guess is that win10 detects specifically when a click is generated while the mouse click is still down and must process multi-touch events, which takes time and can mess up input queue.

**Comment by RamonUnch** [comment]
Well I tried a different strategy:
You no longer have this click stuff but I send the Alt key instead.
Of course to prevent Alt from selecting a menu, I have to send Ctrl in between alt down and alt up.

```
In the [Advanced] section of the .ini file


DragSendsAltCtrl=1
; If set to 1, then Alt_Down, Ctrl_Down, Ctrl_Up, Alt_Up will be sent.
; at the begining of a move/resize action, unless Alt is alreadt down.
; This can help to pop down context menu when the drag starts.
```
[hooks1.55test10_x64.zip](https://github.com/RamonUnch/AltSnap/files/9274801/hooks1.55test10_x64.zip)
[hooks1.55test10_i386.zip](https://github.com/RamonUnch/AltSnap/files/9274802/hooks1.55test10_i386.zip)

**Comment by Ichisich** [comment]
@rp1231 
Alt alone would trigger menu bars and hotkey overlays.

@RamonUnch 
`DragSendsAltCtr`

-Pro
Far less delay (but still an almost unnoticeable amount).
No interference with `MoveUp`.

-Contra
Only works on Windows system menus (and ribbon menus) but not on menus which rely solely on focus loss.
In case the Win button is the hotkey button, using zones activates "Shift+Ctrl+Win+Alt" which triggers the office home page (windows quirk 😒).

**Comment by RamonUnch** [comment]
> But just out of curiosity why is ctrl also being sent along with alt?
Isn't alt enough?

Alt is enough but if you press Alt, then the menu bar will be selected. If you press the alt-ctrl cequence then you fix this problem.

> Why is the titlebar exclusion list called MMBLower?
I always seemed to expand the MMB part as middle mouse button in my head for some reason.

It is for backward compatibility with ini file. It used to be only the middle mouse button in the titlebar that would have lowered a window, then I generalized that and did not change the name of the blacklist because it would force everyone to update their .ini file.

**Comment by RamonUnch** [comment]
>  In case the Win button is the hotkey button, using zones activates "Shift+Ctrl+Win+Alt" which triggers the office home page (windows quirk 

I will avoid to send the sequence then if Shift is down. however I do not expect it to be perfect, we are starting to send too many keys and shortcuts are triggered more easily.

**Comment by RamonUnch** [comment]
in the [Inout] section of the .ini file:

```
MoveUp=Nothing
ResizeUp=Nothing
MoveUpB=Nothing
ResizeUpB=Nothing
; Actions that will be performed on the click UP even of a Move/Resize
; IF no drag occured AND the click was long or PiercingClick=1.
; The B sufixed version apply if the ModKey is down, as usual.
; /!\ Those actions are not associated with buttons but with Move/Resize.
```

I forgot to add it to the wiki, it would deserve a dedicated section

**Comment by RamonUnch** [comment]
So the cool thing with that is that you can have a difference between click&drag  and long click.

**Comment by RamonUnch** [comment]
Any action can be set,
For exalple `MoveUp=Minimize` and a long Alt+Move click (without drag) will minimize the window, same for a long click in the title-bar in your case where AltSnap handles the titlebar.
For an exhaustive list look in the .ini file a little after the [Input] section.

**Comment by RamonUnch** [comment]
```
; Available: Move, Resize, Close, Minimize, Maximize, Lower, AlwaysOnTop,
; Center, Borderless, Roll, Kill, Menu, MaximizeHV, SideSnap, Mute, Nothing.
; Scroll actions: AltTab, Volume, Maximize, Lower, Transparency, HScroll, Nothing.
; When moving and resizing windows, hold shift to snap to other windows.
; For Volume and Transparency, try holding shift to adjust the speed.
```

**Comment by Ichisich** [comment]
`Smarter Aero Snap dimensions` + `ResizeUp=SideSnap`
![3n1ule](https://user-images.githubusercontent.com/31080003/183247647-e5f91f22-cbc3-42ce-9233-b764c44968bb.jpg)

**Comment by RamonUnch** [comment]
Maybe this one will no longer have a lag when using `DragSendsAltCtrl=1`

[hooks1.55test17_x64.zip](https://github.com/RamonUnch/AltSnap/files/9279442/hooks1.55test17_x64.zip)
[hooks1.55test17_i386.zip](https://github.com/RamonUnch/AltSnap/files/9279443/hooks1.55test17_i386.zip)

**Comment by Ichisich** [comment]
No perceivable delay whatsoever.
