### ISSUE TITLE
BLUpperBorder

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#256]
The new approach is in general more accurate and thus an improvement.

Despite that, there are some applications with false positives.
My custom Firefox, for example:
https://user-images.githubusercontent.com/31080003/180955389-c44ae8a6-d996-40fc-94a4-4774d76c6c42.png

Would be nice to be able to exclude them and keep the `BLCapButtons` setting in regard to `WM_NCHITTEST=12` intact.

**Comment by RamonUnch** [comment]
You suggest another BLCapButtons, style setting but for the top resizing border (`WM_NCHITTEST=12`) so that it could be set independently for each mouse button?

Or maybe a general setting to remove the `WM_NCHITTEST=12` from the *extended* titlebar?

**Comment by Ichisich** [comment]
Either your first suggestion or be able to blacklist DWM Buttons detection.

**Comment by RamonUnch** [comment]
> or be able to blacklist DWM Buttons detection

Disable DWM button detection for a mouse button or for a specific window?
I am not sure I understand.

**Comment by Ichisich** [comment]
Only specific windows.
Or introduce a `BLUpperBorder` list.

Both can achieve the same result in different ways.

**Comment by RamonUnch** [comment]
>  Or introduce a BLUpperBorder list.

I will start with this one, It is quite simple to do.
There will always be time to improve upon this later.

**Comment by Ichisich** [comment]
https://github.com/RamonUnch/AltSnap/issues/257#issuecomment-1207338544
