### ISSUE TITLE
Support titlebar specific MoveUp/ResizeUp actions

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#257]
I actually forgot but this would be quite logical.
So titlebar long click could be different than Alt+click.

You would have:
```
MoveUp=Minimize
MoveUpT=Maximize
MoveUpB=Nothing
ResizeUp=Nothing
ResizeUpT=Nothing
ResizeUpB=Nothing
```

And also `MoveUpTB` and `ResizeUpTB` but they are not super useful.
Also ResizeUpT is not very useful as few people would use Resize as titlebar action.

Using Alt+Click in the titlebar should still do the primary MoveUp action, unless titlebar action is enabled with Alt.
~~Using the *move with a long click* should take titlebar into account too.~~ No not really logical, just use the move with titlebar for that.

Also it would have the drawback or breaking ancient configs forcing everyone that used MoveUp to setup also MoveUpT, but because it was a .ini file setting only it is not a big deal, especially If I add those options to the GUI.

**Comment by RamonUnch** [comment]
Here is a test build with a few new things:

1) You can set `MoveUpT` and `ResizeUpT` in the .ini file (also the B varients)
2) Action Menu can now be set as MoveUp/ResizeUp action.
3) You can set this all up using the new GUI. (it is a bit compact but I want to be able to use the config it in 640x480).
4) To simulate old behaviour, you must set both MoveUp and MoveUpT to the same value.

[AltSnap1.55test13_i386.zip](https://github.com/RamonUnch/AltSnap/files/9276258/AltSnap1.55test13_i386.zip)
[AltSnap1.55test13_x64.zip](https://github.com/RamonUnch/AltSnap/files/9276259/AltSnap1.55test13_x64.zip)

@Ichisich this one also adds the `BLUpperBorder` bit-mask in the [Advanced]  section of the .ini.

**Comment by RamonUnch** [comment]
New translations:
```
InputMouseMoveUp=Long &drag-free Move:
InputMouseResizeUp=Long drag-&free Resize:
```

**Comment by Ichisich** [comment]
> this one also adds the `BLUpperBorder` bit-mask in the [Advanced] section of the .ini.

Perfect, thanks.

AltSnap 1.55
[de_DE.zip](https://github.com/RamonUnch/AltSnap/files/9276375/de_DE.zip)
