### ISSUE TITLE
Newest build breaks some AutoHotkey functionality

### ISSUE THREAD

**Issue by Luspin** [RamonUnch/AltSnap#262]
First of all, I really appreciate your continued work on this fork, it's a true life-saver and I can no longer live without it.
I've noticed that the new build breaks some of AutoHotkey's inputs, I believe a lot of people that use this program will also be using AHK.
 
AHK bindings for Media keys won't work while AltSnap is running, e.g.
```SendInput {Media_Play_Pause}```
https://www.autohotkey.com/docs/KeyList.htm
 
It might be related to the Hooks DLL but I am not sure.

**Comment by RamonUnch** [comment]
Remove the XXButtons list from your .ini file.

**Comment by Luspin** [comment]
YES! That's done it, thank you!

**Comment by redactedscribe** [comment]
> Remove the XXButtons list from your .ini file.

Thanks @RamonUnch. I was about to open a new issue about this.

Perhaps you can write something about this in the INI file's comments about how this may conflict with automation software, and too, a warning in the next release's release notes as well, because I think other people may be experiencing this issue and may not know which software on their system is causing the problem and how to fix it.

In fact, maybe `XXButtons=B5 B1 B0 B3` should be a blank value and only an example provided in the comments so that this conflict isn't the default behaviour?

Thanks.

---

Example AutoHotKey script for testing purposes:

```ahk
F1::media_prev
f2::media_next
f3::media_play_pause
f4::launch_media
; should not conflict with AltSnap when AltSnap's INI contains `XXButtons=B5 B1 B0 B3` (`media_stop` is code `B2`):
f5::media_stop
```

**Comment by RamonUnch** [comment]
It is indeed a mistake on my part, the default ini file should never have contained this. This will not be in the next release.

the XXButtons list is a way to convert a key into a n xbutton press so it blocks the key.
It is not related to automation stuff or to ahk, it just blocks the listed keys and sends them as xbuttons to AltSnap

**Comment by RamonUnch** [comment]
I assume however that most people do not override the ini file when they update so it will not be a problem for them.
The next release will be soon anyway and will bring a lot of stuff.

**Comment by Luspin** [comment]
With the new release, "Media_Prev" and "Media_Next" work, but "Media_Play_Pause" and "Media_Stop" don't, even with no values under XXButons

**Comment by Ichisich** [comment]
Can you post your autohotkey script to test?
For reference, my autohotkey script volume section looks like this and works with 1.56:

```
AppsKey & m:: Volume_Mute
AppsKey & ins::Volume_Mute
AppsKey & Space::Media_Play_Pause
AppsKey & del::Media_Play_Pause
AppsKey & home::Media_Prev
AppsKey & end::Media_Next
```

**Comment by Luspin** [comment]
My script is below, but I just tested with yours and nothing else running and I get the same results.

```
; Send "Media_Prev" | "Media_Next" | "Media_Play_Pause"
; AppsKey +  ← | → | SPACEBAR
#If GetKeyState("AppsKey", "P")

    *Left::
        SendInput {Media_Prev}
    Return

    *Right::
        SendInput {Media_Next}
    Return

    *Space::
        ; If I put MsgBox, "Some Text" here, it will fire the MsgBox, but not the Media control.
        SendInput {Media_Stop}
    Return

#If ; End Context Sensitivity
```

**Comment by Ichisich** [comment]
Media_Stop/Prev/Next works with your script, but Media_Play_Pause seems to occupy the same shortcut as Stop

Can you post your altsnap.ini. 
Github accepts .zip

**Comment by Luspin** [comment]
Right now it's the default one, I removed it and let AltSnap create a new one.
However, it's working now, for some reason, so let's leave this as is unless someone else complains.
Thanks for your help!

**Comment by redactedscribe** [comment]
Next, prev, play/pause, and stop all work fine for me using AltSnap 1.56 with `XXButtons` set to a blank value.
