### ISSUE TITLE
Allow setting any keybaord shortcut for any action

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#268]
This would become handy and would replace some ad-hock settings, such Ctrl+Alt+F4 -> Kill. #264 
Also the keyboard-only actions should apply to the foreground window.

So instead of using the LowLevelKeyboardHook, AltSnap would rather use the `RegisterHotKey()` function.
* This should improve compatibility with accessibility tools such as the sticky keys (which I am not sure works well with AltSnap).
* This might have some drawback (not sure which though).
You also should not be able to setup shortcuts that were already set by the system This is both an advantage and a limitation. I would prefer AltSnap not to override system shortcuts though.

**Comment by RamonUnch** [comment]
Here you go, You can now map action to a keyboard shortcut.
I had to rewrite the Shortcut capture routine for the config because the default control does not allow usage of the WinKey.

in the Keyboard tab, you need to first select the action for which you want to assign the shortcut, then you can click the **Pick keys** button and then Press you shortcut:

Eg: select Kill program, Then click the **Pick keys** button then Press CTRL+ALT+F4 and then click the small Apply button.
You may need to disable/enable altsnap for the shortcut to apply. You need to click the Apply button for each shortcut you want to set.

[AltSnap1.55test30_x64.zip](https://github.com/RamonUnch/AltSnap/files/9337284/AltSnap1.55test30_x64.zip)
[AltSnap1.55test30_i386.zip](https://github.com/RamonUnch/AltSnap/files/9337285/AltSnap1.55test30_i386.zip)

**Comment by RamonUnch** [comment]
> A better functionality would be Seek Empty Space and Rotate through Zones, given that the mouse can't specify the location.

This would be nice new features indeed.
I will remove the SnaptoSide/corner from the list. Also because you can already do it with Win+Arrows keys natively.
I also did not include the *Close* action because it is the same than Alt+F4. But you can still do it from the .ini file (difficult though).

I guess than rather than rotating through zones should be something like 4 separate actions to move to the next left/right/above/below zone,so that one could map them with Alt+Win+Arrows keys or something similar.

> Quick nitpick, keyboard settings don't get saved with the in-gui apply.
You first have to change something else and then commit with the window Ok/Apply.

Indeed a bit wird, actually, I will fix that.

**Comment by Ichisich** [comment]
> Also because you can already do it with Win+Arrows keys natively.
> I also did not include the _Close_ action because it is the same than Alt+F4.

Following that logic, you can also scrap maximize vertically (shift+win+up) and minimize other windows (win+home).

**Comment by RamonUnch** [comment]
> Following that logic, you can also scrap maximize vertically (shift+win+up) and minimize other windows (win+home).

And also minimize/maximize (Win+Down/up). This will help people to navigate better, through the options.

**Comment by RamonUnch** [comment]
Fixed:

[AltSnap1.55test31_i386.zip](https://github.com/RamonUnch/AltSnap/files/9339032/AltSnap1.55test31_i386.zip)
[AltSnap1.55test31_x64.zip](https://github.com/RamonUnch/AltSnap/files/9339033/AltSnap1.55test31_x64.zip)

Also @xan2622 With this build you can set `PinColor=FF FF 00`  in the `[Input]` section of the ini file and it will disable the T letter. You can configure any aschii caracter by adding its hex code at the end of the color ie`PinColor=FF FF 00 54` => Yellow+T.

And also @rp1231 you can easily setup a shortcut for the Always on top option, like Ctrl+Win+T.
