### ISSUE TITLE
Move/extend a window to zones with keyboard only

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#270]
In response to https://github.com/RamonUnch/AltSnap/issues/268#issuecomment-1215070305 by @Ichisich

I made (was quite simple to do):
4 New actions to go to the next Left/top/right/bottom zone, with regard to the current window position
Also 4 new additional actions to extend the window with the zone on the Left/top/right/bottom.

Not yet in the GUI, but you can use:
```
in the `[KBShortcuts]` section of the .ini file

; Move to left right top bottom zone with
; Ctrl+Win+Arrows.
MLZone=2597
MTZone=2598
MRZone=2599
MBZone=2600
; Extend with Ctrl+Shift+Win+Arrows
XLZone=3621
XTZone=3622
XRZone=3623
XBZone=3624
```
I think Ctrl+(Shift)+Win+Arrows are not used by windows, not even Windows 11.

[hooks1.55test31_i386.zip](https://github.com/RamonUnch/AltSnap/files/9349279/hooks1.55test31_i386.zip)
[hooks1.55test31_x64.zip](https://github.com/RamonUnch/AltSnap/files/9349289/hooks1.55test31_x64.zip)

I will see for the idea of snap to empty space, this is less trivial as I have to figure out where the empty space is.

**Comment by Ichisich** [comment]
Ctrl+Win+Left/Right is mapped to change "virtual desktop" since Win 10.

**Comment by Ichisich** [comment]
So I tested it with

```
; Move to left right top bottom zone with
; Ctrl+Alt+Arrows.
MLZone=805
MTZone=806
MRZone=807
MBZone=808
```
Changing zones is working fine, entending I still have to test.

**Comment by Ichisich** [comment]
One issue I found:
Changing zones out of maximized windows, with the keyboard, doesn't resolve the maximized state, which can lead to misaligned borders.

**Comment by RamonUnch** [comment]
Indeed I must fix that.

**Comment by Ichisich** [comment]
Somehow Ctrl+Alt+Shift didn't work for extending, so I settled with Alt+Shift
```
; Extend with Shift+Alt+Arrows
XLZone=1317
XTZone=1318
XRZone=1319
XBZone=1320
```

No complaints so far, but admittedly, I don't use this feature at all, so there could be quirks I'm not familiar with.

**Comment by RamonUnch** [comment]
Makes sense indeed.

I am not so sure this would be useful because pressing Ctrl+Alt+Left+RightArrow+TopArrow does the trick which is not too bad. as you do not have to release Ctrl and Alt.
Plus for now if you have for example a window covering both right zones, then Pressing Ctrl+Alt+Up will snap it to the top zone and Ctrl+Alt+Down will snap it to the bottom which is very intuitive.

So it would have to apply only if the current window is covering a single zone.
