### ISSUE TITLE
Option to use move cursor while moving instead of pointer

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#273]
Pointer cursor is a bit cursed for moving windows, would prefer for it to be the move cursor like X11 (and what happens when you resize in the center region)

This one:

![image](https://user-images.githubusercontent.com/4723091/185058959-7513496e-219c-423e-9dc2-3a9b73571ac0.png)

**Comment by RamonUnch** [comment]
Set UseCursor=4. 
This is detailed in the Wiki, i think

**Comment by LoganDark** [comment]
Thanks, that did it!
