### ISSUE TITLE
Esc to exit action menu does not refocus the window

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#274]
Open action menu on a window and press esc to close the action menu. The underlying window doesn't regain focus even though it probably should.

**Comment by RamonUnch** [comment]
This one does.
[AltSnap1.55test33_i386.zip](https://github.com/RamonUnch/AltSnap/files/9374254/AltSnap1.55test33_i386.zip)
[AltSnap1.55test33_x64.zip](https://github.com/RamonUnch/AltSnap/files/9374255/AltSnap1.55test33_x64.zip)

**Comment by LoganDark** [comment]
Thanks, I was running 1.54
