### ISSUE TITLE
Alt to open action menu blocks everything

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#276]
I'm trying to find a way to open the action menu without middle click, my trackpad only has left and right click (Windows lies about middle click, middle click doesn't exist #247).

If I set keyboard action to open action menu, it blocks absolutely everything. No alt+tab, no alt+arrows to navigate in a web browser, etc.

I can't figure out the "modifier key for alternate action". It doesn't work. Like if I set it to shift and then set the alt action to action menu, Alt+Shift does nothing. Just confused.

Is this intended? If so is there any way to set the action menu to be something like alt+space? (yes that keybind is used by Windows but I don't care)

**Comment by RamonUnch** [comment]
The modifier key has to be pressed BEFORE alt because the action is triggered when alt is pressed.
Action without click should generally used with the two keys combo option.


> If I set keyboard action to open action menu, it blocks absolutely everything. No alt+tab, no alt+arrows to navigate in a web browser, etc.
Normally Alt Should not work at all to popup the action menu because the menu gets disabled by Alt.
You can use the Winkey instead for the action menu.

**Comment by LoganDark** [comment]
> The modifier key has to be pressed BEFORE alt because the action is triggered when alt is pressed.

This still doesn't do anything. If I set these settings:

![image](https://user-images.githubusercontent.com/4723091/185405353-d4fe3088-76ef-4f5a-878c-30b8bd074746.png)

Holding Shift and pressing Alt does nothing.

> Normally Alt Should not work at all to popup the action menu because the menu gets disabled by Alt.
> You can use the Winkey instead for the action menu.

Adding Winkey to the hotkeys doesn't work either if I hold shift and then press win.

**Comment by LoganDark** [comment]
> Action without click should generally used with the two keys combo option.

This also affects the window dragging which I don't want

**Comment by RamonUnch** [comment]
Which AltSnap version are you using?
Normally you need to setup a primary action if you want to use a secondary action.

**Comment by RamonUnch** [comment]
You cannot popup a menu with the Alt key, it is not possible and there is no way that I can make it happen.
Grab with Alt was designed with movement in mind.

**Comment by RamonUnch** [comment]
I mean If you are using 1.54 then the picture you posted means that the menu action wil never be performed because the primary action is set to nothing.

In the latest test builds then you can use a secondary action without setting a primary action even if I really ever saw the point.

**Comment by LoganDark** [comment]
Yes I'm using 1.54

> You cannot popup a menu with the Alt key, it is not possible and there is no way that I can make it happen.

Windows by default support Alt+Space to pop up a window, is that special or something?

Is there any way to be able to pop up the action menu without modifying the normal alt+click behavior?

**Comment by RamonUnch** [comment]
With the latest builds 1.55test33 you get more options.
You can do what you just did and it should work.
You can also setup a keyboard shortcut to do it

> Windows by default support Alt+Space to pop up a window, is that special or something?

SPACE pops up the menu, not ALT, the order of the keys does matter...

**Comment by LoganDark** [comment]
> SPACE pops up the menu, not ALT, the order of the keys does matter...

Yes, I'm aware, holding down alt lets you press "accelerators" which are the names of the keys that do stuff

Space in this case brings up the window menu which is usually opened by right clicking the titlebar or left clicking the icon

>  You can also setup a keyboard shortcut to do it

This would work, thank you! Is it possible to fix this particular issue (in the title) or should I just close it as wontfix?

**Comment by RamonUnch** [comment]
I do not see Alt blocking everything.
When you press Alt+Tab for example even If I set Alt to Popup the menu, I just see the menu flicker for a *split-split* second and Alt+Tab is performed normally.

**Comment by LoganDark** [comment]
Now Alt+Tab works but there is a bug where if you press ESC even after the menu is closed then your focus gets taken away from the new window and given back to the previous window. I think this is due to your fix for #274

**Comment by LoganDark** [comment]
Also the shortcut settings can't be saved, the apply button doesn't get enabled and even if I press OK, they stay unset when I reopen the configure menu, is this caused by an outdated ini file or something?

**Comment by RamonUnch** [comment]
> Now Alt+Tab works but not the menu, and there is a bug where if you press ESC even after the menu is closed then your focus gets taken away from the new window and given back to the previous window. I think this is due to your fix for https://github.com/RamonUnch/AltSnap/issues/274

Indeed I did not test it enough, it occurred to me just now too.

You need to press the Save button for it to be saved for each indivibual shortcut you setup.
The big apply button should do nothing

**Comment by LoganDark** [comment]
> Indeed I did not test it enough, it occurred to me just now too

It's OK if the menu doesn't get closed by pressing Alt, so I can still use the test build now that my shortcut can be Alt+Space, which doesn't cause the glitch

Thank you :)

**Comment by RamonUnch** [comment]
For now the keyboard only shortcuts apply to the foreground window so if you setup the action menu, it will appear at your cursor but apply on the window that was focused.

**Comment by LoganDark** [comment]
> if you setup the action menu, it will appear at your cursor but apply on the window that was focused.

Yeah that's a bit annoying, it sounds like it should be a setting or maybe two separate actions (open action menu at focus, open action menu at cursor)

**Comment by RamonUnch** [comment]
It will be an option, just not yet implemented.

**Comment by RamonUnch** [comment]
[AltSnap1.55test34_x64.zip](https://github.com/RamonUnch/AltSnap/files/9377770/AltSnap1.55test34_x64.zip)
[AltSnap1.55test34_i386.zip](https://github.com/RamonUnch/AltSnap/files/9377773/AltSnap1.55test34_i386.zip)
![acmenuonWin+Space](https://user-images.githubusercontent.com/74856804/185498787-f75a5bb5-119a-44fb-a82d-1135bfd21896.png)

Now the menu appears on the focused window if enabled from a keyboard shortcut. 
You can setup in the keyboard to Apply to the pointed window and the menu will appear on the cursor window and apply to the pointed window. All other keyboard shortcuts will apply to the pointed window too.
