### ISSUE TITLE
[Bug] Cannot use media keys while AltSnap is active

### ISSUE THREAD

**Issue by HOSEK1** [RamonUnch/AltSnap#278]
Whenever AltSnap is active, my media keys (Pause, Next, Previous) stop working. 
I tried changing the configs, couldn't resolve it. 

Tested on 2 computers and got the same result.
`Windows version: Win 10 Pro, 21H2 build 19044.1889`

**Comment by RamonUnch** [comment]
Remove the XXButtons list fromthe .ini file
This is a bug with the default config that was already reported a few times, it will be fixed in next release.

**Comment by RamonUnch** [comment]
use latest 1.55 build
