### ISSUE TITLE
New Update bugged "Move window with a long left-click"

### ISSUE THREAD

**Issue by PhoenixCODE2322** [RamonUnch/AltSnap#280]
i cross checked it with deleteing .ini and replacing it with new .ini and changing only this option.
The buggy behaviour
1. it does not work.
2. if it does and performing this action, altsnap does not respond to any other action anymore.

**Comment by PhoenixCODE2322** [comment]
for my G.K .. what does this caption button means ?
```
BLCapButtons=3
; Mouse Buttons for which the caption buttons will not be considered
```

**Comment by Ichisich** [comment]
BlackListCaptionbutton, mouse buttons which ignore the caption buttons and perform title bar actions instead.

**Comment by RamonUnch** [comment]
Indeed huge bug, sorry for that.
Here is the fix:
[hooks1.55fix1_i386.zip](https://github.com/RamonUnch/AltSnap/files/9387706/hooks1.55fix1_i386.zip)
[hooks1.55fix1_x64.zip](https://github.com/RamonUnch/AltSnap/files/9387714/hooks1.55fix1_x64.zip)

**Comment by RamonUnch** [comment]
BLCapButtons only concerns you if you are using title bar actions.
If you set `BLCapButtons=0` and Move as a Titlebar action for the left click for example, then when you left click the caption buttons inside the titlebar ( [_] [O] [X] ), the window will be moved instad of minimized/maimized/closed.
So by default I would recommend 1, 3 or -1
1 => Lets you left click *normally* on the caption buttons
3 => Lets you left and right click *normally* on the caption buttons
-1 => lets any click be *normal* inside the caption buttons.

**Comment by RamonUnch** [comment]
This bug is big enough to justify a new release, but I will wait one more day in case more is coming.

**Comment by PhoenixCODE2322** [comment]
> Indeed huge bug, sorry for that. Here is the fix: [hooks1.55fix1_i386.zip](https://github.com/RamonUnch/AltSnap/files/9387706/hooks1.55fix1_i386.zip) [hooks1.55fix1_x64.zip](https://github.com/RamonUnch/AltSnap/files/9387714/hooks1.55fix1_x64.zip)

please don't say sorry. You are so humbele and we are so much thankfull to you. 

Thanks for the quick fix.

**Comment by PhoenixCODE2322** [comment]
testing it .. will report soon

**Comment by PhoenixCODE2322** [comment]
its working. Thanks again
