### ISSUE TITLE
Feature Request: (Zoom 3?) Expand window up to the screen edge

### ISSUE THREAD

**Issue by xan2622** [RamonUnch/AltSnap#281]
Idea for a "Zoom 3" action (or maybe as a parameter to add to the ini file ?): 

I really like the "Zoom" action, that I use with the mouse wheel. It is handy for resizing horizontally and vertically: 

<details>
  <summary>Here is the "Zoom" action (click me):</summary>
<img src="https://user-images.githubusercontent.com/1732773/185751575-7ed5ad7f-c98e-4dc6-b660-ae7c9d2c6779.gif" width="100%" height="100%"> It works fine, no problem with it. 
</details>

---

That being said, it would be convenient (to resize the window extremely quickly) if the window width could expand to the edge of the screen as soon as the hotkey is pressed: 

![Animation_expand_to_edge](https://user-images.githubusercontent.com/1732773/185752003-00dcf829-1377-4204-a61b-66a4f935a7e3.gif)

Same for the window height: if the user use the "mousewheel up", the window could resize vertically up to the top edge of the screen.

![Animation_expand_to_edge_02](https://user-images.githubusercontent.com/1732773/185752165-17e8c60b-7ff5-452b-9326-bbd7cf688fba.gif)

**Comment by Ichisich** [comment]
Already exists.
Either use shift+sidesnap or shift+double resize.

**Comment by xan2622** [comment]
Hi. Please excuse my ignorance but can you point me to the AltSnap options where I can see these hotkeys ?
Thanks in advance.

**Comment by Ichisich** [comment]
They are fraction sensitive.

Double resize and shift double resize applied to a fraction are default actions.
The other action is called `Snap to Side/Corner` and is also modified by shift.

**Comment by xan2622** [comment]
Thank you very much for your help.
I didn't know about these hotkeys.

**Comment by RamonUnch** [comment]
When using Shift+SideSnap the window should not move, if you just use SideSnap alone, it will snap to the sides like areosnap.

With Shift+SideSnap, The side/corner to which you point your mouse will instead extend to the monitor side/corner, so I am not sure what the big difference is with Zoom3.

However I agree that it could be available also as a separated option, and it could also map to the mouse wheel. Not sure how wheel up/down should behave exactly though.

**Comment by xan2622** [comment]
ok, sorry for bumping this thread. 😳
I didn't clearly understand what you meant by `Shift + double resize`. Now I got it working.
I guess I got lost in translation. 😅

**Comment by RamonUnch** [comment]
If you prefer to have Double resize extending the window without having to press shift, you can check the **Invert Shift behavior for double-click aero snapping**.

A separated *Extend to monitor side/corner* mouse action will be available in next release it will be useful for people that do not like to double click.
