### ISSUE TITLE
Entry in action menu to temporarily disable alt drag

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#283]
I would love an entry in the action menu to temporarily disable alt drag (but not the action menu itself), it would be much faster than hunting down the icon in the system tray.

i.e. I use alt+click to move/resize windows, and alt+space to open the action menu, would be nice if there was an action menu item to just toggle the former, so I can still open the action menu to re-enable it later.

**Comment by RamonUnch** [comment]
You can already setup a keyboard only shortcut for the Action menu (using 1.56):
For example I use Win+SPACE for the Action menu.

Also to Suspend/Resume AltSnap, you can use the Scroll lock key. there is an option in the Keyboard tab.
If you want AltSnap to be disabled when Scroll lock is ON, then set `ScrollLockState=3` in the [Input] section of the .ini

It does make sense to add an additional action to Suspend/Resume AltSnap.

**Comment by LoganDark** [comment]
> You can already setup a keyboard only shortcut for the Action menu (using 1.56):

I already have one. But disabling AltSnap from the tray icon disables the keyboard shortcut as well. I would like a way to disable only the movement and resizing/

> you can use the Scroll lock key

I do not have that key.

> It does make sense to add an additional action to Suspend/Resume AltSnap.

Make sure it does not suspend the keyboard shortcut to open the action menu

**Comment by RamonUnch** [comment]
> I already have one. But disabling AltSnap from the tray icon disables the keyboard shortcut as well. I would like a way to disable only the movement and resizing

Yes disabling AltSnap is notthe same than the scroll lock way.
When you disable via the tray, AltSnap is designed to remove ALL INTERACTIONS. So EVERYTHING is disabled and the hooks.dll file is unloaded from memory.

> I do not have that key.

I should have thought about that.

**Comment by RamonUnch** [comment]
[AltSnap_i386.zip](https://github.com/RamonUnch/AltSnap/files/9393284/AltSnap_i386.zip)
[AltSnap_x64.zip](https://github.com/RamonUnch/AltSnap/files/9393290/AltSnap_x64.zip)

This version adds the suspend/resume Altsnap shortcut (you need to configure)
It also adds the option to the action menu (only if it was opened from a keyboard shortcut).

**Comment by LoganDark** [comment]
> [AltSnap_i386.zip](https://github.com/RamonUnch/AltSnap/files/9393284/AltSnap_i386.zip) [AltSnap_x64.zip](https://github.com/RamonUnch/AltSnap/files/9393290/AltSnap_x64.zip)
> 
> This version adds the suspend/resume Altsnap shortcut (you need to configure) It also adds the option to the action menu (only if it was opened from a keyboard shortcut).

I replaced the executables but it does not look like there is a new entry in the action menu when I trigger it using alt+space:

![image](https://user-images.githubusercontent.com/4723091/185895520-1e817ec2-6247-491a-a917-16cd996142db.png)

I have "apply to the pointed window" enabled, which seems to be the problem.

**Comment by LoganDark** [comment]
I would recommend turning the "Suspend/Resume AltSnap" into a checkbox just like the toggles. For example, name it "Suspend AltSnap" and have it be checked if it's already suspended, and unchecked otherwise

**Comment by RamonUnch** [comment]
It is really a test build.
I am really hesitant to add this option to the action menu, it really does not belong there because it does not concerns the current window at all, and it really makes no sense to me.  Plus I am forced to restrict its use because once you disabled AltSnap via the menu, the only way to have the menu again is a keyboard only shortcut. So it is a no-no if the menu appeared via a kb+mouse action.

Is not a customizable keyboard shortcut enough? I feel it makes double use and I really do not like having it in the action menu.

**Comment by LoganDark** [comment]
> It is really a test build.

Well yeah, I know this is not the final version, which is why I recommended changes :)

> I am really hesitant to add this option to the action menu, it really does not belong there because it does not concerns the current window at all

It is difficult for me to answer this question. On one paw, I understand the single responsibility principle. The action menu is only for the window. On the other... no, wait. I have a solution.

What if you really did make it window local? Use the action menu to disable moving and resizing *only the one window*. That would actually still solve my problem (which is games with an alt+drag keybind), but let me continue to use AltSnap for other windows.

**Comment by Ichisich** [comment]
> What if you really did make it window local? Use the action menu to disable moving and resizing _only the one window_. That would actually still solve my problem (which is games with an alt+drag keybind), but let me continue to use AltSnap for other windows.

You could disable AltSnap in Full-screen/Maximized applications or blacklist your games.
But I agree to make the suspend function configurable and not lock it to the scroll key, as not every keyboard nowadays has it.

**Comment by LoganDark** [comment]
> blacklist your games

This is even more inconvenient than clicking the tray icon, so no, I would prefer not to do this

**Comment by Ichisich** [comment]
The first time, yes, but in the long run and subsequent runs it is even more convenient than a shortcut.

**Comment by Ichisich** [comment]
The synthesis would be to add a `Blacklist Process` action. (Action menu/ Shortcut/ Mouse Action).

**Comment by LoganDark** [comment]
This isn't what my feature request is about, please make a new one

**Comment by RamonUnch** [comment]
> What if you really did make it window local? Use the action menu to disable moving and resizing only the one window. That would actually still solve my problem (which is games with an alt+drag keybind), but let me continue to use AltSnap for other windows.

It could make sense to add it to the blacklist temporally.
I would prefer not to have it modify the ini file, as all settings are only modified from the config dialog.
But then again, how would you re-enable AltSnap on those programs without disabling/re-enabling AltSnap?
Every time you use the Action Menu you would be at one miss-click from disabling AltSnap for the program then to re-enable it you would need to look for the tray icon and disable/enable AltSnap. It is not going to integrate well.

**Comment by LoganDark** [comment]
> It could make sense to add it to the blacklist temporally.

That's not what I'm asking for. Adding it to the blacklist would disable all actions, even opening the action menu. I only want to disable movement and resizing.

> I would prefer not to have it modify the ini file, as all settings are only modified from the config dialog.

This would be temporary, in memory, not saved to the ini file. It would be treated similarly to how borderless is now, except AltSnap would keep track of the windows where movement/resizing is disabled.

> But then again, how would you re-enable AltSnap on those programs without disabling/re-enabling AltSnap?

By using the action menu keyboard shortcut, which wouldn't be disabled

> Every time you use the Action Menu you would be at one miss-click from disabling AltSnap for the program then to re-enable it you would need to look for the tray icon and disable/enable AltSnap. It is not going to integrate well.

Every time you use the action menu you are one misclick away from terminating the entire process so I don't think this is a very big problem. The whole point of the action menu is to perform actions

**Comment by RamonUnch** [comment]
Disabling AltSnap for a specific window is an administrative task, If you want not to have to do it, then use a key combo, or suspend AltSnap temporarily with the keyboard shortcut.

I could add the **Add to blacklist** action menu entry that would open the config dialog with the process mane appended to the balcklist, and you would just have to press OK and the program would be blacklisted.

**Comment by RamonUnch** [comment]
So it is just about disabling MOVEMENT for a specific window temporarily?
It is starting to be quite specific.

**Comment by LoganDark** [comment]
Sorry for my tone, I realize I'm getting annoyed by the other things that are being proposed here.

To be perfectly clear this feature request is about the ability to temporarily disable moving and resizing a specific window (not a program, and not permanently) from the action menu. That way the action menu would still work to turn it off later, but I can use things like alt+drag for, say, multi cursor in a text editor.

It would only last until the window is closed, but that's fine because I only care about the one window.

I'm not asking about an easier way to add processes to the blacklist. I'm not asking about a keyboard shortcut to toggle AltSnap globally. I'm not asking about any of that.

> So it is just about disabling MOVEMENT for a specific window temporarily?  
> It is starting to be quite specific.

Yes my feature request is quite specific really and all the alternatives proposed here don't serve my use case well. Hopefully the explanation above helps

**Comment by RamonUnch** [comment]
It makes more sense indeed, plus it would easy to do.
some kind of Disable AltSnap movement/ Enable AltSnap movement

**Comment by LoganDark** [comment]
> It makes more sense indeed, plus it would easy to do.  
> some kind of Disable AltSnap movement/ Enable AltSnap movement

yes, sorry it took me so long

**Comment by RamonUnch** [comment]
Adds the Movement disabled menu entry.
[AltSnap1.57test1_i386.zip](https://github.com/RamonUnch/AltSnap/files/9415274/AltSnap1.57test1_i386.zip)
[AltSnap1.57test1_x64.zip](https://github.com/RamonUnch/AltSnap/files/9415277/AltSnap1.57test1_x64.zip)

**Comment by LoganDark** [comment]
Perfect, that's exactly what I had in mind! Thank you <3

**Comment by brian6932** [comment]
@RamonUnch I think this (unintentionally) inverted the tray logo for enabled and disable state

**Comment by LoganDark** [comment]
> @RamonUnch I think this (unintentionally) inverted the tray logo for enabled and disable state

It didn't, I'm using the test build that added this change and it does not have that issue

**Comment by brian6932** [comment]
Well there it is inverted in live

**Comment by LoganDark** [comment]
> Well it is inverted in live

That is not caused by this issue
