### ISSUE TITLE
Winget source out of date v1.53

### ISSUE THREAD

**Issue by ShayBox** [RamonUnch/AltSnap#289]

**Comment by RamonUnch** [comment]
Unfortunately I am not the maintainer of the winget package and I do not use winget.
You should try to find the maintainer if any or maybe consider submitting yourself the update?
I am not sure of what the package submission process is for winget.
I did not know the existence of winget before someone came to me telling that my package was on it.

The only *official* package is the chocolatey package, which is now recognized as a trusted package by the chocolatey reviewer so there is never more than a day before it is updated and I am the maintainer. The GitHub page is always the first one to be updated with new releases.
