### ISSUE TITLE
Left click to close window in a window list

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#290]
@onguarde

Here is an improved version of the Stacked list Menu that adds the option to close the selected window with the right click on the menu.
This Clsoe action is the same than clicking on the close button in the caption.

When you close the item, the title becomes grayed and the icon turns into the Error icon to indicate that the window was closed:
![StackedWindowList2](https://user-images.githubusercontent.com/74856804/188159798-5aec4ab4-f37c-4997-8f88-b10e772f8c87.png)

The menu remains opened when you right-click an item so that you can easily close several windows.

[AltSnap1.57test7_i386.zip](https://github.com/RamonUnch/AltSnap/files/9478230/AltSnap1.57test7_i386.zip)
[AltSnap1.57test7_x64.zip](https://github.com/RamonUnch/AltSnap/files/9478232/AltSnap1.57test7_x64.zip)

This relies on the `WM_MENURBUTTONUP` message introduced with Windows 2000.
The option can be disabled setting the `RCCloseMItem=0` value in the `[Advanced]` section of the .ini.

**Comment by onguarde** [comment]
wow this is awesome, it works perfectly. Can close windows really fast.

**Comment by fourteen-1** [comment]
Can someone explain this feature to me? I don't understand how to use it. How can I open this "stacked list menu"?

**Comment by RamonUnch** [comment]
It was an alpha built, now the middle click is used to close a window and the right click minimizes the window.
The "stacked list menu" can be configures as a a mouse or keyboard action.
