### ISSUE TITLE
Window transparency issues when maximising/restoring

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltSnap#293]
I've got AltDrag set so that each time the window is dragged, the window becomes slightly transparent (Mouse > Title bar > LMB > Move window is set). The problem is that now when I double-click the _title bar to maximize_ the window, the window changes and remains at the transparency level set for when the window is being dragged. Clicking on the window after this happens restores the window to being fully opaque:

https://user-images.githubusercontent.com/25013746/188314576-660899dd-f16b-4869-ab4b-1786a508f530.mp4

Also, notice the bottom-left showing the input keys. I only used the left-mouse button in the video recording, but for some reason, Ctrl is shown when grabbing the window's title bar for the first time. The input keys software is kind of old so perhaps it has a bug.

Also, When I maximise/restore the window via holding the Alt key (actually Win key for me) and double-click the window area _and I do not let go of the Win key_, the window will stay transparent for as long as I hold the Win key down for:

https://user-images.githubusercontent.com/25013746/188315196-9899e237-fc2d-473c-ae42-a8b72c5742c6.mp4

Thanks.

AltDrag 1.56
Windows 11

**Comment by RamonUnch** [comment]
Thanks for your very detailed report.
This version should fix it.
You have to manually extract the files (x64) and replace both AltSnap.exe and hooks.dll

[AltSnap1.57test9_i386.zip](https://github.com/RamonUnch/AltSnap/files/9484868/AltSnap1.57test9_i386.zip)
[AltSnap1.57test9_x64.zip](https://github.com/RamonUnch/AltSnap/files/9484871/AltSnap1.57test9_x64.zip)

**Comment by redactedscribe** [comment]
Both issues fixed, thanks!
