### ISSUE TITLE
Windows Terminal hides itself when minimizing other windows is issued

### ISSUE THREAD

**Issue by zhichaoh** [RamonUnch/AltSnap#295]
I found the windows terminal has troubles with "Minimizing other windows" behavior. It always minimize itself when such a action is issued. But similarly, the Windows + Home will correctly minimizing other windows in the same scenarios. The altsnap version is 1.56. The OS is Windows 11.

**Comment by RamonUnch** [comment]
Interesting...
Does it happen when you perform the action while clicking on the titlebar?
I have an idea of what it might be, have a try with this build (you need to replace both AltSnap.exe and hooks.dll)

[AltSnap1.57test12_x64.zip](https://github.com/RamonUnch/AltSnap/files/9550978/AltSnap1.57test12_x64.zip)
[AltSnap1.57test12_i386.zip](https://github.com/RamonUnch/AltSnap/files/9550981/AltSnap1.57test12_i386.zip)

**Comment by zhichaoh** [comment]
I tried the patch and still the same behavior (terminal itself is also minimized). Clicking on titlebar behave the same way (I.e. binding the action to one of the titlebar click). Actually, in windows terminal, you can hide/unhide title bar. I unhide the title bar and none of the actions I registered with title bar works. But they are all working fine (roll up/down, etc) for other apps. Unfortunately, the patch does not seem to fix the issue. Thanks.

**Comment by RamonUnch** [comment]
For titlebar specific actions, have a look at https://github.com/RamonUnch/AltSnap/issues/11
Short story: If you keep the titlebar enabled in Windows Terminal, then you can remove it from the titlebar blacklist (`MMBLower`) in the AltSnap.ini file. Onceyou removed it from the titlebar blacklist you will be able too perform titelabr actions.
Window Terminal titlebar is blacklisted by default because unless you display it fully, it is buggy.

**Comment by Ichisich** [comment]
Can confirm, the terminal gets also minimized with a very short delay compared to the other windows.
The Terminal also has the quirk that it draws invisible borders on the desktop, which can mess up snapping.
The Terminal is the only program, to my knowledge, that shows this behavior.

**Comment by RamonUnch** [comment]
This version will show a popup before minimizing each other window.

[AltSnap1.57test13_x64.zip](https://github.com/RamonUnch/AltSnap/files/9554382/AltSnap1.57test13_x64.zip)

Just copy/paste the message box content that is just before the window treminal minimization (when it should not get minimized).
To copy the textual content of a message bow, just hit Ctrl+C after selecting the MessageBox, then when you paste you will see the whole content appear: ie:
```
---------------------------
Goinng to Minimize:
---------------------------
Hwnd=1230090/1230090, [hooks.c] - GreenPad|GreenPad MainWnd, style=14cf0000, xstyle=110
---------------------------
OK   
---------------------------
```

So just click on the Window Terminal window to minimize all other window and click and each new popup Hit Ctrl+C , then press OK, until the Window Terminal get minimized.

**Comment by Ichisich** [comment]
With this build, the terminal is the first window that gets minimized and shows the following:
```
---------------------------
Goinng to Minimize:
---------------------------
Hwnd=40140/90510, |PseudoConsoleWindow, style=94cf0000, xstyle=80801a0
---------------------------
OK   
---------------------------
```

**Comment by RamonUnch** [comment]
Well I guess this `|PseudoConsoleWindow` is owned by the Window Terminal and minimizing it minimizes also the owner.
So have a try with this hooks.dll
[hooks1.57test14_x64.zip](https://github.com/RamonUnch/AltSnap/files/9555878/hooks1.57test14_x64.zip)

It will still display message boxes...

**Comment by Ichisich** [comment]
With test14 the terminal keeps up.
But windows on other virtual desktops get also minimized, and the terminal loses focus, although the latter is probably due to the message boxes.

**Comment by RamonUnch** [comment]
[hooks1.57test15_x64.zip](https://github.com/RamonUnch/AltSnap/files/9557072/hooks1.57test15_x64.zip)

Strange, it should not minimize windows from other virtual desktops. Does the 1.56 build have this problem too?
The above version does not display message boxes, otherwise should be Identical.

**Comment by Ichisich** [comment]
No, regular 1.56 doesn't, only the debug box message builds do.
They also change the `Snap Gap`.

Test15 fixes the focus loss, so it was just a message box thing.

**Comment by RamonUnch** [comment]
Ok, I think I git the problem, it is because I was experimenting with extra DWM flags and it messed up their numbering sequence.
[AltSnap1.57test16_x64.zip](https://github.com/RamonUnch/AltSnap/files/9557183/AltSnap1.57test16_x64.zip)
[AltSnap1.57test16_i386.zip](https://github.com/RamonUnch/AltSnap/files/9557188/AltSnap1.57test16_i386.zip)

**Comment by Ichisich** [comment]
Perfect, test16 respects virtual desktops, the snap gap is normal again, and it can handle the terminal in regard to minimizing other windows flawlessly.

**Comment by zhichaoh** [comment]
I can confirm that latest zip (test16) solved all my issues with Windows Terminal. Actually, it is working more reliable than Win+Home  as sometimes it brings a bottom explorer window on top when reversing the "minimizing other windows". But your latest fix does not exhibit this issue. Thank you so much!
