### ISSUE TITLE
Windows Terminal Snapping Behavior

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#296]
In case `Smarter Aero Snap dimensions` is enabled, the Terminal seems to snap to invisible but deterministically drawn edges:

https://user-images.githubusercontent.com/31080003/189995304-feeffe61-3d1a-4ecc-9d2a-2f4218540b33.mp4

The identify window function in the blacklist tab is unable to register any invisible process on the desktop.

**Comment by RamonUnch** [comment]
I guess I can check for the `WS_EX_NOACTIVATE` extended flag, this is I think related to #295 
Here have a try:
[hooks1.57test17_x64.zip](https://github.com/RamonUnch/AltSnap/files/9560403/hooks1.57test17_x64.zip)

It seems Windows Terminal is a running gag since Issue #11 :)

**Comment by Ichisich** [comment]
Indeed... not only in regard to AltSnap.

Test17 shows the correct snapping behavior.
Feel free to close the issue, I will reopen it in case something comes up.
