### ISSUE TITLE
How can I enable the option "scroll inactive windows"?

### ISSUE THREAD

**Issue by pityalvarez** [RamonUnch/AltSnap#299]
It's unavailable

**Comment by RamonUnch** [comment]
It is only available if you are using Windows 8.x or below.
On Windows 10 the inactives windows are scrolled by default and with this option all metro apps stop receiving scroll inputs.
If you are using a very old build of Windows 10 or really want the option to be enabled you can go to the .ini file (middle click the tray icon) and set `InactiveScroll=1` in the `[General]` section of the .ini file
