### ISSUE TITLE
Move to Zone extends the window instead when using Grid layout.

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#300]
I have found an issue related to Move to Zone (using Grid layout). If the app is in a bottom zone, hitting the keyboard shortcut to move it to the top zone, it will actually extend to that zone instead of moving. Is this intended?

_Originally posted by @zhichaoh in https://github.com/RamonUnch/AltSnap/issues/271#issuecomment-1255233194_

**Comment by RamonUnch** [comment]
It is a bug, if you use UseZones=3+4 the option should still move and not extend,
I will fix that.

Ideally it would move the window one grid step without resizing it if it is already snapped over several cells.

**Comment by RamonUnch** [comment]
[AltSnap1.57test20_x64.zip](https://github.com/RamonUnch/AltSnap/files/9627718/AltSnap1.57test20_x64.zip)
[AltSnap1.57test20_i386.zip](https://github.com/RamonUnch/AltSnap/files/9627719/AltSnap1.57test20_i386.zip)

This one should fix the problem. You need to replace both hooks.dll and AltSnap.exe
It is still not perfect, grid movement should be handled differently I think because current behavior can be annoying if grid cell is small. So more work will be needed but it will be for later.

**Comment by zhichaoh** [comment]
The fix works really well in my settings. Thank you for the immediate solution. Yes, small grids can be frustrating. I divided my 32" 4K monitor into 5x3 grids. Now I found that I have to actively move the mouse after sending it to a zone. This is because we only move windows under the mouse. Is there a way to move the active window instead so we don't have chase the window using mouse?

**Comment by RamonUnch** [comment]
Be sure to uncheck the Apply to the pointed window. (It should be off by default but I may be wrong.)
![image](https://user-images.githubusercontent.com/74856804/191814023-d4093548-f258-4163-bb1a-72d652126642.png)

**Comment by RamonUnch** [comment]
Note that this option applies to all keyboard shortcuts.

**Comment by zhichaoh** [comment]
That does the trick! Thanks!
