### ISSUE TITLE
[Question] - How can I configure a keyboard shortcut to enable/disbale AltSnap ?

### ISSUE THREAD

**Issue by eriksdev1** [RamonUnch/AltSnap#303]
Good day, I was unable to find how to enable/disable the program (usually by clicking on the taskbar) but I was wondering if a keyboard shortcut exists. Thanks.

**Comment by Ichisich** [comment]
You can Suspend/Resume AltSnap based on the scroll lock state.

The option is in the keyboard section.

**Comment by eriksdev1** [comment]
> You can Suspend/Resume AltSnap based on the scroll lock state.
> 
> The option is in the keyboard section.

Thank you, is this the only way ? If it is, well, no problem I will have to use my Fn + Scr lock keys, I hope this is configurable. Adding Image to help others find this fast:
![image](https://user-images.githubusercontent.com/45124393/192979587-5ab2da26-14eb-48aa-9bb6-6b1c2f540cc6.png)

**Comment by Ichisich** [comment]
You can also create a custom shortcut:

![Unbenannt](https://user-images.githubusercontent.com/31080003/192984868-b6583763-89fc-4783-ab2d-9f9c76bb3f14.png)

**Comment by RamonUnch** [comment]
To setup a custom keyboard shortcut, you need the latest test build. it was not yet there in v1.56.
Hopefully a new release is coming soon.

**Comment by eriksdev1** [comment]
Oh correct, I'm using 1.56 and I did not find the Suspend/Resume AltSnap action, this program is great, so thankful I found it, I was using the original but this fork is awesome. Hopefully the new version gets released without problems, this is a really useful feature (Suspend/Resume)
