### ISSUE TITLE
Move windows with keyboard

### ISSUE THREAD

**Issue by icyhoty2k** [RamonUnch/AltSnap#304]
Please add an option to move windows with keyboard shortcuts +x pixels to letft , right ,up ,down

**Comment by icyhoty2k** [comment]
I will use it extensively , and one more point , define a step in pixels(for move pixels )and if pressing shift use step x 10 (for acceleration key).

**Comment by RamonUnch** [comment]
With this one you get 8 additional keyboard actions to setup:
Step left
Step up
Step right
Step down
Small step left
Small step up
Small step right
Small step down

[AltSnap1.57test26_x643.zip](https://github.com/RamonUnch/AltSnap/files/9738997/AltSnap1.57test26_x643.zip)
[AltSnap1.57test26_i386.zip](https://github.com/RamonUnch/AltSnap/files/9738998/AltSnap1.57test26_i386.zip)

By default the steps are 100pixels and small step is 10 pixles. you can change those vales as you please with:
`KBMoveStep` and `KBMoveSStep` for step size and small step size in the [advandec section of the .ini file.
```
in the [Advanced] section.
KBMoveStep=100
KBMoveSStep=10
; Value in pixels from 1-255.
```

**Comment by icyhoty2k** [comment]
Thakns this is super

**Comment by icyhoty2k** [comment]
its working i tested it but when the window snaps , it does not work snap
it to the edges of the screen to test, down + right edge snap , and
keyboard movement is not working

**Comment by RamonUnch** [comment]
You mean the window gets stuck?
Does it happen only with the small steps?
I cannot produce, for me the window moves even after snapping it to another window or to a monitor edge.

**Comment by RamonUnch** [comment]
Does it happen when you snap to the top of the monitor and try moving down? This might be because of Win10's invisible borders and there is no invisible border at the top.

**Comment by icyhoty2k** [comment]
I try only with small steps .when i snap to the right edge  i can only move
up down and when it snaps to up or down it stops completely to move

**Comment by RamonUnch** [comment]
Does it persist if you set a very low value for SnapThreshold the default is 20, could you try with 5 or 0 (just to test).

**Comment by zhichao-h** [comment]
Great feature added! May I suggest to also support resize horizontally or vertically with keyboard shortcuts only?
