### ISSUE TITLE
Enhancement request: add 'run now' option to the installer

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RamonUnch/AltSnap#312]
Windows users tend to expect a 'run now' option within the installer - an option that, post-installation, runs the program - and such an option would be useful, especially since the installer does not place an icon on the desktop.

Thank you for your software.

EDIT: AltSnap version 1.57, running on Windows 10 Pro - 21H2 (2009: 19044).

**Comment by RamonUnch** [comment]
This would be nice indeed.

**Comment by RamonUnch** [comment]
Done on 1.58
