### ISSUE TITLE
Could the icon be improved so as to reduce confusion with the pointer?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RamonUnch/AltSnap#313]
The program's current icon somewhat encourages confusion between that icon and the pointer. For, the icon includes an image of a pointer. I know that one can hide the icon in various - but still. Perhaps the pointer image should simply be removed from the icon - leaving the crosshair image.

EDIT: AltSnap version 1.57, running on Windows 10 Pro - 21H2 (2009: 19044).

**Comment by RamonUnch** [comment]
Interesting, I am not an artist, the Icon is the same than the original AltDrag.
To me it looks quite different from the Windows default cursors because it does not have a shaft but just is an arrowhead. Also by default the window cursor is white.
It has been this tray icon for a while now, so I am not sure how to improve the icon without disturbing or annoying long time AltSnap users.

**Comment by erasmion** [comment]
I have made some icons for myself, don't know if you like them...

[alt-snap icons.zip](https://github.com/RamonUnch/AltSnap/files/10282156/alt-snap.icons.zip)

**Comment by LinuxOnTheDesktop** [comment]
@RamonUnch 

> To me it looks quite different from the Windows default cursors because it does not have a shaft but just is an arrowhead. Also by default the window cursor is white.

Good points. Perhaps no change is needed after all. If a change were desired, I did make a suggestion - namely, keep only the crosshair image.

@erasmion 

I think your icons look alright, and they seem designed to reflect different states of the program. Does the existing version of AltSnap do that? (I'm not on my Windows computer right now, so I cannot easily check.)

**Comment by erasmion** [comment]
if you right click on the tray, you will find 'disable' -  if you click the icon will turn red.

the grey one - for 'suspend' is possibly a redundancy from a previous version (like a left over from AHK).   it isn't even available in the tray menu.

**Comment by RamonUnch** [comment]
The icons should be customizable anyway, So I will add a and an option to be able to change the theme and @erasmion's theme will be an option without modifying the exe file.

**Comment by erasmion** [comment]
sounds great

**Comment by erasmion** [comment]
thanks R, will test now

**Comment by RamonUnch** [comment]
Strange, try maybe with the i386 version or AltSnap.exe, be sure to replace both AltSnap.exe and hooks.dll in AltSnap folder.

**Comment by erasmion** [comment]
tried x86 - of course all files in folder - what i get is an icon in the tray for about a second - no appearance in the task manager, as if it doesn't even load at all.

could it be something do do with some runtimes i'm missing (1.57 works fine though)?

**Comment by RamonUnch** [comment]
[AltSnap_debug_i386.zip](https://github.com/RamonUnch/AltSnap/files/10361053/AltSnap_debug_i386.zip)
Have a try with this debug build that will write a log file `ad.log`
Then show me the content of the log file

**Comment by erasmion** [comment]
here it is, same as before, starts and goes off



ALTSNAP STARTED, LastError=298
ini file: C:\AS\AltSnap.ini, LastError=0
Running with Windows version 4A64000A, LastError=0
Process started already elevated, LastError=0
Command line parameters read, hide=0, quiet=0, elevate=0, multi=0, config=0, LastError=0
No previous instance found, LastError=2
Language updated, LastError=3
Create main APP Window: Sucess, LastError=0
Register TaskbarCreated message: C0CC, LastError=0
Updating tray icon, LastError=0
Sucess at try 1, LastError=0
Going to Hook the system..., LastError=0

**Comment by RamonUnch** [comment]
OK, I got it, it was a bug int he .ini file reading procedure.
[AltSnap1.58test4_x64.zip](https://github.com/RamonUnch/AltSnap/files/10365847/AltSnap1.58test4_x64.zip)

This one should do the trick.

**Comment by erasmion** [comment]
yes, all working well.  i added theme the entry and after restarting AS the new icons show.

perhaps at some point there should be a theme entry in the ini (even if null), so that it's easier to find and edit for newcomers.

thumbsup for this one RamonUnch

**Comment by RamonUnch** [comment]
> perhaps at some point there should be a theme entry in the ini (even if null), so that it's easier to find and edit for newcomers.

There will be the option in the next default AltSnap.ini file bundled with next release.

**Comment by RamonUnch** [comment]
@erasmion, do you grant permission to include tour theme in the next release of AltSnap?
If yes, could you provide a copyrights information that would go inside your theme folder? So people know what they can do with the icons?

**Comment by erasmion** [comment]
Hi Ramon, of course.   no need for acknowledgment...   use it freely, and thanks for implementing it

**Comment by RamonUnch** [comment]
It will be in the next release then.
Thanks a lot for your contribution!
