### ISSUE TITLE
Inverted tray logo for enabled and disable state

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#315]
@RamonUnch I think this (unintentionally) inverted the tray logo for enabled and disable state

_Originally posted by @brian6932 in https://github.com/RamonUnch/AltSnap/issues/283#issuecomment-1287963168_

**Comment by RamonUnch** [comment]
I cannot reproduce this problem. Can you give any more context?

**Comment by brian6932** [comment]
https://i.alienpls.org/tLw.ini @RamonUnch this is my ini
Without scroll lock pressed: 
![image](https://user-images.githubusercontent.com/18603393/197424830-882df612-15bd-4323-8137-24c517f95cae.png)
With scroll lock pressed:
![image](https://user-images.githubusercontent.com/18603393/197424851-c6ec713b-57aa-405c-a810-81a6b6259902.png)

**Comment by RamonUnch** [comment]
Ok,I was trying enabling/disabling by a sinlge click on the tray.
Scroll lock suspend/rsume should show  a specific tray icon.

**Comment by RamonUnch** [comment]
This one should fix it:

[AltSnap_1.57fix1_x64.zip](https://github.com/RamonUnch/AltSnap/files/9850406/AltSnap_1.57fix1_x64.zip)

**Comment by brian6932** [comment]
Fixed
