### ISSUE TITLE
Resizing a window out of snap layout and then moving it reset its size to how it was before it was snapped

### ISSUE THREAD

**Issue by Susko3** [RamonUnch/AltSnap#317]
Best explained by a video:

https://user-images.githubusercontent.com/16479013/198723350-6198965c-5572-48ed-8eaa-b8e1eaf73a97.mp4

Here, I would expect the notepad window's size to remain as it was right after the <kbd>Right Click</kbd> resize.

Steps to repro:
1. Move window into snap zone by holding <kbd>\<activator key\></kbd>+<kbd>Shift</kbd>+<kbd>Left Click</kbd>
2. Resize the window with <kbd>\<activator key\></kbd>+<kbd>Right Click</kbd>
3. Move the window with <kbd>\<activator key\></kbd>+<kbd>Left Click</kbd>

**Comment by RamonUnch** [comment]
This mimics the default Snapping behavior, if you do not like this, you can disable the smarter aero-snapping option in the general tab.
If you never want AltSnapped windows to be restored to their previous size, you can also check the Never restore AltSnapped windows options in the Advanced tab.

**Comment by Susko3** [comment]
>This mimics the default Snapping behavior, if you do not like this, you can disable the smarter aero-snapping option in the general tab.

Disabling this fixes the issue I had. Cheers!
