### ISSUE TITLE
Option to disable edge resize region while keeping center region

### ISSUE THREAD

**Issue by nevubm** [RamonUnch/AltSnap#318]
With "snap to window edges", I find that I don't really use the edge resize anymore, only corner resize, so here's an idea: have an option to disable the horizontal/vertical region while keeping the center.

To give a better idea of what I mean
normal:
![normal](https://user-images.githubusercontent.com/14833020/198886824-406823bb-9d6f-4745-9552-36176bbccffc.png)
sides disabled:
![no side](https://user-images.githubusercontent.com/14833020/198886828-20e69b24-368c-4226-9c30-d868f3889708.png)

**Comment by RamonUnch** [comment]
There is no such option for the moment.
You can set the **Center fraction** to `0` in the advanced tab, but it will make 4 quadrants without a central region.
It is interesting, I will see if I can implement it.

**Comment by RamonUnch** [comment]
With this build (replace both AltSnap.exe and hooks.dll) you can configure the side fraction in the advanced tab on the first raw (Center/Side fraction).

![sidesfract](https://user-images.githubusercontent.com/74856804/198973187-59581210-a97c-46a0-965c-cd77b164a328.png)

If you set the sides fraction larger than the center fraction then it will behave as previously.
**In your case you cant to set the Sides fraction to `0`.**

[AltSnap_sidefractest_x64.zip](https://github.com/RamonUnch/AltSnap/files/9899617/AltSnap_sidefractest_x64.zip)
[AltSnap_sidefractest_i386.zip](https://github.com/RamonUnch/AltSnap/files/9899646/AltSnap_sidefractest_i386.zip)

**Comment by nevubm** [comment]
That was quick!. Yes that works great! Though I think it would make more sense if 100% meant no edge area, rather than same as center area. This would also allow you to have a decent side area even with center area disabled. See mockup:
![altsnap](https://user-images.githubusercontent.com/14833020/199120596-5210e951-408a-4e75-b8e4-886543db29c3.png)

**Comment by RamonUnch** [comment]
However I do agree that it is logical and simple to do so it will be done, just the test window will take extra time.

**Comment by RamonUnch** [comment]
[AltSnap_sidefractest2_i386.zip](https://github.com/RamonUnch/AltSnap/files/9910311/AltSnap_sidefractest2_i386.zip)
[AltSnap_sidefractest2_ix64.zip](https://github.com/RamonUnch/AltSnap/files/9910316/AltSnap_sidefractest2_ix64.zip)

This one should behave as you expect, implementation was actually quite straightforward.

**Comment by nevubm** [comment]
Amazing! I'll give it a shot
