### ISSUE TITLE
Keyboard shortcut opens the action menu at the top-left of the window on Windows 11

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#330]
I'm not sure if this is an intentional change or not, but when using the release version of AltSnap 1.57, using a keyboard shortcut to open the action menu opens it at the top-left of the window instead of at the mouse cursor. Opening the action menu with the mouse works correctly; but on my other Windows 10 computer (running some snapshot build of 1.57), opening the action menu using alt+space opens it at the mouse cursor.

![image](https://user-images.githubusercontent.com/4723091/204069620-3141487a-cf92-41bc-a04e-ff9c5cd78499.png)

**Comment by RamonUnch** [comment]
The behavior is intended and should depends on the **Apply to the pointed window** option.
If it is disabled then the action will apply to the foreground window and menu will popup in the top left corner.

**Comment by LoganDark** [comment]
But "apply to the pointed window" *is* on and it still appears in the top left corner

**Comment by RamonUnch** [comment]
Give me the ini file.
Which version are you using? be sure that both AltSnap.exe and hooks.dll are from the same version,
Try to reset the the ini file with the version that comes with AltSnap.

**Comment by LoganDark** [comment]
> Give me the ini file.

[AltSnap-bug.ini.txt](https://github.com/RamonUnch/AltSnap/files/10095903/AltSnap-bug.ini.txt)

> be sure that both AltSnap.exe and hooks.dll are from the same version,

this is a clean install using the msi

> Try to reset the the ini file with the version that comes with AltSnap.

I reset it and tried again and now it works, here is the working version

[AltSnap-work.ini.txt](https://github.com/RamonUnch/AltSnap/files/10095904/AltSnap-work.ini.txt)

**Comment by LoganDark** [comment]
I think this is a UI desync because the ini file says usepointedwindow is off, but in the screenshot it's obviously on and the save button is disabled which means it thinks it's been saved

**Comment by RamonUnch** [comment]
You can find indeed `UsePtWindow=0` in the buggy version, So it is a problem with the GUI that do not read or write properly the ini file.

**Comment by RamonUnch** [comment]
> I think this is a UI desync because the ini file says usepointedwindow is off, but in the screenshot it's obviously on and the save button is disabled which means it thinks it's been saved

Indeed as you say, Now I understand, it is indeed a UI bug.

The small save button only apply to the shortcut definition, however for this option you need to hit the global Apply button at the very bottom of the Dialog because it is a global option. Also pressing OK should work.

**Comment by LoganDark** [comment]
> The small save button only apply to the shortcut definition, however for this option you need to hit the global Apply button at the very bottom of the Dialog because it is a global option. Also pressing OK should work.

This is very unintuitive, could you try to make this more clear?

**Comment by RamonUnch** [comment]
> This is very unintuitive, could you try to make this more clear?

I will just make in sort that if you hit the small save button everything gets saved and you no longer need to also press the apply button.
