### ISSUE TITLE
Make AltSnap able to move window that comes from WSLg

### ISSUE THREAD

**Issue by philippea** [RamonUnch/AltSnap#339]
hi,
AltSnap is working fine when I want to move any native windows window (by using ALT+click)
My issue is that this does not work for window that comes from WSLg
For instance, I start a gedit from my WSL, the gedit window appears, but I cannot move it using ALT+Click, I must move it by clicking on the title bar.

It would be great if it could work from WSLg window

**Comment by RamonUnch** [comment]
Duplicate of #191
Long sorry short: When I eventually get to use more modern hardware with new Windows Version I will be able to actually try and see if it can be done. For now AltSnap is voluntarily disabled on WSLg windows because the programs freezes if moved by AltSnap.
