### ISSUE TITLE
Scroll inactive windows not working on modern Windows applications

### ISSUE THREAD

**Issue by flamingjupiter** [RamonUnch/AltSnap#351]
AltSnap breaks modern Windows apps scrolling. In my use case, I need AltSnap enabled for only two or three applications where scrolling is kinda buggy and AltSnap "fixes" it. For people like me that needs AltSnap only for specific applications it'd be much easier to have a list where you put the windows/applications where AltSnap will work and will not work with anything that's not on the list. Much faster to configure and wouldn't break scrolling on modern Windows apps as well.

**Comment by RamonUnch** [comment]
First be sure to disable *scroll inactive windows* opton that is reserved for Windows 7 and below.
Then you can turn a blaklist into a whiteist already by specifying *|* as a first element. read the wiki for more informations.

**Comment by RamonUnch** [comment]
By the way if AltSnap breaks scrolling even without the **scroll inactive windows** option, this would be a bug, and should be treated as such, so open another issue if the scrolling bug still occurs with the option disabled.

**Comment by flamingjupiter** [comment]
> First be sure to disable _scroll inactive windows_ opton that is reserved for Windows 7 and below. Then you can turn a blaklist into a whiteist already by specifying `*|*` as a first element. read the wiki for more informations.

Idk why but the application I use needs scroll inactive windows option for it to work. To work/scroll when the window is active and I'm dragging something within it. Without scroll inactive windows, it doesn't scroll. With scroll inactive windows on, I can scroll while dragging something.

**Comment by RamonUnch** [comment]
The Scroll incative window option always blocks the physical wheel input and instead directly sends the scroll message. So only normal windows programs can understand it and there is no equivalent for new Metro apps. those latter are very limited in communication.

>  With scroll inactive windows on, I can scroll while dragging something.

I did not even know this was possible, interesting, this is an involuntary side-effect of the option, logical though.
Is it possible to scroll while dragging when AltSnap is not active? in this case this would be a bug.
Otherwise I could add a blacklist specific to inactive scroll action, so that even on Win10 the option could be used.

**Comment by flamingjupiter** [comment]
> I did not even know this was possible, interesting, this is an involuntary side-effect of the option, logical though. Is it possible to scroll while dragging when AltSnap is not active? in this case this would be a bug. Otherwise I could add a blacklist specific to inactive scroll action, so that even on Win10 the option could be used.

I didn't know either, I discovered it by accident. I was using AltDrag for other things and accidentally scrolled while dragging on the application where that's not possible. I've found it to work on another one or two applications (specifically scroll inactive windows option enabling scroll while dragging), though I'm not remembering them right now. 

It's not possible to scroll while dragging if AltSnap if disabled. AltSnap has to be enabled and the scroll inactive windows option needs to be enabled. That screws Metro apps, so what I do is use my PC with AltSnap enabled and whenever I need to do more than one or two things on Metro apps I disable AltSnap, do the thing, and then re-enable it, but that's cumbersome. That's why I thought of an option to blacklist AltSnap (or AltSnap scroll inactive windows feature) for everything, and then one would pick the applications where they want scroll inactive windows to function and add to a list. 

I tried A LOT of ways to scroll while dragging on the application where I use this feature, because it's really useful sometimes. AltDrag/AltSnap scroll inactive windows option is the only one that can do it.

**Comment by RamonUnch** [comment]
I will add a Inactive scroll specific blacklist.

**Comment by RamonUnch** [comment]
[hooks_x86_64.zip](https://github.com/RamonUnch/AltSnap/files/10483971/hooks_x86_64.zip)
[hooks_i386.zip](https://github.com/RamonUnch/AltSnap/files/10483981/hooks_i386.zip)

Use this version of hooks.dll and you will have a new `IScroll` blacklist: to add in the [Blacklist] section of the .ini file.

```
IScroll=*|ApplicationFrameWindow
; List of windows on which the scroll inactive window option willnot apply.
```
You an also specify exename in the list, and you can also use it as a whitelist as usual, so you could also for instance use `IScroll=*|*,explorer.exe` to have it enabled only on explorer.exe

**Comment by flamingjupiter** [comment]
> [hooks_x86_64.zip](https://github.com/RamonUnch/AltSnap/files/10483971/hooks_x86_64.zip) [hooks_i386.zip](https://github.com/RamonUnch/AltSnap/files/10483981/hooks_i386.zip)
> 
> Use this version of hooks.dll and you will have a new `IScroll` blacklist: to add in the [Blacklist] section of the .ini file.
> 
> ```
> IScroll=*|ApplicationFrameWindow
> ; List of windows on which the scroll inactive window option will not apply.
> ```
> 
> You an also specify exename in the list, and you can also use it as a whitelist as usual, so you could also for instance use `IScroll=*|*,explorer.exe` to have it enabled only on explorer.exe
> 
> EDIT: By default I would set `*|ApplicationFrameWindow` that include most new style metro apps.

I just tested it and it's now working, thanks. I'm using it as a whitelist, since on W10/W11 you have native scroll inactive windows feature. Enabling/disabling AltSnap no more!
