### ISSUE TITLE
Middle mouse activation conflict

### ISSUE THREAD

**Issue by xeophyte** [RamonUnch/AltSnap#352]
Hi, when I use only middle mouse button to move https://i.imgur.com/uXhYAFp.png I can't close window thumbnail with it https://i.imgur.com/z8dh2pM.png because then it moves the thumbnails panel. Can it be fixed? Maybe long middle-mouse click?
Windows 11, AltSnap 1.58

**Comment by RamonUnch** [comment]
Long click should already work, try with a Browser tab.
You can also check the **Avoid blocking alt+click** option in the general tab. So Alt+Click or Hotclick will be forwarded on middle click release, without having to wait for delay.

**Comment by xeophyte** [comment]
Thanks, Avoid blocking alt+click solved the problem, however windows close slower now, there is a half second delay.

**Comment by RamonUnch** [comment]
Windows 10 always has it weirdness, I will see what I can do for the delay, but I cannot run Win10 so I have to work blind.
In the meantime I advise you to blacklist the windows thumbnails, If you manage to find their window calss, I guess you can try with AutoHotkey's Win Spy.

**Comment by RamonUnch** [comment]
[hooks1.59test2_x86_64.zip](https://github.com/RamonUnch/AltSnap/files/10497393/hooks1.59test2_x86_64.zip)
Tell me if this one gives you the same problem.

**Comment by Ichisich** [comment]
The class is `TaskListThumbnailWnd`

@xeophyte 
So the entry would be `, *|TaskListThumbnailWnd` in the Windows Blacklist.

@RamonUnch 
If there is not one use case, and I can't think of one, blacklisting the thumbnails should be default in coming versions.

**Comment by RamonUnch** [comment]
>  If there is not one use case, and I can't think of one, blacklisting the thumbnails should be default in coming versions.

I agree 100%
Also I hope more things will be easily blacklistable because now the full blacklist format can include exename, so there is no more process specific blacklists.

**Comment by xeophyte** [comment]
Ok I disabled `Avoid blocking alt+click` and added `, *|TaskListThumbnailWnd` to the windows blacklist and it's working properly. Windows thumbnails can be closed and explorer doesn't broke, at least for now, thanks.
`hooks1.59test2_x86_64.zip` also solves the problem - no need to add `, *|TaskListThumbnailWnd`, but have to enable `Avoid blocking alt+click`.
However I still have problem with other apps, like Image Viewer or Notepad++. In Notepad++ I can't close tabs or can, but with the delay. Above solutions don't work anymore or I don't know how to do it.

**Comment by RamonUnch** [comment]
So You mean the delay is gone only for the thumbnail but not for other windows?
This is quite strange, I would expect the delay to be there all the time or never regardless of the application. If the application is blacklisted, there is no way to be any delay because AltSnap will not interact.

**Comment by xeophyte** [comment]
Yes, something like that. I'll describe it other way. Settings:
test `hooks.dll` applied, `Middle mouse button` enabled, `Avoid blocking alt+click` enabled, `, *|TaskListThumbnailWnd` added or not
blacklists:
- StartMenuExperienceHost.exe,SearchApp.exe,osk.exe,Virtual PC.exe,anydesk.exe
- Program Manager|Progman,*|MultitaskingViewFrame,Volume Control|Tray Volume,Volume Control|Windows.UI.Core.CoreWindow,*|TaskSwitcherWnd,*|TaskSwitcherOverlayWnd,|WorkerW,|Shell_TrayWnd,|BaseBar,|#32768,*|XamlExplorerHostIslandWindow,*|TSSHELLWND,|MozillaDropShadowWindowClass,*|RAIL_WINDOW,VistaSwitcher|VistaSwitcher_SwitcherWnd

Results:
- explorer thumbnails: closing instantly
- notepad tabs: most close with delay, some instantly
- fullscreen/exit previews in FastStone: half delay, half instantly

But I also noticed (looks like cause of problems for me) that when `Disable AltSnap on Maximized windows` is enabled and I maximize notepad or faststone windows (with the above settings) it works ok - no delays on maximized windows.
When I disable `Disable AltSnap on Maximized windows` there is a delay in normal and maximized windows.
However I'd like to have this option enabled.

**Comment by RamonUnch** [comment]
> But I also noticed (looks like cause of problems for me) that when Disable AltSnap on Maximized windows is enabled and I maximize notepad or faststone windows (with the above settings) it works ok - no delays on maximized windows.

Again expected, because AltSnap does not interact with maximized window with this option enabled, so it is consistent.
> Results:
>   * explorer thumbnails: closing instantly
 >  * notepad tabs: most close with delay, some instantly
  > * fullscreen/exit previews in FastStone: half delay, half instantly

Thanks for confirmation, I will try more things. to solve the delay issue.

**Comment by RamonUnch** [comment]
[hooks1.59test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/10503875/hooks1.59test3_x64.zip)
Try again with this one (odds are small but who knows...)

**Comment by xeophyte** [comment]
It's working, with `Disable AltSnap on Maximized windows` enabled or disabled, at least with all mentioned cases and without delay, thanks again.
Btw, could you add remembering of the position of the settings window? I always move it from the bottom right corner.

**Comment by RamonUnch** [comment]
> It's working, with Disable AltSnap on Maximized windows enabled or disabled, at least with all mentioned cases and without delay, thanks again.

Nice to see it working...

>  Btw, could you add remembering of the position of the settings window? I always move it from the bottom right corner.

This is in my plans to improve dialog position indeed but priority is low because config dialog is something on which people usually do not go very often, at least once they have found a good workflow. see issue #314.

**Comment by RamonUnch** [comment]
1.59 released.
I know there can still be locks even with this patch so if you find a consistent way to reproduce, open a new issue.
