### ISSUE TITLE
Drag/Move Wheel Actions

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#362]
https://github.com/RamonUnch/AltSnap/issues/232#issuecomment-1426996783
> Indeed could be nice, but I was more thinking about Using the mouse wheel while in Snap to zone mode, like this people that you can go next/previous layout.

In light of this, I would suggest expanding the drag-free actions to mouse wheel actions, but without the "free" limitation.

e.g. 
Wheel while move: `Zoom Window`
Wheel while resize: `Roll/Unroll Window`

**Comment by RamonUnch** [comment]
I should rather generalize click combo action so that Any button can be mapped to a new action if we are within a movement or resize.

I will start with generalizing the Wheel action on move/resize.

**Comment by Ichisich** [comment]
> As soon as you start the extra action, movement gets locked and you have to release before being able to drag again.
Is this a technical limitation or by design?

**Comment by RamonUnch** [comment]
It is a bit of both, It would be perfectly possible not to lock the window, but then it becomes quite quirky and more work would be needed to handle it properly.

**Comment by Ichisich** [comment]
It depends on the action. 
Transparency/Unroll/NPStacked would be better off without stopping moving/resizing.

BTW, the action combo ScrollM=NPStacked is quite nifty.
As you can quickly switch the focused window while moving it.
Although the laser variation would be even better as the mouse courser is the primary focus point during a move action.

**Comment by RamonUnch** [comment]
Indeed there is no Next/Previous stacked window laser mode, it is an oversight, I will add that (easy).

As long as the combo action does not change the size of the window it should not add any quirk not to disable movement, so I might do that as well.

**Comment by RamonUnch** [comment]
This build tries to be smarter and locks movement only for some specific actions, namely those that can move/resize the window and those that can minimize/close it, or that pop up a new menu
Also fixes the laser stack action: `NPStacked2` = Next/Perv laser stacked window.

When the Move action is not locked, moving will always move the initial window, doing otherwise would be tricky and would require too much specific code to to handle it.

[AltSnap1.59test6_x64.zip](https://github.com/RamonUnch/AltSnap/files/10725483/AltSnap1.59test6_x64.zip)
[AltSnap1.59test6_i386.zip](https://github.com/RamonUnch/AltSnap/files/10725476/AltSnap1.59test6_i386.zip)

**Comment by Ichisich** [comment]
Works great so far.

The only bug I could detect is that the drag-free actions are broken (test5 and test6).

**Comment by RamonUnch** [comment]
indeed, I forgot to update this part with the new action system, same for GrabWithAlt stuff.
[AltSnap1.59test7_x64.zip](https://github.com/RamonUnch/AltSnap/files/10725797/AltSnap1.59test7_x64.zip)
[AltSnap1.59test7_i386.zip](https://github.com/RamonUnch/AltSnap/files/10725798/AltSnap1.59test7_i386.zip)

**Comment by Ichisich** [comment]
When using a while action without moving/resizing the window, a drag-free action will be triggered afterward.
Not sure if this desirable or not.

**Comment by RamonUnch** [comment]
> When using a while action without moving/resizing the window, a drag-free action will be triggered afterward.
Not sure if this desirable or not.

This is indeed an oversight, I think it is undesirable, and drag-free action should only trigger if no other cation was done in the meantime.

**Comment by RamonUnch** [comment]
This one should fix it.

[AltSnap1.59test16_x64.zip](https://github.com/RamonUnch/AltSnap/files/10756683/AltSnap1.59test16_x64.zip)

**Comment by zhichaoh** [comment]
Love the additional support! Unfortunately, I found with AltSnap1.59test16_x64.zip, the command line option "-af" no longer triggers. Can you please confirm?

**Comment by RamonUnch** [comment]
> I found with AltSnap1.59test16_x64.zip, the command line option "-af" no longer triggers. Can you please confirm?

For me it works just fine, both `-af` and `-ap`, maybe you have a specific command in mind?

**Comment by zhichaoh** [comment]
I figured out why. I launched AltSnap elevated. But the ahk script that triggers the action is not running from an elevated script/session. Once I elevated the ahk script, the command line option works like before. Sorry for the false alarm.

**Comment by RamonUnch** [comment]
No problems, it is still informative, I will keep this in mind if someone else gets the problem.
