### ISSUE TITLE
Hide tray on startup

### ISSUE THREAD

**Issue by redsigma** [RamonUnch/AltSnap#370]
I am using the portable version of this tool. I am launching at windows startup by placing a shortcut in `shell:startup` and it works fine.

However I would like to hide it from the tray. I know there is an option in the config file called `AlwaysElevate` . Would it be possible to also add an option call `AlwaysHideTray` or something like that ?

**Comment by RamonUnch** [comment]
You can hide the tray with the -h command line at AltSnap startup;
Go to the properties of the shortcut, and add at the very end of the target field the `-h` option, (after the quotation mark).

`"C:\my\path\to\AltSnap.exe" -h`

You can also use (and combine) with `-e` to elevate. the `AlwaysElevate` option is inherited from AltDrag but it is actually not needed.

**Comment by redsigma** [comment]
> You can hide the tray with the -h command line at AltSnap startup; Go to the properties of the shortcut, and add at the very end of the target field the `-h` option, (after the quotation mark).
> 
> `"C:\my\path\to\AltSnap.exe" -h`
> 
> You can also use (and combine) with `-e` to elevate. the `AlwaysElevate` option is inherited from AltDrag but it is actually not needed.

Thank you, that did the job. I am not sure if this is documented (maybe I missed it). I tried to launch `AltSnap.exe --help` to see if there were any command lines but it didn't show anything.

**Comment by RamonUnch** [comment]
> Thank you, that did the job. I am not sure if this is documented (maybe I missed it). I tried to launch AltSnap.exe --help to see if there were any command lines but it didn't show anything.

It is indeed not documented in the wiki, I should add it, It was in the original AltDrag doc by Stefan Sundin.

Plus `AltSnap --help` should indeed display the option list...
