### ISSUE TITLE
P/NStacked Keyboard Shortcuts

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#372]
Both Shortcuts currently need the mouse pointer to be in the window space to work.
The `Apply to the pointed window` setting is disabled.

**Comment by RamonUnch** [comment]
It is one of the limitations of the algorithm (depends on cursor position to know which stacked window should be selected.
This can be improved upon for sure.

**Comment by RamonUnch** [comment]
[AltSnap1.59test22_x64.zip](https://github.com/RamonUnch/AltSnap/files/10787972/AltSnap1.59test22_x64.zip)

This one should fix it.
I think other actions are OK in this regard, or they make no sense without the cursor position.
