### ISSUE TITLE
LMB sometimes not working properly

### ISSUE THREAD

**Issue by xeophyte** [RamonUnch/AltSnap#388]
After updating to 1.59 I'm having weird left-click issues. Sometimes a single click works as a double click, sometimes it doesn't work at all. Sometimes it happens for no reason and sometimes after pressing the middle button. The problem goes away immediately after disabling AltSnap. A little hard to reproduce. My settings:
https://i.imgur.com/G6hgEKg.png
https://i.imgur.com/f774ljr.png
https://i.imgur.com/yYQlYgo.png
https://i.imgur.com/75lFrJw.png

**Comment by RamonUnch** [comment]
I would prefer to have a copy of your AltSnap.ini file (you can zip it and attach it to a post).
I also need a sequence of actions that triggers the issue, otherwise I will probably be unable to reproduce.

**Comment by RamonUnch** [comment]
Also try to set `AblockHotclick=1` in the [Advanced] section of the ini file, it might help, in theory in your case it should change nothing, because you combined MMB hotclick with the Move action.

**Comment by xeophyte** [comment]
`AblockHotclick=1` doesn't fix it.
I don't know how to reproduce it yet. So far it seems to be a random occurrence, I don't know what it depends on yet.
I just noticed that the problem goes away when I disable `Middle mouse button` option.
[AltSnap.zip](https://github.com/RamonUnch/AltSnap/files/10991015/AltSnap.zip)
ini file attached.

**Comment by RamonUnch** [comment]
>  I just noticed that the problem goes away when I disable `Middle mouse` button option.

It is indeed a quite intrusive option, I will try to see how different the behavior should be from 1.58

**Comment by RamonUnch** [comment]
Thanks a lot for the ini file, I will try my best to reproduce your issue whenever I got time.

Note that the Polish translation is quite incomplete (and was not updated since AltDrag1.0) we are looking for translators, If you want to contribute with the translation I would be grateful and probably many users as well, Improving a translation is a simple matter of editing a text file see #35

**Comment by RamonUnch** [comment]
It seems that you never use the Alt activation key, so I guess you can safely disable left and right Alt keys in the Hotkeys section of the Keyboard tab. It will probably not fix anything but it will be even less intrusive.

**Comment by xeophyte** [comment]
1. Sorry, I was wrong, it is not connected to `Middle mouse button` option. When I disabled it, I click apply. The problem just sometimes goes away when I change something in the settings and click apply, no matter what, it's just about applying.
2. So far, I could only reproduce it like this:
https://i.imgur.com/cnoQozO.gifv
I also noticed that when the AltSnap is enabled and the problem does not occur I can't close tabs in Notepad++, but when the problem occurs, I can do it. Maybe some connection to https://github.com/RamonUnch/AltSnap/issues/352?
3. polish translation attached
[pl_PL.zip](https://github.com/RamonUnch/AltSnap/files/10995526/pl_PL.zip)

**Comment by RamonUnch** [comment]
Thanks for the info and espacially thanks for the translation!

**Comment by RamonUnch** [comment]
I am unsure of when the issue started to occur.
If I understand correctly, on **1.58**, there was this delay problem, then you were using **1.59test3** and you had zero issues, but when updating to the final **1.59** then this locking problem started to occur?

Could you double check to see if you are still able to reproduce the issue with the test3 build.
[hooks1.59test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/10503875/hooks1.59test3_x64.zip)

If you have no problems with the **1.59test3** (which should be the case from what you said) then this reduces the scope on which I have to search.

**Comment by xeophyte** [comment]
> If I understand correctly, on **1.58**, there was this delay problem, then you were using **1.59test3** and you had zero issues, but when updating to the final **1.59** then this locking problem started to occur?

Yes.
> Could you double check to see if you are still able to reproduce the issue with the test3 build.

No problem with test3 build when I reproduce it my way (disable->enable AltSnap, then single-click on the text in the notepad, repeat disabling->enabling until a single click selects the text - behaves as double-click, the problem occurs within a maximum of a few tries).

Going back to 1.59 hooks.dll, I deleted my AltSnap.ini, turned on the program and new default ini was created, then I gradually added my settings. It turned out, that only `Middle mouse button` enabled causes this. ini files attached.

I also noticed that when the problem occurs the long single-click is ok, it doesn't act like double-click. For example, long LMB press on the text doesn't select it.

[AltSnapINIwithAndWithoutProblem.zip](https://github.com/RamonUnch/AltSnap/files/11006755/AltSnapINIwithAndWithoutProblem.zip)

**Comment by RamonUnch** [comment]
I think I got an idea (unsure), try this one:
[AltSnap1.59fix2_x64.zip](https://github.com/RamonUnch/AltSnap/files/11006821/AltSnap1.59fix2_x64.zip)
I will go to sleep anyway now.

**Comment by RamonUnch** [comment]
I got another idea of why this bug might occur, have a try with this one:
[AltSnap1.59fix3_x64.zip](https://github.com/RamonUnch/AltSnap/files/11007795/AltSnap1.59fix3_x64.zip)

**Comment by xeophyte** [comment]
fix2 not working.
fix3 seems to work without problems, I'll leave it and test it.
I'm also wondering if it has something to do with the system version.

**Comment by RamonUnch** [comment]
>  I'm also wondering if it has something to do with the system version.

It does depends on the Windows version, Newer Windows are less forgiving to inconsistent key states.
It was due to some drag threshold not measured the same at two different places.

**Comment by RamonUnch** [comment]
does the [AltSnap1.59fix3_x64.zip](https://github.com/RamonUnch/AltSnap/files/11007795/AltSnap1.59fix3_x64.zip) fixes it for you?

**Comment by Kostrol** [comment]
> I got another idea of why this bug might occur, have a try with this one: [AltSnap1.59fix3_x64.zip](https://github.com/RamonUnch/AltSnap/files/11007795/AltSnap1.59fix3_x64.zip)

Yes, I have this in use currently. So far this version seems to have helped a lot with limited testing, does not seem to break anything that I can notice with normal use.. however it does still register double clicks with the testing method i was using earlier, but it doesn't cause any conflict with desktop like it was.

**Comment by xeophyte** [comment]
Same here, I don't see any problems with normal use. However, on the mousetester.com, double clicks (both LMB and RMB) appear, but only when I start clicking immediately after pressing MMB. When I click LMB/RMB, for example, after a second, the clicks are not registered as double. Of course Win 11 here.

**Comment by RamonUnch** [comment]
Could you give me a copy of your .ini file (you can zip it and attach to a post), I want to easily load it for myself.

**Comment by RamonUnch** [comment]
I think I got it.
[hooks1.59fix5_x64.zip](https://github.com/RamonUnch/AltSnap/files/11009470/hooks1.59fix5_x64.zip)

**Comment by Kostrol** [comment]
That seems to have done it, no more double clicks with the test with this v5 fix for me. 

> I think I got it. [hooks1.59fix5_x64.zip](https://github.com/RamonUnch/AltSnap/files/11009470/hooks1.59fix5_x64.zip)

**Comment by xeophyte** [comment]
Looks fixed to me too, thanks.
