### ISSUE TITLE
Long drag-free move/resize not working

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#392]
Got it. However I cannot activate this functionality (1.59, win11) -- nothing happens if I alt-click and hold, and release.

I do see the mouse pointer blink if I long click any title bar (but still, nothing happens).

https://github.com/RamonUnch/AltSnap/pull/391

_Originally posted by @yatli in https://github.com/RamonUnch/AltSnap/issues/35#issuecomment-1471508812_

**Comment by RamonUnch** [comment]
This is strange, @yatli Could you give me a copy of your ini file? because I cannot reproduce (not using Win11 however).

Also you can try to set `DragThreshold=2` or `3`, because otherwise, the least amount of movement will prevent the action and this can be difficult not to move at all with some setups.

```
in the [Advanced] section
DragThreshold=1
; Require a small drag before actually starting a movement.
; Set to 0 to disable (like for AtSnap 1.58 and below)
; Set to 1 to have a drag threshold for maximized/snapped windows only (default).
; Set to 2 to always have a drag threshold.
; Set to 3 to have a drag threshold even when resizing the window.
```

**Comment by yatli** [comment]
Setting the drag threshold to 1 solves the problem.

**Comment by RamonUnch** [comment]
> Setting the drag threshold to 1 solves the problem -- this entry was missing from my ini file.

I will investigate, In theory `DragThreshold=1` should not affect non-snapped windows and it should not be required for drag-free actions.

**Comment by yatli** [comment]
`DragThreshold=1` has a side effect that a maximized window cannot be moved anymore.
Quick guess: maximized window is fixed and thus cannot overcome the threshold?
Resize does work.

**Comment by RamonUnch** [comment]
It is very strange, because the mouse position is used to detect the threshold, not the window movement
I cannot reproduce the issue either. Are you sure that the **Disable on Maximized windows** is not set?

Also maybe try with this test build that fixes some other bugs that might be related in the end.
[AltSnap1.60test2.zip](https://github.com/RamonUnch/AltSnap/files/11012096/AltSnap1.60test2.zip)

**Comment by yatli** [comment]
When I comment out the threshold option and reload config (disable & enable AltSnap), maximized windows can be moved.

I'll test that build later.

**Comment by yatli** [comment]
The test build fixed it. Amazing.

**Comment by RamonUnch** [comment]
Very happy to hear that.
I will make a release soon because there are significant bugs in 1.59 indeed.

**Comment by RamonUnch** [comment]
1.60 released
