### ISSUE TITLE
[Feature Request] Zones >> Use center most zone when overlapping

### ISSUE THREAD

**Issue by weaverinva** [RamonUnch/AltSnap#405]
Hello there.  Great great product. Thank you for your service to the community.

I would rather use this than FancyZones. The idea to use the Test windows works well to save a layout.....

However, when I use overlapping windows, the choser gets confused. It wants to combine multiple zones. Could this be configurable in the .ini?  I would like it to chose the center most test windows from my mouse cursor and only join two or more if it is center most for those zones.  It would require some triangulation but would really work well when I want top and bottom, four corners, and two central on the same monitor.  I can do this with fancyzones.

Thank you for considering.
<img width="859" alt="Snag_db19c8" src="https://user-images.githubusercontent.com/60267438/226965788-fcbf158c-876b-4e43-bb77-e839e9010497.png">

**Comment by RamonUnch** [comment]
Ok, I see what you mean actually you were taking about overlapping zones, this is an interesting concept on which I did not work.

It should not be hard to implement indeed, I will see what I can do after the next stable release.

**Comment by weaverinva** [comment]
You are great!  Thank you for considering!  I am an efficiency guy and I
want a number of zones for flex on the same screen.

Right now, I have to have at least some section of the screen that each
zone has no multilayer depth on. Otherwise, I cannot select that zone.  I
was trying by leaving my four corners layer with gaps in the top and lower
center.

Thank you for all your efforts.

Peace.

**Comment by RamonUnch** [comment]
Actually implementation is straightforward so I added already an option:

Add this option in In the `[Zones]` section:
```
ZSnapMode=1
; Zone snapping strategy
; Set to 0 to snap to the zones pointed by the cursor (default).
; Set to 1 to snap to the zone which center is the nearest from the cursor
```
There is always an interzone tolerance to allow to snap to two zones but in your specific case it might be useless.
Use this build of AltSnap.exe+hooks.dll (quit altsnap and replace the old files).

[AltSnap1.60rc2_x64.zip](https://github.com/RamonUnch/AltSnap/files/11044183/AltSnap1.60rc2_x64.zip)

**Comment by weaverinva** [comment]
You are great!  I will download and try it!

Thank you kindly.

**Comment by weaverinva** [comment]
Hello, this is not working. I created 12 windows on with test window and
saved.  That is in the ini but the drag is not honoring it.

Also, what is layoutzones=0?  I got rid of that.

Only my last two zones show to snap to....

Peace.

**Comment by RamonUnch** [comment]
Use this one, it might fix your issue.

[AltSnap1.60rc3_x64.zip](https://github.com/RamonUnch/AltSnap/files/11049290/AltSnap1.60rc3_x64.zip)

Also be sure not to set a too large value to InterZone because the new strategy has a way to use the value that is slightly different.

**Comment by weaverinva** [comment]
I will try this one rc3.  I did have interzone at 127 and now 75 I think.

**Comment by weaverinva** [comment]
Oh dear, Alt key is not working at all with 60rc3.

**Comment by RamonUnch** [comment]
Could you give more details?
I am unable to reproduce, obviously!
Could you give a copy of your ini file?
You can zip it and attach it in a post.

**Comment by weaverinva** [comment]
So sorry. I thought I put the ini in the one of the last 2 emails......

**Comment by weaverinva** [comment]
Hello RamonUnch/AltSnap,

It is working now!!!  Not sure...I unchecked saved and checked a configure
setting and now working nicely.  Well done there!!!

Thank you.

Mike

**Comment by weaverinva** [comment]
Hello there,

It is working pretty well at this point.  It does get confused a bit with
overlapping test windows. If there are several, I have 10 on one screen, it
wants to create a together snap zone from the top to the bottom of the
screen.

Interesting.....

**Comment by weaverinva** [comment]
An enhancement request....

Could you add another tray menu option to create and show the existing test
windows, so that then a person could add or delete and then save?

I now have 16-18 test windows to create.

I understand if you would not.

Peace.

Mike

**Comment by RamonUnch** [comment]
If it tend to snap to too many zones at tye same time, decrease again the InterZone value, setting it to 0 mean that the window will snap to only one zone which is probably whet you want if you use may overlapping zones.

**Comment by weaverinva** [comment]
Thank you.

**Comment by RamonUnch** [comment]
1.60 is released (same than rc3)
