### ISSUE TITLE
Window snap to edges while moving without modifier hotkeys

### ISSUE THREAD

**Issue by sound8** [RamonUnch/AltSnap#418]
First off thank you so much for keeping this project going and for all the contributions made to it.

Question / Feature Request if does not exist.
Noticed that you can setup current window edges to snap to screen edges / other windows edges when moving using Alt + LMB drag.  Was wondering if there is a setting in which you can also allow this to occur just by dragging a window using only LMB drag (no modifier hotkeys needed)?

New to the program, I apologize if I have overlooked this feature / ablilty.
Thanks again

**Comment by Ichisich** [comment]
Mouse Tab-> Mouse Actions-> Title bar-> Left Mouse Button-> Move Window.

Or

Mouse Tab-> Activate with click-> Move windows with a long left-lcik

**Comment by RamonUnch** [comment]
It is possible but via a combination of settings.
You can setup an action to occur when clicking into the title-bar, even without the activation key.

So you can go to the **Mouse** tab and check the *Use specific actions when clicking the title bar* **[X] Without hotkey**
Then select the **Title bar** radio button at the top and set **Move Window** for the Left mouse button.

**Comment by sound8** [comment]
Thank you guys so much for your responses.
I saw the titlebar option but overlooked it because it was greyed out, activating it with the check box and the apply button was it.
Works great, discovered so many other great features while playing around as well.
I love programs like this that have tons of settings because everyone has different needs, really great stuff, thanks again.
