### ISSUE TITLE
Actions Without Click Send "Ctrl + w"

### ISSUE THREAD

**Issue by icyhoty2k** [RamonUnch/AltSnap#422]
Can you make altSnap Send Keyboard combinations like Ctrl+w(close tab) in chrome and most apps ?
I need to close tabs when pressing only modifier keys

**Comment by RamonUnch** [comment]
It is not possible for now. At some point I plan to add a send key sequence action, but it starts to be outside of the scope of AltSnap that is not designed to be a key remapper.

Related #205,

**Comment by icyhoty2k** [comment]
Can i send end key a key combination two or more keys , from my understanding this key is send after alt snap finishes

**Comment by RamonUnch** [comment]
The EndSendKey is a single vKey that is sent at the end of a movement. The only purpose of the `EndSendKey` is to prevent Menu selection because of Alt or Start menu poping up because of Winkey so it is only sent if a movement occurred (Move or resize) AND if the movement was triggered via a hotkey (Alt or WinKey). It was previously hard-coded to Ctrl in the original AltDrag, but it is not possible to use it to send a key sequence, and it would not be the place to do it either.

What you actually would want is simply to add a new action with that would send a customizable key sequence.

**Comment by emvaized** [comment]
@RamonUnch 
Is it possible to send "Forward" action, identical to "forward" mouse button? 

I remapped this button to serve as Alt when pressed down, and now wondering if it's regular functionality could be restored on the button release using Action Without Click option. I tried setting `GrabWithAlt` to `A7` (VK_BROWSER_FORWARD action from [the list](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)), but it seems to not working

**Comment by RamonUnch** [comment]
> Is it possible to send "Forward" action, identical to "forward" mouse button?

Not for now,  beware that the mouse buttons 4 and 5 are used as forward / backward but they are not the same than the keyboard's versions `VK_BROWSER_FORWARD/BACKWARD`.


> I remapped this button to serve as Alt when pressed down, and now wondering if it's regular functionality could be restored on the button release using Action Without Click option. I tried setting `GrabWithAlt` to `A7` (VK_BROWSER_FORWARD action from [the list](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)), but it seems to not working

GrabWithAlt can only contain an action, vkCodes are not valid actions.

However even it it was true, as soon as you remap a key AltSnap will no longer hear the key itself it will hear Alt instead, in the same manner when AltSnap tries to send a key that is remapped, then the key will get converted by the re-mapper and any program having the keyboard focus will hear the translated key instead. So your are kinda blocked in this case.

Until more work is done, you are out of luck. You can ask AltSnap to listen to any key other than Alt as a hotkey, however if you use `VK_BROWSER_FORWARD` then the key will still be sent to the program which you probably do not want.

**Comment by emvaized** [comment]
Okay, I got it, thanks

**Comment by RamonUnch** [comment]
You can look at #492 to make an action that sends arbitrary key sequence.
