### ISSUE TITLE
How to silently install to the program files folder?

### ISSUE THREAD

**Issue by IRainman** [RamonUnch/AltSnap#424]
Hello, I try to silently install utility to the program files, but it's not working. Can I fix that behavior?
```
@echo off

cd /D %~dp0

set AltSnap_VERSION=1.60

echo AltSnap installation begin...

if %PROCESSOR_ARCHITECTURE% == AMD64 (
	set AltSnap_PLATFORM_ADD=-x64
) else (
	set AltSnap_PLATFORM_ADD=
)

AltSnap%AltSnap_VERSION%%AltSnap_PLATFORM_ADD%-inst.exe /S /D %ProgramFiles%\AltSnap

echo AltSnap installation end.
```

I use documentation for NSIS framework from [here](https://www.exemsi.com/documentation/installer-frameworks/nsis-nullsoft-scriptable-install-system/)

**Comment by RamonUnch** [comment]
Actually you need to specify the = after the `/D` parameter.
I looked it up in the local doc from the NSIS version I am using so it might have been improved lately.
`AltSnap1.60-installer.exe /S /D=C:\Program Files\AltSnap`
Works for me.

**Comment by IRainman** [comment]
Thank you very much
