### ISSUE TITLE
Keybinds do not work when running as administrator on a standard account

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#428]
If my user is a standard account, and I use a User Account Control elevation prompt to run AltSnap as an administrator account, keybinds do not work.

The mouse hook (alt+ drag) works perfectly, but the keybind I have set to open the action menu does not work.

The tray icon still shows up, the configuration interface works fine, but the keybind does not work.

If I make my account an administrator and elevate AltSnap on my own account, the keybinds start working again. But they do not work if I run it using a different administrator account.

AltSnap should probably [prepare for being operable by a standard user](https://www.youtube.com/watch?v=8T6ClX-y2AE) as that is the direction that Windows 11 seems to be officially heading.

**Comment by RamonUnch** [comment]
[AltSnap1.61test4.zip](https://github.com/RamonUnch/AltSnap/files/11340518/AltSnap1.61test4.zip)

Try this version of AltSnap.
This is pure guesswork, it is untested on Windows 11.

**Comment by RamonUnch** [comment]
@LoganDark 
Does the above build fixes the issue for you?

**Comment by LoganDark** [comment]
> @LoganDark Does the above build fixes the issue for you?

I intend to test it as soon as I have time

**Comment by LoganDark** [comment]
> [AltSnap1.61test4.zip](https://github.com/RamonUnch/AltSnap/files/11340518/AltSnap1.61test4.zip)
> 
> Try this version of AltSnap. This is pure guesswork, it is untested on Windows 11.

That fixed the issue, thank you!!
