### ISSUE TITLE
SimpleWindowSwitcher's alt tab replacer should probably be in `Blacklist.Windows` of the `.ini` by default

### ISSUE THREAD

**Issue by brian6932** [RamonUnch/AltSnap#435]
Apart of https://github.com/valinet/ExplorerPatcher
More details https://github.com/valinet/sws

**Comment by RamonUnch** [comment]
Could you share the blacklist entry? I do not use SimpleWindowSwitcher.

In general the TAB key (`09`) should be in the kill key list, thus Alt+Tab will disable AltDrag Anyway whatever the AltTab replacement window.

**Comment by brian6932** [comment]
Well when you use a mouse with alt tab, you're releasing off tab so you can actually just see the menu, so it won't disable AltSnap. I wasn't sure how to blacklist it, which is kinda why I made an issue as opposed to a PR.

**Comment by RamonUnch** [comment]
I will see if I can install it and check, (using AHK's Window Spy with the Follow Mouse option should probably do the trick).

**Comment by brian6932** [comment]
I tried to `tasklist /v /fo list` with a timeout and holding alt tab open, and then diffing one without, but didn't see any new window titles

**Comment by RamonUnch** [comment]
Maybe the AltTab window is elevated and thus will be listed only to an elevated command prompt?

**Comment by RamonUnch** [comment]
From reading the sws source, it seems that the blacklist item should be:
`*|SimpleWindowSwitcher_{BEA057BB-66C7-4758-A610-FAE6013E9F98}`

**Comment by brian6932** [comment]
yep works for me, nice
