### ISSUE TITLE
v1.60 will not install or run on my computer

### ISSUE THREAD

**Issue by jacksonmacd** [RamonUnch/AltSnap#438]
Saw this utility featured on AskWoody.com.   It sounds like a great utility, but it will not run on my desktop computer (Win 11). After double-clicking the EXE, neither the installation program nor the portable version gave any indication of running. Nothing in the system tray, no warning from Windows Defender. Nada. Tried on my Win10 laptop, and it worked exactly as expected. 

Tried installing v1.57 through 1.60, all with the same result.

I am stumped. Any advice how to determine what’s blocking it from running?

**Comment by RamonUnch** [comment]
There are several people that have been using AltSnap on Windows 11 successfully so for sure something can be done about it.

I think on Win11 there is a setting to allow only signed applications and/or only store applications to run, this might be the problem, Have a look at the **Settings->Apps->Choose where to get apps** and set it to "Anywhere" (I saw this online), I am not sure this is the problem though, I would have expected a warning from Windows.
Also another place to look would be AppLocker that should be by shipped with the Pro Windows versions, there may be some settings that blocks unsigned exe that are enabled. I am quite unfamiliar with newer Windows versions.

Also I do not have an ARM build of AltSnap so if you got an ARM PC it will not run but very few PCs use ARM.
If none of this work, then I do not know what to recommend, I would suggest you try to run also the original [AltDrag](https://github.com/stefansundin/altdrag).

**Comment by Ichisich** [comment]
Additionally, to what Ramon suggested, you can add AltSnap to your security exclusion list:
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#ID0EBF=Windows_11

Sometimes the Windows defender isn't as clear in its feedback as one wishes.

**Comment by RamonUnch** [comment]
Without feedback for a few months I close the issue.
Feel free to re-open and comment if needed.
