### ISSUE TITLE
Maximized into Snap is misaligned

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#445]
![maximised](https://github.com/RamonUnch/AltSnap/assets/31080003/2e0a92e5-4b33-4eb0-ae35-b611eb522225)

![snapped 1](https://github.com/RamonUnch/AltSnap/assets/31080003/c4505b36-2529-4a0e-9ea7-2fcea4bf1be5)

The window keeps its slightly smaller title bar from the maximized state and gets cropped as a result.
The desired outcome would look like this:
![snapped 2](https://github.com/RamonUnch/AltSnap/assets/31080003/91a4de21-c94e-411a-b28b-469882a8dff5)

It seems Altsnap's WinRestore command only changes the flag but not the dimensions before snapping the window.

**Comment by Ichisich** [comment]
Most likely the same issue.

Dragging a window out of the maximized state doesn't restore the proper borders.
https://github.com/RamonUnch/AltSnap/assets/31080003/ee7c33d6-3f0a-4250-a518-c0a6ced82e62

Snapping to the taskbar out of the maximized state -> the blue border disappears
Snapping to the taskbar from a windowed state -> the blue border aligns perfectly

**Comment by RamonUnch** [comment]
The invisible borders change size when the window is maximized So I should check them again after restoring the window. This should not be hard to fix.

**Comment by RamonUnch** [comment]
OK, I was focused on other things, This one should do the trick.
[AltSnap1.62_test3_x64.zip](https://github.com/RamonUnch/AltSnap/files/12867743/AltSnap1.62_test3_x64.zip)
Let me know if it works for you...
