### ISSUE TITLE
commands operate on wrong window (window focused at time of last command)

### ISSUE THREAD

**Issue by JGJP** [RamonUnch/AltSnap#455]
I'm observing some interesting behavior, where if I try to resize or pan a window, the actual window that gets affected is always the window that was in focus the last time a command was ran. Sequence of events will thus be like this:

1. Browser focused
2. Terminal focused
3. Try to resize terminal -> browser gets resized (incorrect)
4. Try to resize terminal again -> terminal gets resized (I assume this is because at step 3 the terminal was actually in focus)
5. Try to resize terminal again -> terminal gets resized (all good)
6. Browser focused
7. Try to resize browser -> terminal gets resized (same issue as step 4)
8. Try to resize browser again -> browser gets resized (all good)

This is my best assessment of its behavior, as sometimes it will actually resize a window that seemed totally random and hadn't been focused recently, but it turned out that that was the window I opened first after booting up the computer itself, and it would do this on my first command issued after boot.

My settings are as follows:

![image](https://github.com/RamonUnch/AltSnap/assets/3692190/2a72716c-4f44-40f2-941a-a9151dea9ace)
![image](https://github.com/RamonUnch/AltSnap/assets/3692190/ccad90cc-e6d0-46f6-a907-f993e1922c58)
![image](https://github.com/RamonUnch/AltSnap/assets/3692190/85549f54-a35c-403b-8e67-641489ab833b)
![image](https://github.com/RamonUnch/AltSnap/assets/3692190/cd554f25-988d-4c36-be42-703b6a4476af)

**Comment by RamonUnch** [comment]
quite a big bug indeed, I will need to investigate.

**Comment by RamonUnch** [comment]
This one should fix it.

[AltSnap1.61test22_x64.zip](https://github.com/RamonUnch/AltSnap/files/12326934/AltSnap1.61test22_x64.zip)
[AltSnap1.61test22_i386.zip](https://github.com/RamonUnch/AltSnap/files/12326937/AltSnap1.61test22_i386.zip)

**Comment by JGJP** [comment]
Seems that this fixes it!
