### ISSUE TITLE
Auto start on boot with elevated privileges, how to eliminate the UAC prompt ?

### ISSUE THREAD

**Issue by batchfileframework** [RamonUnch/AltSnap#461]
Hi,

I would like alt-snap to be able to interact with elevated windows.

So I set it to auto start with elevated privileges. 

As alt-snap indicates, this does create a UAC prompt on every boot.
Alt-snap even suggests starting it from a task scheduler as a suggestion.

Do we have a clear method for starting alt-snap with elevated privileges at boot without an extra UAC prompt on every reboot ?

**Comment by batchfileframework** [comment]
I have not tried this but there is a command to create a scheduled task, to run at boot, with elevated privileges

schtasks /create /f /tn "RunAltSnap" /tr "C:\Path\To\AltSnap.exe" /sc onlogon /rl highest

Here is the meaning of those arguments as per schtasks /create /?

    /F                 Forcefully creates the task and suppresses warnings if
                       the specified task already exists.

    /TN   taskname     Specifies the string in the form of path\name
                       which uniquely identifies this scheduled task.

    /TR   taskrun      Specifies the path and file name of the program to be
                       run at the scheduled time.
                       Example: C:\windows\system32\calc.exe

    /SC   schedule     Specifies the schedule frequency.
                       Valid schedule types: MINUTE, HOURLY, DAILY, WEEKLY,
                       MONTHLY, ONCE, ONSTART, ONLOGON, ONIDLE, ONEVENT.

    /RL   level        Sets the Run Level for the job. Valid values are
                       LIMITED and HIGHEST. The default is LIMITED.

**Comment by batchfileframework** [comment]
It is possible to check if the task exists with

schtasks /query /tn "RunAltSnap" /fo LIST

    /TN   taskname       Specifies the task path\name for which
                         to retrieve the information, else all of them.
    /FO   format         Specifies the format for the output.
                         Valid values: TABLE, LIST, CSV.

And it is possible to delete the task with 

schtasks /delete /tn "RunAltSnap" /f

**Comment by RamonUnch** [comment]
There is also an `AltSnap.xml` file in the installation directory to help users to setup the Scheduled task.
Because Scheduled tasks are invisible in the task manager's startup list, I do not put AltSnap there by default, Also many users will not use it elevated anyway.

I will Add the command line options in the wiki, and to the readme file, this will be helpful to some users indeed.

**Comment by RamonUnch** [comment]
Referenced in the README FIRST issue, so I close it.

**Comment by RajStartsHere** [comment]
@batchfileframework Thanks For The Solution, How Can I Make 'AltSnap' Hidden From The Tray?
It Usually Works When It Doesn't Not Run In Elevated Privileges, Via Enabling AutoStart

**Comment by RamonUnch** [comment]
You can add the -h parameter to the command line.

In the `AltSnap.xml` file
```xml
      <Command>%APPDATA%\AltSnap\AltSnap.exe -h</Command>
```

with command line it would be:
`schtasks /create /f /tn "RunAltSnap" /tr "C:\Path\To\AltSnap.exe -h" /sc onlogon /rl highest`

**Comment by shodanx2** [comment]
Hello RajStartsHere

The hiding of the systray is controlled by the command line parameter -hide

`"C:\Users\user\AppData\Roaming\AltSnap\AltSnap.exe" -hide`

I have not tested the following, but I think that's how you should modify

By adding thisline
`<Arguments>-hide</Arguments>`

in the section 
`<Actions Context="Author">`

```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <URI>\AltSnap</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT10S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <GroupId>S-1-5-32-545</GroupId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>5</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>%APPDATA%\AltSnap\AltSnap.exe</Command>
      <Arguments>-hide</Arguments>
    </Exec>
  </Actions>
</Task>
```

**Comment by RamonUnch** [comment]
please use `-h`, not `-hide` as you did, `-hide` is not supposed to work, it will work by default because AltSnap after a `-` only considers the next character, but putting -hide is misleading.

**Comment by RamonUnch** [comment]
If you want the full list of parameters use `AltSnap.exe --help`

**Comment by RajStartsHere** [comment]
> You can add the -h parameter to the command line.
Thanks A Lot, @RamonUnch 

Really Appreciate That
