### ISSUE TITLE
Move or Resize don't work on certain areas of the window

### ISSUE THREAD

**Issue by xan2622** [RamonUnch/AltSnap#463]
Hi.

With AltSnap 1.60 or 1.61, I have noticed that some areas of the window don't work if you try to move or resize the window.
Here are my settings for AltSnap 1.61: https://pastebin.com/XJzrpK2Z

<img src="https://github.com/RamonUnch/AltSnap/assets/1732773/db0f5c42-da98-455a-9ef6-75bf361ce42d" width="75%" height="75%">

As you can see, I can move and resize the window but not if I click at the bottom or on the right side of the window: 

![notepad++_dHJN83iwU3](https://github.com/RamonUnch/AltSnap/assets/1732773/413a578d-b74e-4874-9181-a12b5877adb3)

**Comment by Ichisich** [comment]
I tried your AltSnap.ini and can't reproduce the issue.
Is only Notepad++ affected?
Could you try the same with the Altsnap test window?

**Comment by RamonUnch** [comment]
This looks like a dpi issue, did you try to disable any dpi settings you might have applied to AltSnap.exe?

**Comment by xan2622** [comment]
> This looks like a dpi issue, did you try to disable any dpi settings you might have applied to AltSnap.exe?

This was it! Thank you very much.
