### ISSUE TITLE
Can't get XButton1 (Back button on mouse) working as a hotkey

### ISSUE THREAD

**Issue by AstudilloMarillo** [RamonUnch/AltSnap#467]
I really want to have XButton1, the back button on the mouse, to be the hotkey instead of Alt, but I can't get it to work. I've specified both 05 and A6 in the ini file, following the values listed on the website linked in the ini itself, but it doesn't work. Any other way to do this? Are 05 and/or A6 not the correct values? 

The reason that I want XButton1 as the hotkey is, so I can move applications freely by only using the mouse.

**Comment by AstudilloMarillo** [comment]
I found out I can accomplish this with the 'Activate with click' option set to Mouse button 4, which to be honest is not very intuitive since to me, the sentence "Activate with click" is not really obvious in its meaning. Nevertheless, I did figure it out, so I'm closing this issue.

**Comment by RamonUnch** [comment]
Maybe the Hotclick term would be more clear? I think I will add this term to the config dialog.

**Comment by AstudilloMarillo** [comment]
> Maybe the Hotclick term would be more clear? I think I will add this term to the config dialog.

That would match better with the 'Hotkey' term, so yes it would be more clear I think. Although honestly, I understand that the mouse buttons are not really keys, but I wouldn't be opposed to just calling it Hotkeys (or Mouse Hotkeys?) for clarity's sake. Anyway, just my two cents :).
