### ISSUE TITLE
Change delay of 'Move windows with a long left-click'

### ISSUE THREAD

**Issue by AstudilloMarillo** [RamonUnch/AltSnap#468]
I love to be able to manoeuvre through the OS only using the mouse, when I found out I could move windows by only using 1 mouse button I was immediately sold on the idea.

One thing I'd like some more control over is the delay to "activate" the "long left-click" for the 'Move windows with a long left-click' option. In the ini file I saw that it's tied to the double click delay, does that mean the Windows built in double click delay or the AltSnap built double click delay? Any chance of adding an option (either in the UI or only in the ini) to change this delay?

**Comment by AstudilloMarillo** [comment]
And now that I'm thinking about it, it would also be interesting to be able to experiment with having the long click option on the Right Mouse Button (or any other button for that matter).

**Comment by RamonUnch** [comment]
> One thing I'd like some more control over is the delay to "activate" the "long left-click" for the 'Move windows with a long left-click' option.

This would not be hard. I guess I can add the option.

> And now that I'm thinking about it, it would also be interesting to be able to experiment with having the long click option on the Right Mouse Button (or any other button for that matter).

Unfortunately AltSnap has to send the UpClick event to the program, this means that it will popup the context menu in almost all applications which from my testing makes it unusable with most applications.

**Comment by AstudilloMarillo** [comment]
> This would not be hard. I guess I can add the option.

That'd be a very welcome upgrade for me :D!

> Unfortunately AltSnap has to send the UpClick event to the program, this means that it will popup the context menu in almost all applications which from my testing makes it unusable with most applications.

Right, I understand. I ran into similar issues trying to recreate the window dragging functionality in AutoHotKey (my poormans attempt at it, that is).

**Comment by RamonUnch** [comment]
Note that if you try to set a small delay (like 100ms) you will generate triple clicks with doubleclicks sometime which unfortunately is not really avoidable, so be sure to put a large enough value.

**Comment by AstudilloMarillo** [comment]
> Use this version of AltSnap.exe+hooks.dll
> 
> [AltSnap1.62test2_i386.zip](https://github.com/RamonUnch/AltSnap/files/12822129/AltSnap1.62test2_i386.zip) [AltSnap1.62test2_x64.zip](https://github.com/RamonUnch/AltSnap/files/12822130/AltSnap1.62test2_x64.zip)
> 
> then in the `[Advanced]` section of the .ini file, set:
> 
> ```
> LongClickMoveDelay=0
> ; Delay in ms before considering a click to be long for the LongClickMove
> ; option. Default is 0 to use the double click delay.
> ```
> 
> with the value you want instead of 0.

Works like a charm, gonna experiment with different delays now :)
Thanks for adding this!
