### ISSUE TITLE
Feature Request, add mstsc.exe to the blacklist OOB

### ISSUE THREAD

**Issue by jefflord** [RamonUnch/AltSnap#474]
Seems like a no brainer, right? Works like a charm. 

If you don't Blacklist it, you can't click in the ALT+TAB UI among other things inside a full screen RD session.

**Comment by RamonUnch** [comment]
mstsc main window should already be blacklisted via`*|TSSHELLWND`.
Maybe it does not work anymore on newer Windows?

**Comment by RamonUnch** [comment]
> If you don't Blacklist it, you can't click in the ALT+TAB UI among other things inside a full screen RD session.

Indeed for this reason it needs to be put in the process blacklist...

**Comment by jefflord** [comment]
> mstsc main window should already be blacklisted via`*|TSSHELLWND`. Maybe it does not work anymore on newer Windows?


Not sure. For Windows I am on Version 22H2 (0S Build 22621.2361). For mstsc.exe it's 10.0 22621.2361.


The tool on the Blacklist page has this:

```PMGJL Host - pmgjlhost - Remote Desktop Connection|TscShellContainerClass```

So maybe just add "*|TscShellContainerClass"?

**Comment by jefflord** [comment]
Great, this would have (and will for other), save a lot of confusion when working in RD after installing this on the RD client! 

Thanks!
