### ISSUE TITLE
Alt+Scroll should not trigger while window is "Movement disabled"

### ISSUE THREAD

**Issue by LoganDark** [RamonUnch/AltSnap#484]
I use the "movement disabled" feature for games and IDEs, and it works great. However alt+scroll still changes window transparency when movement is disabled. I think that should not happen (alt+scroll should not work when movement is disabled on the window).

Of course, keep the keyboard shortcuts enabled so I can still open the action menu :)

**Comment by RamonUnch** [comment]
Movement was disabling only the Movement action (move/resize) However disabling also the wheel action makes sense.
This one should do the trick:

[AltSnap1.62_test12_x64.zip](https://github.com/RamonUnch/AltSnap/files/12918774/AltSnap1.62_test12_x64.zip)
[AltSnap1.62_test12_i386.zip](https://github.com/RamonUnch/AltSnap/files/12918779/AltSnap1.62_test12_i386.zip)

**Comment by LoganDark** [comment]
That works indeed, thank you so much!
