### ISSUE TITLE
Move To Next Edge Invisible Border

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#491]
The `Move to Next Edge` action shows some misalignment:

![1](https://github.com/RamonUnch/AltSnap/assets/31080003/9725f736-5b13-4fc0-8022-525127b4b077)
![2](https://github.com/RamonUnch/AltSnap/assets/31080003/7603700b-2264-43f0-8bc3-138037fc027e)
![3](https://github.com/RamonUnch/AltSnap/assets/31080003/40fe3d66-f988-4fd3-a32d-c1a15906f302)

This behavior shows only when moving towards the bottom and is not affected by the position of the taskbar.

**Comment by RamonUnch** [comment]
indeed there is a sign error just for the bottom border in my code.
fix:
[AltSnap1.62test14_x64.zip](https://github.com/RamonUnch/AltSnap/files/13225742/AltSnap1.62test14_x64.zip)
