### ISSUE TITLE
Is it possible to make Activate with click compatible with Title bar?

### ISSUE THREAD

**Issue by signin404** [RamonUnch/AltSnap#503]
For example:
Set Activate with click to Mouse button 4
Title bar Mouse button 4 is set to center
Perform centering when Mouse button 4 is pressed on Title bar
Activate with click is only executed when Mouse button 4 is pressed outside the Title bar

**Comment by RamonUnch** [comment]
for now Hotclick has precedence over titlebar action, this should be reversed.
This test build should fix it, replace exe and dll files.
[AltSnap-1.63test1_x64.zip](https://github.com/RamonUnch/AltSnap/files/14033881/AltSnap-1.63test1_x64.zip)

**Comment by signin404** [comment]
The beta version works fine
