### ISSUE TITLE
Request: add remapping for "Alt Key"

### ISSUE THREAD

**Issue by spacemansp1ff11** [RamonUnch/AltSnap#506]
Can you allow remapping the Alt drag key to the Windows Key, or Win+Alt? This would be super useful, especially when using unix+windows together, so I can keep alt key functionality on unix.

**Comment by Ichisich** [comment]
![Unbenannt](https://github.com/RamonUnch/AltSnap/assets/31080003/a97b80d7-16a7-4d5b-b8e9-9c508d9f91d8)

**Comment by RamonUnch** [comment]
@spacemansp1ff11 
As Ichisich said, you can already use a different hotkey to activate AltSnap, Alt is just the default for compatibility with Linux desktops.
