### ISSUE TITLE
Weird behavior when holding the alt key

### ISSUE THREAD

**Issue by PanterM** [RamonUnch/AltSnap#518]
I'm very sorry if there is an option I missed or this is addressed somewhere in the wiki but I can't find it.

My problem is that when I hold the alt key and move a window it locks it to my current screen/monitor.

When rezising it locks it horizontally and only snaps vertically to certain positions depending on how high or low I am from the center of the middle section of the window

If I let go of the key while moving or resizing it's completely fine. Is this a bug or a feature I'm missing somewhere?

The version I'm using is the latest version 1.62

**Comment by RamonUnch** [comment]
Strange behavior, does it happen when you use WinKey as a hotkey?
Also maybe you are using **Alt Gr** and in this case depending on your keymap it can actually behave as Alt+Ctrl. In this case AltSnaps Cannot see the difference between you pressing simply Alt or Alt+Ctrl. The solution would be then to use a different hotkey.

**Comment by RamonUnch** [comment]
To be sure you can check what your Alt key sends to the **Test Window** available in the Advanced tab of the config: For Example here is what happens with a french keymap:
![image](https://github.com/RamonUnch/AltSnap/assets/74856804/b545886b-bcfc-4f22-a56e-9ebe0706a652)

**Comment by PanterM** [comment]
Ah that would be it, I use right alt because I have hotkeys on my main Alt key.
I did see the Test Window log but thought it was standard behavior as I didn't encounter a problem with it before (when using altdrag).
I have it bound to an additional mouse button I have so rebinding it to something else shouldn't be a problem.

**Comment by RamonUnch** [comment]
>  I did see the Test Window log but thought it was standard behavior as I didn't encounter a problem with it before (when using altdrag).

Indeed AltDrag was avoiding this by ignoring the Ctrl key when it was pressed before Alt, however this would not be nice when using the Ctrl key modifier because it means you had to be pressing the keys in the right order.

I guess I could do a workaround (not sure what yet) but I wonder if it is worth it.

**Comment by RamonUnch** [comment]
Actually the fix is trivial,
Try with this build, it ignores the Ctrl key if it is a *simulated* key.

[AltSnap1.63fix2_x64.zip](https://github.com/RamonUnch/AltSnap/files/15285588/AltSnap1.63fix2_x64.zip)
