### ISSUE TITLE
Add "Scroll pressed" action

### ISSUE THREAD

**Issue by cojoMan** [RamonUnch/AltSnap#519]
Is it possible to add an extra action to be selected when the scroll wheel is pressed ?
I've added actions to left, right, scroll wheel, but4+5, and I'd like another one, and not sure how to add it, since I've maxed the buttons I could possibly use for it..
Currently using leftWin key as an activation key.
Is it possible to add a secondary activation key for another set of actions ? I can see radio buttons for "while moving" and "while resizing" but those don't make sense, and "alternate" and "title bar" are disabled...
Thanks

**Comment by RamonUnch** [comment]
You can select a modifier key for alternate action, alternate actions in the keyboard tab? you could use Alt for example and then Win+Alt would be the alternate action and while Win would remain the current action.

> I can see radio buttons for "while moving" and "while resizing" but those don't make sense

They make perfect sense, you can for example decide that when a drag started you can click another mouse button to make an action, for example you can have Win+LClick+RClick => any action you want or Win+LCkicl+Wheel => any wheel action you want. This is very powerfull and doubles the amount of available actions Again.

To use titlebar actions you must check the **Use specific action when clicking the titlebar** please read the wiki, it is not complete but it will get you started. Also keep in mind that more can be configured via the .ini file.

**Comment by RamonUnch** [comment]
If you want to have a different action happen when the middle button is down, set it as the Move action, then set the **While moving** actions to your likings.

**Comment by cojoMan** [comment]
oh wow, thank you for explaining it to me.
SO MANY more available actions !!
win+alt for the win ! :D
