### ISSUE TITLE
Cant seem to clear shortcut keys - keyboard tab [v1.63]

### ISSUE THREAD

**Issue by schroef** [RamonUnch/AltSnap#526]
AltDrag v1.63
Win 11 

Description
I was trying to add a key-combo to activate and deactivate AltDrag. Somehow, it keeps showing Kill program and i cant reset the keys. When i try to clear and save, after reopening the settings menu. It still show Kill program.

How can i actually make it toggle the app On and Off. I use the alt drag for Blender a lot since im a tablet user 100%.

![Screenshot 2024-04-25 121328](https://github.com/RamonUnch/AltSnap/assets/6923008/c7432087-e867-4b91-8761-75b8e96699bf)

**Comment by schroef** [comment]
Kinda solved it, apperantly if you do a "clear", you need to save it in order to clear it. Im still looking for the solution to toggle AltDrag on and off with a key-combo. The tips state it, but it doesnt state where we can do this

https://github.com/RamonUnch/AltSnap/wiki#tricks-you-should-know:~:text=a%20key%20combo%20can%20be%20used%20in%20order%20to%20activate%20altsnap%2C%20this%20allows%20using%20alt%2Bwinkey%2Bclick%20to%20drag%20windows%20and%20leaves%20alone%20the%20win%2Bclick%20and%20the%20alt%2Bclick%20that%20some%20programs%20may%20require.

**Comment by Ichisich** [comment]
The action is called `Suspend/Resume Altsnap`.
Alternatively, you can also use the scroll lock key. It's the first checkbox in your screenshot.

**Comment by schroef** [comment]
Yeah had just found it after fiddling around in the menu


Edit
Okay found it in shortcut menu, perhaps add a link in the description for that.
![suspend-altdrag](https://github.com/RamonUnch/AltSnap/assets/6923008/d335f604-7fa7-4763-bef0-e3be92c744d2)

**Comment by RamonUnch** [comment]
For the other question, if you want to use a key combo you can simply check the box in the screenshot you show (very bottom) you will also need to check two hotkeys in addition and AltSnap will only activate when you press both keys at the same time.

**Comment by schroef** [comment]
@RamonUnch 
That's better perhaps than the shortcut to suspend. Im going to try both a bit, see which feels more natural.

**Comment by RamonUnch** [comment]
>Ps when there is a 2-key combo for a action, will that turn into a 3 button combo than?
> So say I set WIN for the 2 key combo, does al + shift + LMB than needs WIN as well

Yes you will, you need two **Hotkeys** to be pressed, the Hotkeys are the ones that activate AltSnap.

Most action have an alteration when pressing Shift and Ctrl, You can also configure an alternate key to use an alternate action with mouse click. This alternate key can be combined with the hotkeys so for instance you could use the WinKey and then in your case Alt+Win+Click => primary action and Win+Alt+Click => Secondary action.

**Comment by schroef** [comment]
> >Ps when there is a 2-key combo for a action, will that turn into a 3 button combo than?
> > So say I set WIN for the 2 key combo, does al + shift + LMB than needs WIN as well
> 
> Yes you will, you need two **Hotkeys** to be pressed, the Hotkeys are the ones that activate AltSnap.
> 
> Most action have an alteration when pressing Shift and Ctrl, You can also configure an alternate key to use an alternate action with mouse click. This alternate key can be combined with the hotkeys so for instance you could use the WinKey and then in your case Alt+Win+Click => primary action and Win+Alt+Click => Secondary action.
> 

Wait you mean I can see the teigferwd keys and the order in which they are triggered?
I can not or understand where to add the win key as a modified key. The past section shows an option to press a secondary key to trigger altsnap, I would prefer than alt+win. But i couldn't find where to add it in ini file
