### ISSUE TITLE
Feature request : reload config explicitly option in systray context menu

### ISSUE THREAD

**Issue by shodanx2** [RamonUnch/AltSnap#528]
While fiddling with another setting

I can't tell if/when my changes to the ini config have been activated

I propose the following

![w2ZLeI0AFl](https://github.com/RamonUnch/AltSnap/assets/10621885/30768aca-1713-4c8d-a396-3d8f0732643f)

**Comment by RamonUnch** [comment]
For now you can enable/disable altsnap and config options will be reloaded.
Some special options require a full restart, nut they are few.

**Comment by shodanx2** [comment]
sounds good thanks 👍
