### ISSUE TITLE
[bug?] Snapping after Alt-Tab doesn't work.

### ISSUE THREAD

**Issue by sequencerr** [RamonUnch/AltSnap#529]
Snapping after Alt-Tab doesn't work properly.
ex.: press Alt-Tab, keeping pressing Alt, switch to other window(without unpressing only possible with mouse, or Enter, I guess), action Alt-Lmb doesn't work

**Comment by RamonUnch** [comment]
Tab is in the Killkeys list so it should not be possible to even drag the window.

Open the AltSnap.ini file (middle click the tray icon)
Search for Killkeys list
`Killkeys=09 2E`

Just remove the `09` which is 'tab'
Alt+Tab can in some cases open an elevated window and in this case AltSnap cannot be warned that Alt was released, that is why it is in the killkeys, I would advise in general against removing it but you can try.

**Comment by sequencerr** [comment]
so remapping alt-tab or snap key would also possibly help?
