### ISSUE TITLE
Move to left/right/top/bottom zoone limitation

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#534]
These are my 'window zones' for example (1) left focused window - a liitle space at the right side -, 2) middle window, 3) right focused window - a liitle space at the left side -, 4) middle bottom window)

![Snap_Layout](https://github.com/RamonUnch/AltSnap/assets/1481680/c0541ccb-ae00-4b5d-8c28-16774e2185b1)

I've set it to
`move to left zone` = `ALT + LEFT`
`move to right zone` = `ALT + RIGHT`
`move to bottom zone` = `ALT + DOWN`

The only thing thing which work is `ALT + LEFT` => window goes to 1) and `ALT + RIGHT` => window goes to 3).

I can't use the middel bottom window 4) for example - I thought this should work with `ALT + DOWN` but `ALT + DOWN` maximize the window to whole screen.

_Originally posted by @Heart1010 in https://github.com/RamonUnch/AltSnap/issues/511#issuecomment-2100550159_

**Comment by RamonUnch** [comment]
@Heart1010
Could you try this build, I changed the way the next left/top/right/bottom zone is picked in the case  you use `ZSnapMode=1`
It should help with your case.

[AltSnap1.63test_x64.zip](https://github.com/RamonUnch/AltSnap/files/15282603/AltSnap1.63test_x64.zip)

**Comment by Heart1010** [comment]
This is exactly the way I supposed it to work 👍
