### ISSUE TITLE
Centering a window is misaligned

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#546]
When centering a vertically maximized window, the window shows a cropped title bar and a 3 pixel gap between its bottom edge and the taskbar or screen edge.

![1](https://github.com/RamonUnch/AltSnap/assets/31080003/7774e9bd-b64d-4a0b-a508-fe72f5450766)

Centering the vertically maximized window:
![2](https://github.com/RamonUnch/AltSnap/assets/31080003/c93d59c1-c33a-4bfa-a433-31494d7bdf8c)

Zooming in, we see the 3 pixel gap:
![3](https://github.com/RamonUnch/AltSnap/assets/31080003/59c6f602-3199-43be-b565-54a8ded8b831)

The gap is consistent even when I resize/disable the taskbar or move it to the side.

**Comment by RamonUnch** [comment]
this build should fix it, thanks to @mbartlett21 for finding the time to fix it.
[AltSnap1.64test2_x64.zip](https://github.com/user-attachments/files/17006772/AltSnap1.64test2_x64.zip)

**Comment by Ichisich** [comment]
It does, much appreciated @mbartlett21
