### ISSUE TITLE
Not able to disable Double Click action.

### ISSUE THREAD

**Issue by Shy1nx** [RamonUnch/AltSnap#551]
I'm using Alt+Double click to see the Properties easily. And I find ALT key is the most suitable for this program. So, I don' t want to change it to the CTRL or Windows key. Can you please add option to disable Double Click action? I don't want to make full screen by double clicking with ALT.

**Comment by Ichisich** [comment]
You can re-enable native Alt+Double click with:

![Alt-Doubleclick](https://github.com/user-attachments/assets/c3b9fc29-99ba-49c6-89cf-2ea1cc7a486b)

But you will lose the `Long drag-fee` actions.

**Comment by RamonUnch** [comment]
As @Ichisich said it can already be disabled, so I close this one.
Normally the long drag-free should not be lost but no longer requires a long click.
