### ISSUE TITLE
Moving and resizing with AltSnap 1.64 now activates PowerToys FancyZones

### ISSUE THREAD

**Issue by flechnical** [RamonUnch/AltSnap#572]
> AltSnap Version 1.64
> Windows 11 Version 23H2 (OS Build 22635.4371)
> PowerToys Version 0.86

When trying to resize windows with the right mouse button the window is automatically snapped into the zone in FancyZones (PowerToys setting: "Hold Shift key to activate zones while dragging a window" is deactivated).

The only way to avoid this behavior is to release Alt and hold Shift before releasing the mouse button.
The same applies to moving the window using the left mouse button, however this could be considered a feature if intended (if so, letting the user choose in the settings would be optimal).

Downgrading to 1.63 fixes the issue, so it is most likely be due to a change in AltSnap rather than PowerToys or Windows.

**Comment by RamonUnch** [comment]
I guess this is because of the new accessibility event.

Try with this version of hooks.dll
[hooks.zip](https://github.com/user-attachments/files/17790547/hooks.zip)

**Comment by flechnical** [comment]
I just reinstalled 1.64 and tried your suggestion.

This solved the issue for 1.64👍.
Neither the left mouse button nor the right mouse button now activate FancyZones.

I also do not see any weird behavior because of the swapped hooks.dll (at least while playing around for a few minutes).

**Comment by RamonUnch** [comment]
This version has it optional,
If you could test, in the next version it will be like this:

[hooks.zip](https://github.com/user-attachments/files/17791276/hooks.zip)

For this one you need to set:
```
in the [Advanced] section of the .ini file

NotifyWinEvent=0
; Determines if AltSnap should send the EVENT_SYSTEM_MOVESIZESTART/END
; events when moving a window. This is useful when interacting with
; some other accessibility tools (default 1).
```

This was added for compatibility with other windows manager such as [komorebi](https://github.com/LGUG2Z/komorebi). But it will interact with FancyZones.

**Comment by flechnical** [comment]
It works as expected.

When I add your new hooks.dll it goes back to default 1.64 behavior.
When I then add the new lines to the [Advanced] section in the .ini it behaves like 1.63, so it does not conflict with FancyZones anymore.
