### ISSUE TITLE
winget

### ISSUE THREAD

**Issue by dmwyatt** [RamonUnch/AltSnap#62]
It would be nice if this was submitted to [winget](https://github.com/microsoft/winget-cli).  You do that [here](https://github.com/microsoft/winget-pkgs). Unfortunately, the original AltDrag is [already on there](https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AltDrag/AltDrag/1.1/AltDrag.AltDrag.yaml), so I'm not sure what to do about that.

(For the unaware, winget is Microsoft's own package manager in the vein of chocolatey.)

**Comment by RamonUnch** [comment]
Interesting...
It seems that anyway that the [AltDrag 1.1 package](https://github.com/microsoft/winget-pkgs/pull/2436) was not added by Stefan himself, and he is probably not even aware.

I took the choco package from **narnaud**, its previous owner who had stopped using Windows.
After a [discussion with Stefan](https://github.com/stefansundin/altdrag/discussions/128), he came to the agreement that it was fine I took the choco slot, as long as he would have no update for the original altdrag.

So I think it makes sense to submit this AltDrag version but with a different name.
Probably I should rename the whole project at some point.

An other option would be to ask the advice of @gabrielstedman who submitted the AltDrag package.

**Comment by gabrielstedman** [comment]
Hi, I'm happy to assist with this.
Are you planning on maintaining this fork separately or are there any plans to integrate into original repo?

**Comment by RamonUnch** [comment]
This is a fork and most of it will not be ported back to the original AltDrag.
I did submit a few PRs to the original AltDrag (important bugfixes) but they will not be integrated unless Stefan starts again to work on the project.
For now it seems he is not going to work on it soon he has other more important things to do.
I plan to keep working on this fork, as long as I can find some time and as long as I will be using Windows.

It would be very appreciated if you could take care of the winget package, I guess everyone would be grateful.

**Comment by gabrielstedman** [comment]
From reading your conversation with Stefan it doesn't look like he's abandoned the project, looks like he intends to differentiate the official from forks.
If he explicitly agrees I can open a winget PR to switch existing official version to this fork else I'd suggest a project rename.

**Comment by RamonUnch** [comment]
You are right, the project needs to be renamed.
I need to come up with something.

**Comment by dmwyatt** [comment]
Name suggestions:

1. dragrace
2. moveit
3. altmove
4. winch (WINdow CHanger)
5. dragalt
6. alttug
7. altpull
8. winyank (as in...yanking windows around)

**Comment by RamonUnch** [comment]
Well [AltMove ](http://www.altmove.com/)already exists (similar to AltDrag). 
Same for [MOVEit ](https://www.ipswitch.com/moveit) (compleatly dirrerent program though)

DragRace is pretty cool but sounds more like a game.

Winch is a cable pulling device (funny sounding), in this case I would propose **ZDrag** which is also a pulleys system and is more reminiscent of AltDrag with exten or maybe even **ZXDrag** to remind that it is implementing a feature available on most of X-window managers (the original predecessor of AltDrag was [Win-X-Move](http://winxmove.sourceforge.net/)).

I also thought about **EzDrag** or **EasyDrag**

I think i will make a new thread fore proposition.
To me this is no hurry anyway.

**Comment by RamonUnch** [comment]
Next release will be named AltSnap instead of AltDrag. This will avoid any package name pollution.

**Comment by RamonUnch** [comment]
New release: AltSnap 1.47, anyone interested can update the winget package

**Comment by crramirez** [comment]
https://github.com/microsoft/winget-pkgs/pull/29259
