### ISSUE TITLE
New name for the project

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltSnap#63]
This fork of AltDrag went quite some distance away. 
I am planing to rename the project, to avoid conflict with the original AltDrag.

Name suggestions from @dmwyatt:

1. dragrace
2. ~~[moveit ](https://www.ipswitch.com/moveit)~~(Already exists!)
3. ~~[altmove ](http://www.altmove.com/)~~(Already exists!)
4. winch (WINdow CHanger)
5. dragalt
6. alttug
7. altpull
8. winyank (as in...yanking windows around)

My suggestions in no particular order:
ZDrag, ZXDrag, EZDrag, EasyDrag.

I am open to more suggestions and to users preferences.
I am not in a hurry to change the name

**Comment by bufferUnderrun** [comment]
alt base :
- alteration
- alteraction

drag base :
- dragonalt
- dragon

**Comment by Florin9doi** [comment]
AltDrag2

**Comment by scx** [comment]
@RamonUnch 

>  I am planing to rename the project, to avoid conflict with the original AltDrag.

I think it is fine to keep the old name if development of the orginal version has been stalled or original author just give up. Actually, we have a lot of such projects in FLOSS, including _MyPaint_ or _RawTherapee_.
You could also rename it to **AltDrag2**, just like it was with _Notepad2_ ⭢ _Notepad3_.
If you want to pick different name, you should take a look at similar projects first:
- [AquaSnap](https://www.nurgo-software.com/products/aquasnap)
- [KDE Mover-Sizer](https://corz.org/windows/software/accessories/KDE-resizing-moving-for-Windows.php)
- [Win32WM](https://github.com/mlni/win32wm) ([VirtuaWin](https://virtuawin.sourceforge.io) [module](https://virtuawin.sourceforge.io/?page_id=50))
- [WindowGrid](http://windowgrid.net)

It should be noted that these software are not only about dragging windows, but also snapping windows to the edges. I think this is a feature that is worth to be mentioned.
Unfortunatelly, **snapdragon** and **snapdragger** are trademarks, and **snapdrag** is already taken. However, **AltSnap** should be free for now. The same thing applies to **AltWM**.

**Comment by RamonUnch** [comment]
> I think it is fine to keep the old name if development of the original version has been stalled or original author just give up. Actually, we have a lot of such projects in FLOSS, including MyPaint or RawTherapee.

I was thinking the same thing, but Stefan would prefer his version to stay the _official_ version. The name is not registered or anything but Stefan do plan to release newer versions eventually. My fork when too far from the original AltDrag for him to ever merge everything. That is why I submitted some mandatory bug-fixes to him (in hope they will be eventually merged).

I want to be able to have a winget (https://github.com/RamonUnch/AltDrag/issues/62) package, and it would be better to stop "stealing" the [chocolatey package](https://chocolatey.org/packages/altdrag) slot.

So I excluded AltDrag2 because it would really look like just "a build" of AltDrag which it is not.
I really like your **AltSnap** suggestion, it remains short and simple.

**Comment by garoto** [comment]
altdrag-ng
drag-snap
drag-n-snap
easy-snap
grab-n-drag

**Comment by mebo** [comment]
What about something like ngDrag (bit of a next-gen vibe)

**Comment by chrisburel** [comment]
I'd vote for `windrag`. I always reset the drag key to the Windows key anyway, because I have applications that use the Alt+LMB drag combo (like Blender) and they conflict.

**Comment by dmwyatt** [comment]
> alt base :
> 
> * alteration
> * alteraction
> 

I thumbs up for those suggestions.  

I don't think there's much, if any, evidence that it really matters if the name obviously reflects the functionality of the program. There's tons of successful software using names that don't have any bearing on what they actually do, and tons of unsuccessful software using names that match their purpose quite well. I'm not a fan of naming skeuomorphism just for the sole purpose of describing the software.

The two examples quoted above are a nice little "insider joke" for those who know what the "alt" means and for those who don't they're fine names with no other meaning.

**Comment by yatli** [comment]
+1 altdrag-ng

**Comment by neerolyte** [comment]
draggy-mc-drag-face

**Comment by chutzimir** [comment]
AltDragRU ?

**Comment by RamonUnch** [comment]
Thanks for all your suggestions,
I finally stuck to AltSnap! I also considered seriously WinDrag but it is already taken.
Next release will add some features and will be named AltSnap.
