### ISSUE TITLE
AltDrag not working on newer versions of Vivaldi

### ISSUE THREAD

**Issue by molohov** [RamonUnch/AltSnap#72]
It's been working fine until I updated Vivaldi recently

Current version of Vivaldi: 4.0.2312.33

With Alt as the trigger, Alt will open the menu. With another key like Win as the trigger, text gets selected on the page.

**Comment by RamonUnch** [comment]
Strange, I cannot reproduce the bug on the same Vivaldi-4.0.2312.33. (using AltDrag 1.43 and Win 10_x64 20H2)
Which version of Windows are you using? Could you give me a zipped copy of your .ini file?
Did you change default settings of Vivaldi?

When you press Alt (in most programs), then the menu gets selected.
However could you disabel AlrtDrag, then check if the menu activates when pressing the following key sequence:
Press Alt, Press then release Ctrl, release Alt.
If you try this with a "normal" program (like notepad), the Ctrl before releasing Alt will prevent the menu from activating.
For me Vivaldi behaves...

**Comment by RamonUnch** [comment]
Maybe it is a lag problem. Does it work if you press Alt and wait a little before trying to click and drag?

**Comment by molohov** [comment]
I am on Windows 10 x64 21H1. 
I tried the Alt + Ctrl experiment and it doesn't activate the menu.
If I wait a bit after pressing Alt, it still doesn't work.

Attaching my .ini file
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6697051/AltDrag.zip)

**Comment by RamonUnch** [comment]
I will have a deeper look tomorrow, in the meantime, could you give a try with the latest test build?
I did quie some changes and it might be fixed (probably not though), but just in case.
[AltDrag1.44-test15.zip](https://github.com/RamonUnch/AltDrag/files/6697196/AltDrag1.44-test15.zip)

So to be clear, when using Alt+Clic, you do see the _hand_ cursor and the windows moves when you drag? the only problem is that the menu gets selected? 
Or the windows does not move at all? Do you see the hand cursor when trying to drag?

**Comment by molohov** [comment]
With your test 1.44, the issue is resolved!
In 1.43, when I hold Alt + Click, I don't see the hand cursor appearing.

**Comment by molohov** [comment]
Haha, it's working again now. I think Vivaldi tends to have some issues after it updates; I had issues with other applications that were trying to use multiple profiles and those were bugging out too until I restarted Vivaldi. Closing once again, thanks!
