### ISSUE TITLE
Feature Request: AltDrag to work with PowerToys FancyZones

### ISSUE THREAD

**Issue by shelbyKiraM** [RamonUnch/AltSnap#80]
I'm quite interested in AltDragging with left then clicking right or another key like I can do if I drag a window using the titlebar or other draggable area... but this may be also a feature to belay for Windows 11's new shiny Snap interface (I'm testing 11 rn, can confirm, AltDrag works as expected!! 😺)

**Comment by RamonUnch** [comment]
I do not have Win 11 for now so I cannot promise anything soon.
But I guess there is a one main thing to do: Support snap layouts?
* Read the them from wherever windows stores them if it is even documented?
* Snap to the pointed *Zone* when the user presses a specific key (or mouse button) while AltDragging.

Just to know Under Win11, when you snapped a window in a zone, is its size properly restored when moving it out of the zone?
Also when moving it out with AltDrag?
I have a way to detect is a windows was snapped by window7/8.x/10 but I do not know if it works with Win11 as all the snapping is opaque and microsoft did not document or offer any functions to handle sanpped windows. this makes the job of AltDrag much harder that it looks as I have to re-implement what MS already did.

**Comment by RamonUnch** [comment]
work in progress: https://github.com/RamonUnch/AltSnap/issues/97
