### ISSUE TITLE
Feature Request: add maximize window horizontally/vertically

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#85]
Would be nice to have this function as a mouse action.
Windows provides this currently with win+shift+up and double-clicking on the top or bottom window border.

**Comment by RamonUnch** [comment]
This could be added as an option but for now you can maximize the windows vertically with Alt+Double-right-click on the middle of the window (central fraction). If you want to maximize horizontally then add the Shift modifier. ie: Alt+Shift+Double-right-click always on the central fraction of the monitor.
Is that enough for you or you need a specific action?

**Comment by Ichisich** [comment]
Nice, I didn't know what the fractions could do. 

Although a dedicated mouse action would be preferable, because one wouldn't have to aim, but Alt(Win in my case)+double-right-click in the central fraction does the trick for me.
Thanks for the quick response.

**Comment by RamonUnch** [comment]
Here is a beta version with the Maximize Vertically action, (use Shift to maximize horizontally)
Note: project was renamed to AltSnap:
[AltSnap1.47-test3.zip](https://github.com/RamonUnch/AltSnap/files/7142168/AltSnap1.47-test3.zip)

**Comment by Ichisich** [comment]
Unfortunately, the bottom border doesn't align correctly with the task bar or bottom screen edge, in case the taskbar is docked to the sides.

![Screenshot 2021-09-10 101236](https://user-images.githubusercontent.com/31080003/132822418-5af23896-f46d-44ce-ac6a-708fe66bea07.png)

Double metaclick into the cenral fraction or the native Windows solutions don't show the same behaviour.

**Comment by RamonUnch** [comment]
[AltSnap1.47test4.zip](https://github.com/RamonUnch/AltSnap/files/7142391/AltSnap1.47test4.zip)
Yep, I forgot about invisible borders, this is an easy fix.

**Comment by Ichisich** [comment]
Yep, works like a charm now, thank you.
BTW: "Use AltSnap for normalt titlebar movement" is a wonderful implementation. Makes window behaviour far more consistent

**Comment by Ichisich** [comment]
Seems the vertically maximized window gains some width:

From:
![1](https://user-images.githubusercontent.com/31080003/132835983-b41a8be3-16be-4036-8965-6e1a36354ac8.png)
To:
![2](https://user-images.githubusercontent.com/31080003/132836018-a9367339-ff25-4eef-b74e-0ca76e864cbf.png)

**Comment by RamonUnch** [comment]
Test5 should have fixed it, you were so quick to download that you got an intermediate version.
Just in case:
[AltSnaptest6.zip](https://github.com/RamonUnch/AltSnap/files/7143110/AltSnaptest6.zip)

**Comment by Ichisich** [comment]
Fixed.
