### ISSUE TITLE
Ubersmart Aero Snap Dimensions

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#94]
Would it be possible to let windows align with any other window when getting snapped, not just other snapped ones?

Current behaviour:
![current](https://user-images.githubusercontent.com/31080003/132989589-b89b9b67-7cc5-4cac-b820-b54a081e8383.png)

Desired behaviour:
![desired](https://user-images.githubusercontent.com/31080003/132989595-558703c3-01cb-41b4-a878-a6d7b8241781.png)

This would also improve AltSnap's consistency, as currently only other windows snapped via AltSnap are being recognized as such but not native ones.

**Comment by RamonUnch** [comment]
It should be possible to have more snapping, I will see on how to implement it.

However smart aero snapping should work alongside normally snapped windows.
ie: when you snap, then resize a window natively, then if you alt-snap a window to the other side it should fill in the gap.

**Comment by RamonUnch** [comment]
It is not trivial matter though to decide to which side one should snap to when there are many windows, whai I can do is snap to any windows that are touching the screen borders (for which decision is much easier and that I already wrote to handle the case of non altsnapped windows).
Use this copy of hooks.dll and set SmartAero=2 in the [General] section of the ini file.

**Comment by Ichisich** [comment]
Perfect, I only chose a loose window to better illustrate what I meant.

**However smart aero snapping should work alongside normally snapped windows.**
It does, but sometimes fails to grasp the edge of the other window and falls back to a simple screen split.
I wasn't able to dependably reproduce this misbehaviour, but it seems higher max snapping speed is more reliable and faction snapping is always successful.

**Comment by Ichisich** [comment]
After some testing, so far so good, the new hook.dll even recognizes fixed positioned windows as long as they are placed at the screen edge.
The only feature that is missing yet is the consideration of horizontal edges.

**Comment by Ichisich** [comment]
> The only feature that is missing yet is the consideration of horizontal edges
Implemented in [#96 (comment)](https://github.com/RamonUnch/AltSnap/issues/96#issuecomment-917697966)

**Comment by Ichisich** [comment]
I found some oversights in quarter-snapping:

Current:
![current1](https://user-images.githubusercontent.com/31080003/133925913-acb513cf-f6df-4f4e-a2c2-8df5abaacd2b.png)

Desired:
![desired1](https://user-images.githubusercontent.com/31080003/133925919-88e32c71-a19a-4111-a210-2eb7b9ef0c1b.png)

Current:
![current2](https://user-images.githubusercontent.com/31080003/133925931-150728e9-ab4e-4280-b12f-71aa2ac7eb36.png)

Desired:
![desired2](https://user-images.githubusercontent.com/31080003/133925935-0fe3b6d4-e0e1-4318-8fdf-a2e8f33fbdd7.png)

**Comment by RamonUnch** [comment]
I understand your desire, however it would be enabled only in the Ubersmart mode, because the behavior of normal snapping is what AltSanp does, only take in account the window that is on the opposite side, same for up/down.
I will see on how to do this.

**Comment by RamonUnch** [comment]
Actually you are right, Win10 behavior is what you just said, my mistake...
