### ISSUE TITLE
Smart Aero Snap Overlaps Virtual Desktops

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#95]
Tested with 1.46 on Windows 10

In case, a window is snapped and then resized on one virtual desktop:
![1](https://user-images.githubusercontent.com/31080003/132997854-438949f8-b58b-4575-8755-e9f8fc6fdb03.png)

AltSnap adapts even on other virtual desktops:
![2](https://user-images.githubusercontent.com/31080003/132997869-ce77f780-3631-4379-9946-9647f0059722.png)

**Comment by RamonUnch** [comment]
Those are standard Win10 virtual desktops?
I actually never used them.
Try this build (could not test on Win10 yet):
[hooks.zip](https://github.com/RamonUnch/AltSnap/files/7150155/hooks.zip)

**Comment by Ichisich** [comment]
Yep, everything is standard, and I only encountered this niche quirk by accident.

The behaviour still persists.

**Comment by RamonUnch** [comment]
It seems virtual desktop api can be accessed with IServiceProvider stuff, I will check this when I got more time.

**Comment by RamonUnch** [comment]
Well it seems that GUID to acess those functions are changed with every major builds under Win10 https://github.com/Ciantic/VirtualDesktopAccessor/issues/33, so I am not sure I want to take time with this mess, it is undocumented anyway. zVirtualDesktop is playing with that: https://github.com/mzomparelli/zVirtualDesktop.

**Comment by Ichisich** [comment]
Elegant and works in regard to virtual desktops. 

According to the documentation, the cloaked attribute is applied in a few use cases, but never user-visible.
This approach could even have some positive side effects beside virtual desktops.

> DWMWA_CLOAKED
Use with DwmGetWindowAttribute. If the window is cloaked, provides one of the following values explaining why.
DWM_CLOAKED_APP (value 0x0000001). The window was cloaked by its owner application.
DWM_CLOAKED_SHELL (value 0x0000002). The window was cloaked by the Shell.
DWM_CLOAKED_INHERITED (value 0x0000004). The cloak value was inherited from its owner window.
Windows 7 and earlier: This value is not supported.

> Answered from an internal forum in Microsoft:
"To check the cloak state a caller may call DwmGetWindowAttribute() with DWMWA_CLOAKED. A nonzero attribute value (of type BOOL) means the window is “cloaked” and not user-visible. This is the recommended mechanism for developers to skip windows when performing enumerations of things that are supposed to be logically “visible” (in addition to WS_VISIBLE)."
