### ISSUE TITLE
Don't restore AltSnapped windows with AltSnap movement.

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#96]
Identical to normal movement, the behaviour of which is toggleable in the advanced options.

**Comment by RamonUnch** [comment]
So if I understand well you would like an option so that windows are not restored to there pre-snapped state when alt-dragging them?
This would be very easy (just would have to not even store restore info) but I am not sure this is what you really want.

**Comment by Ichisich** [comment]
That's exactly it.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltSnap/files/7150184/hooks.zip)
Try with this version of hooks.dll
and add 4 to the value of `SmartAero` in your case set `SmartAero=6` (7 will also work)
Windows that are snapped normally will still be restored and also maximized windows.

**Comment by Ichisich** [comment]
It works, thank you.
