### ISSUE TITLE
Fun weird issue

### ISSUE THREAD

**Issue by xzayn** [RamonUnch/AltSnap#98]
![image](https://user-images.githubusercontent.com/74079803/133907478-02118acb-42db-45bd-a65a-ac7487187e5a.png)
This happens with non-resizable windows when I try to maximise them by dragging them up (not much of an issue tbh but bleh)

**Comment by RamonUnch** [comment]
Did you disable the "Resize all windows option" in the general Tab of the config. If it is disabled you will no longer be able to resize or maximize the windows that do not have the `WS_THICKFRAME` flag. All windows that are supposed to be resized should have this flag.

**Comment by RamonUnch** [comment]
There is a bug for now if you disable this option. You will actually be unable to AltSnap resizble windows after moving a non resizable window, this will be fixed of course.

**Comment by RamonUnch** [comment]
Fixed versions.
i386 builds [AltSnap1.47test15bin.zip](https://github.com/RamonUnch/AltSnap/files/7196921/AltSnap1.47test15bin.zip)
x86_64 builds [AltSnap1.47test15bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/7196922/AltSnap1.47test15bin_x64.zip)

You can disable the **Resize all windows** option in the General Tab and it should be fine.
If there is a window that is lacking the resizing borders that you need to resize, then you can add it to the `AResize` whitelist in the `[Blacklist]` section of the .ini file.

**Comment by xzayn** [comment]
Thanks for the response, I just now saw as I wasn't receiving notifs. I downloaded 1.47test16bin, can you guide me to use Win key for more controls?

**Comment by xzayn** [comment]
Ok I cant use it very well. It's doing random things. Snapping other windows the same way (without the background blur in win11) witht the jerky motion when even when I'm not pressing a key... and cant close a window clicking on the close button

**Comment by RamonUnch** [comment]
Try with latest test build:
[AltSnap1.47test20bin.zip](https://github.com/RamonUnch/AltSnap/files/7225714/AltSnap1.47test20bin.zip)
[AltSnap1.47test20bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/7225715/AltSnap1.47test20bin_x64.zip)

If you want more keyboard/mouse combo, you can as exemple:
1) Select **Alt key** and **Win key** as **Hotkeys** in the **Keyboard** tab
2) Select the **Win key** as the **Modifier key for alternate action**.
3) Go to the **Mouse** tab and click on the **2. Alternate** radio button.
4) Configure alternate actions for all of your mouse buttons, do not forget to hit Apply before clicking again the radio button.

Then Alt+Click will do the primary action and Win+Click will do the alternate action.

**Comment by xzayn** [comment]
Is it possible to package it into an installer for you? This replaces my .ini file ... I understand if it's not possible...

**Comment by xzayn** [comment]
Ok so this build is working very gracefully and I'm so thankful you implemented the features so nicely!
![image](https://user-images.githubusercontent.com/74079803/134685353-5443fba0-bfd9-4c9a-8b03-deca1223c8a5.png)
This is what I've done with Win+ controls, not defining win+left mouse right now 'cos alt and win are so close and could get messy.
Thanks again dude!

**Comment by xzayn** [comment]
So this might be out of scope of this utility, but when I maximise a window its a jerk motion unlike how windows shows an animation when maximising... I can attach a video if you want...

**Comment by RamonUnch** [comment]
> So this might be out of scope of this utility, but when I maximise a window its a jerk motion unlike how Windows11 shows an animation when maximising... I can attach a video if you want...

True, I do not play the Maximize animation, I did not realize that because I always disable the animations anyway, but it is a legit concern, create a new issue, so I do not forget and remember to give it a look.

> Is it possible to package it into an installer for you? This replaces my .ini file ... I understand if it's not possible...

Next releases test build I will give the x64 installer as well. I understand it can be a trouble for ini files.
Here you go... https://github.com/RamonUnch/AltSnap/issues/83#issuecomment-926651615

Note I close this issue, because those comments would be better on their specific issues, this is mostly my fault. though.
