### ISSUE TITLE
Crash with 64 build

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#99]
Crash occurs when changing and accepting settings in the mouse tab.
Only affects the 64bit test builds.

**Comment by RamonUnch** [comment]
I got the crash too, thanks, I will see what to do...

**Comment by RamonUnch** [comment]
Stupid access out or array bound, I was lucky it would not crash in 32b mode...
[AltSnap1.47test16bin.zip](https://github.com/RamonUnch/AltSnap/files/7202081/AltSnap1.47test16bin.zip)
[AltSnap1.47test16bin_x64.zip](https://github.com/RamonUnch/AltSnap/files/7202082/AltSnap1.47test16bin_x64.zip)
